### ISSUE TITLE
Compile the library not in a workspace

### ISSUE THREAD

**Issue by yoasha** [0xced/XCDYouTubeKit#101]
Hi,
First to say, this is an amazing library! It works perfectly and integrating the API into my project was extremely easy and fast.
I found one minor limitation in the library that can be easily fixed. The library forces users to create a workspace and add their own project plus this library project in order to compile.
The following code can remove this limitation so users can choose their prefered method:
```objc
#ifdef XCD_YOUTUBE_KIT_TARGET_WORKSPACE
  #import <XCDYouTubeKit/XCDYouTubeOperation.h>
#else
  #import "XCDYouTubeOperation.h"
#endif
```
Or the other way around: (depends on what you'd like to the default behavior)
```objc
#ifndef XCD_YOUTUBE_KIT_TARGET_PROJECT
  #import <XCDYouTubeKit/XCDYouTubeOperation.h>
#else
  #import "XCDYouTubeOperation.h"
#endif
```
Any thoughts?

**Comment by 0xced** [comment]
I don’t understand what problem you are trying to solve. Importing XCDYouTubeKit.xcodeproj into a `.xcworkspace` or into another `.xcodeproj` works fine regarding header imports. Drag & drop import of direct source and header files is not supported and never will be.

Also, using [CocoaPods](http://www.cocoapods.org) or [Carthage](https://github.com/Carthage/Carthage/) can greatly reduce friction when trying to compile third-party open source libraries.
