### ISSUE TITLE
Problems when creating iOS archive

### ISSUE THREAD

**Issue by yoasha** [0xced/XCDYouTubeKit#102]
When I import XCDYouTubeKit to my own project (by dragging XCDYouTubeKit.xcodeproj into my own project) and trying to archive, I am getting a "Generic Xcode Archive". Only when I am changing "Skip Install" to YES within XCDYouTubeKit.xcodeproj I can successfully create a valid iOS archive. 

Is there any workaround to this without modifying XCDYouTubeKit project file?

**Comment by 0xced** [comment]
You are right, `SKIP_INSTALL` should be set to `YES`. It will be in the next release of XCDYouTubeKit. In the meantime, modifying the XCDYouTubeKit project file is probably the best workaround.

**Comment by yoasha** [comment]
That will be perfect. Thanks a lot.
