### ISSUE TITLE
background play

### ISSUE THREAD

**Issue by syrakozz** [0xced/XCDYouTubeKit#103]
how i can play the video in background so i can still listen to the song, 
ans appear on the lock screen

**Comment by 0xced** [comment]
Background playback is outside the scope of XCDYouTubeKit.

I have implemented a [hack](https://github.com/0xced/XCDYouTubeKit/blob/master/XCDYouTubeKit%20Demo/iOS%20Demo/MPMoviePlayerController%2BBackgroundPlayback.h) in the demo project but it is not part of the XCDYouTubeKit library and as such is not supported.
