### ISSUE TITLE
Rotation Issue

### ISSUE THREAD

**Issue by msmq** [0xced/XCDYouTubeKit#104]
Just portrait orientation is working; Landscape orientation is not working if entire project is in portrait and want this YouTube Player in both orientation. Any fix? Thanks

**Comment by 0xced** [comment]
Landscape orientation works fine in XCDYouTubeVideoPlayerViewController, you need to properly [configure your app](https://developer.apple.com/library/ios/featuredarticles/ViewControllerPGforiPhoneOS/RespondingtoDeviceOrientationChanges/RespondingtoDeviceOrientationChanges.html#//apple_ref/doc/uid/TP40007457-CH7-SW12) to support landscape orientation.
