### ISSUE TITLE
Cannot play a special video

### ISSUE THREAD

**Issue by matrad** [0xced/XCDYouTubeKit#108]
Hello,

i cannot play the video with Identifier TXZoWTvkBqM

Why?
I got no error Notifications

**Comment by 0xced** [comment]
Please see issue #105.

**Comment by matrad** [comment]
using the development branch:
pod 'XCDYouTubeKit', :git => 'https://github.com/psycotica0/XCDYouTubeKit.git', :branch => 'develop'

I'm still unable to play this video?

**Comment by 0xced** [comment]
I meant the `develop` branch of 0xced/XCDYouTubeKit, not psycotica0/XCDYouTubeKit.
