### ISSUE TITLE
Does not load FfM_wS7qYfY

### ISSUE THREAD

**Issue by 0xABC** [0xced/XCDYouTubeKit#112]
However @psycotica0's fix for issue #105 works:  https://github.com/psycotica0/XCDYouTubeKit/commit/898d3105f4

**Comment by 0xced** [comment]
I just released version 2.1.0 and `FfM_wS7qYfY` plays fine with it.

**Comment by 0xABC** [comment]
FfM_wS7qYfY does not work with version 2.1.0 or 2.1.1 from within Canada at least. At the time I posted this issue it worked with @psycotica0's fix (but not after the recent youtube change).
