### ISSUE TITLE
Restricted Videos

### ISSUE THREAD

**Issue by robertocorrales** [0xced/XCDYouTubeKit#113]
Hi, With your KIT we can pass over video copyright restrictions (like VEVO's) etc.. and play them all (Which is really cool!! ;-) ). But, is there any way to get on the same video object which ones have those restrictions? I want to play them but also "mark" them as "with restrictions".

Thanks in advance,

**Comment by 0xced** [comment]
I don't think I want to add this information in the public API.

But you can parse all the stream URLs and if all last query items are `signature` then you probably have a protected video.
