### ISSUE TITLE
App Store approval and video quality

### ISSUE THREAD

**Issue by cannyboy** [0xced/XCDYouTubeKit#114]
App Store guidelines state *If your app delivers video over cellular networks, and the video exceeds either 10 minutes duration or 5 MB of data in a five minute period, you are required to use HTTP Live Streaming.*

I don't know how strict Apple are. Should I use:

    videoPlayerViewController.preferredVideoQualities =  @[@(XCDYouTubeVideoQualitySmall240)];

Would this play any video, and be acceptable to Apple? Have people had XCDYouTubeKit apps admitted when it is possible to play over cellular?

**Comment by 0xced** [comment]
> I don't know how strict Apple are.

They are not strict at all. I recently removed a paragraph (6cba69a535a30693bf2c255596fb28b359c0fe3d) in the README about these requirements because it would make people unnecessarily worried.

> Would this play any video, and be acceptable to Apple? Have people had XCDYouTubeKit apps admitted when it is possible to play over cellular?

Yes, Apple accepts apps playing these videos.
