### ISSUE TITLE
VEVO/WMG issues again...

### ISSUE THREAD

**Issue by nahum365** [0xced/XCDYouTubeKit#116]
Getting this message from VEVO and WMG videos: "This video contains content from VEVO. It is restricted from playback on certain sites. Watch on YouTube"
Here is an example:
https://www.youtube.com/watch?v=AJtDXIazrMo

EDIT: (This is on version 2.1.0, updated via Cocoapods)

**Comment by objectiveCarlo** [comment]
This is also happening to me.

**Comment by mzgaljic** [comment]
I can confirm, happened to me as well.

**Comment by K-IOS** [comment]
Yes, VEVO videos not playing now

**Comment by nokai** [comment]
mmmm Dont work

This video contains content from WMG. It is restricted from playback on certain sites. Watch on YouTube" UserInfo=0x17066f700 {NSURL=https://www.youtube.com/get_video_info?el=embedded&hl=en&ps=default&video_id=ne9MmSeMfuk

**Comment by Quapper** [comment]
Same issue here but I am getting this error when attempting to play protected videos:

_itemFailedToPlayToEnd: {
    kind = 1;
    new = 2;
    old = 0;
}

**Comment by Quapper** [comment]
This issue is still not fixed for me. Video example: OPf0YbXqDm0

**Comment by 0xced** [comment]
I messed the 2.1.1 release with a wrong merge of version 2.1.1. Please make sure to checkout tag 2.1.1 or use CocoaPods.

**Comment by nahum365** [comment]
Works perfectly. Thanks for all your work!

**Comment by dev4you** [comment]
is this issue got fixed? I am using 2.2. still issue exists.
