### ISSUE TITLE
video pause/stop play

### ISSUE THREAD

**Issue by syrakozz** [0xced/XCDYouTubeKit#117]
how i can control the video pause/stop/play

**Comment by 0xced** [comment]
`XCDYouTubeVideoPlayerViewController` is a subclass of `MPMoviePlayerViewController` which has a `moviePlayer` property conforming to the [`MPMediaPlayback`](https://developer.apple.com/library/ios/documentation/MediaPlayer/Reference/MPMediaPlayback_protocol/) protocol.
