### ISSUE TITLE
Youtube video subtitle

### ISSUE THREAD

**Issue by Piero87** [0xced/XCDYouTubeKit#118]
Hi, this is an amazing project, i want know if there is a way to display also the subtitle of youtube video when exist.

thanks

**Comment by 0xced** [comment]
There is currently no way of displaying the subtitles but I may consider adding this feature un a future version of XCDYouTubeKit.

**Comment by chrisb491** [comment]
Hi - sent you an email yesterday.  Are you willing to consider adding subtitles sooner for some donations?  We love the code, but have requirement for subtitles really soon.

Thanks
