### ISSUE TITLE
XCDYouTubeVideoErrorDomain Code=-2

### ISSUE THREAD

**Issue by robertocorrales** [0xced/XCDYouTubeKit#120]
Hi, I'm getting a lot of this errors lately.
What kind of error is Code=-2 error? Is there any way to fix this from my end?

I did a search for Code=-2 but didn't find anything.

Error Domain=XCDYouTubeVideoErrorDomain Code=-2 "The operation couldn’t be completed. (XCDYouTubeVideoErrorDomain error -2.)" UserInfo=0x7fd487d6ccb0 {NSURL=https://www.youtube.com/get_video_info?el=detailpage&hl=en&ps=default&video_id=UjUkjpJa6bY}

Thanks,

**Comment by 0xced** [comment]
Code -2 is [`XCDYouTubeErrorNoStreamAvailable`](https://github.com/0xced/XCDYouTubeKit/blob/646cba4400daca847799fee1eea4610e9dd68dc9/XCDYouTubeKit/XCDYouTubeError.h#L19) in `XCDYouTubeVideoErrorDomain`. I can’t reproduce your issue with video `UjUkjpJa6bY`, are you using the latest version of XCDYouTubeKit, i.e. 2.1.1?

**Comment by robertocorrales** [comment]
How do I know which version is it? I didn't use cocoapods to install it. I did the download-drag thingy a couple of weeks ago... Could it be this?

**Comment by 0xced** [comment]
Yes it could be. If you don’t use CocoaPods, I strongly suggest you to follow the [installation](https://github.com/0xced/XCDYouTubeKit/blob/2.1.1/README.md#installation) instructions with [version 2.1.1](https://github.com/0xced/XCDYouTubeKit/releases/tag/2.1.1).

Please try again with version 2.1.1 and see if it fixes your problem.

**Comment by robertocorrales** [comment]
OK, I'll do that and let you know. THANKS!!!

**Comment by arno608rw** [comment]
Good job

**Comment by robertocorrales** [comment]
Yeah!!! It seems to work with this fresh installation thru CocoaPods. THANKS A LOT!!!!

**Comment by peterpaulis** [comment]
having the same problem with latest version and video https://www.youtube.com/watch?v=7jTyvm27EsE

**Comment by k06a** [comment]
Having same problem on `2.5.2` with video http://www.youtube.com/watch?v=BsXkSldJuQ8

**Comment by k06a** [comment]
Looks like Google changed script to this version:
```
var _yt_player={};(function(g){ … })(_yt_player);
```
