### ISSUE TITLE
YouTube TOS and Appstore policy

### ISSUE THREAD

**Issue by demonoid67** [0xced/XCDYouTubeKit#121]
Hey! I know this lib breaks youtube TOS, but can it be used for playing videos  in a appstore app without being rejected?

**Comment by 0xced** [comment]
Yes, it can. See my reply in #114.

**Comment by demonoid67** [comment]
Thanks! But what if i decide to play a youtube stream using get_info link. Will then the app be rejected?

**Comment by 0xced** [comment]
No. Again, please read issue #114.

**Comment by niklaskorz** [comment]
Actually, our app was rejected because we are violating the YouTube TOS. So depending on the person reviewing your app, this library might not be approved.

**Comment by 0xced** [comment]
According to [App Store Review Guidelines History](http://www.appstorereviewguidelineshistory.com), section 8.6 was added on March 12, 2015 and states:
> Apps that include the ability to download music or video content from third party sources (e.g. YouTube, SoundCloud, Vimeo, etc) without explicit authorization from those sources will be rejected

So yeah, this may have changed recently. :-(

**Comment by arslanraza** [comment]
I want to use this library in my iOS project but I am concerned about the Appstore Approval process. The youtube videos I will be playing  in my app will mostly have less than 5 minutes duration. So my question is
- Can i use XCDYouTubeKit in my application if I want it to go live on app store?
- Or should I go with the Official library provided by youtube.?

**Comment by chamroeunbm** [comment]
Quoted:
"According to App Store Review Guidelines History, section 8.6 was added on March 12, 2015 and states:

Apps that include the ability to download music or video content from third party sources (e.g. YouTube, SoundCloud, Vimeo, etc) without explicit authorization from those sources will be rejected
So yeah, this may have changed recently. :-(
"

But if just play(not download), it's ok right?

**Comment by 0xced** [comment]
Yes, it's OK.

**Comment by goktugyil** [comment]
How do they even track if it is downloaded vs played? From the size of app storage?

**Comment by niklaskorz** [comment]
They load the video, cut off internet connection, and if it's still working/playing, they consider it a violation of the guidelines.,

**Comment by codaman** [comment]
No, i believe that they have decompile tools and they can learn which libraries you have used easily. For example you are using nsurlconnection or nsurlsession for downloading. if you said i haven't let users to download videos they said why you've used nsurlconnection or nsurlsession so it is too hard to fool Apple.

**Comment by niklaskorz** [comment]
That as well, but in our case we didn't even download the video / stored it for offline usage. It was still considered a violation.

**Comment by codaman** [comment]
Yes, unfortunately . i have an app thats using xcd. Apple is decomposing in review and always rejecting my app. Now it is impossible to use this framework anymore.

**Comment by nickv2002** [comment]
Can anyone else confirm that Apple is rejecting apps using this framework categorically as @niklaskorz and @codaman are suggesting?

**Comment by whoisdis** [comment]
Had an app approved 2 days ago without an issue...

**Comment by codaman** [comment]
i've tried 4 times and rejected. now, i sent a new binary 5 days ago without xcdyoutubekit , i'm waiting result

**Comment by codaman** [comment]
may be my app is in black list

**Comment by codaman** [comment]
@whoisdis do you allow users to download or only watch. how apple approve your app

**Comment by whoisdis** [comment]
Only watching in this app.

**Comment by niklaskorz** [comment]
Okay, to make things clear: Our app has been accepted. But as I mentioned, we were rejected at first before we did not stop playback when the user loses internet connection, which Apple considered a way to make the content available offline. After "fixing" this, we had no further trouble using XCDYouTubeKit.

**Comment by wilburckwong** [comment]
@niklaskorz May I know how to "fixing" that?

**Comment by vitalii-boiarskyi** [comment]
Hi, can anyone point me to a place in Youtube TOS that is being violated by the library? Or explain in more details what is violated?
