### ISSUE TITLE
Video dont work... No error

### ISSUE THREAD

**Issue by nokai** [0xced/XCDYouTubeKit#122]
This Video: [tg00YEETFzg] Rihanna - We Found Love ft. Calvin Harris

Dont work and says no errors

**Comment by 0xced** [comment]
It looks like this issue is related to #119. I will investigate.

**Comment by airrons** [comment]
hello ,i'm willing to konw have you found any ideas to solve this issue ?
many videos by vevo cannot be played since 28 Feb.   Waiting for your reply .
