### ISSUE TITLE
Cannot find Products - all are "corrupted"

### ISSUE THREAD

**Issue by aej** [0xced/XCDYouTubeKit#123]
When doing a manual install - I try to load up the Xcode project and go into the "Products" folder, all the products are red, meaning they're corrupted and cannot be found. Can you upload them as an attachment to this reply, or send me a link where I can download them? I need it for a project, but cannot find it in your project. I'd love to donate if I could get a speedy response. I cannot use the other two methods that you mentioned, they need to be the manual installation in my project.

**Comment by 0xced** [comment]
Please read the [installation instruction](https://github.com/0xced/XCDYouTubeKit/blob/2.1.1/README.md#installation) carefully. Everything is explained for a manual installation.
