### ISSUE TITLE
Strange Issue with Fullscreen

### ISSUE THREAD

**Issue by Urkman** [0xced/XCDYouTubeKit#124]
I start the video as an inline player, this works fine.
Then I switch to Fullscreen and the video stops and it says "Loading...".

When I now tap the "skip back" button, the video starts playing...

I'm using version 2.1.1.
Any idea on this?

**Comment by 0xced** [comment]
I can not reproduce this behavior in the demo app. Could you please provide a test app that demonstrates this behavior?

**Comment by Urkman** [comment]
OK... Found the problem...

It was caused, by a cleanup call in viewDidDisapear.
I wrapped it in "if ([self isMovingFromParentViewController]) {" and everything is fine :)

**Comment by 0xced** [comment]
Glad you solved it!

**Comment by FlorianBasso** [comment]
Hi, 

I have the same issue.
I display the video in a view then when I want to go fullscreen it displays " Loading" until I press the Skip button.

My code is : 

            [[XCDYouTubeClient defaultClient] getVideoWithIdentifier:videoIdentifier completionHandler:^(XCDYouTubeVideo *video, NSError *error) {
                if (video)
                {
                    // Do something with the `video` object
                    XCDYouTubeVideoPlayerViewController *videoPlayerViewController = [[XCDYouTubeVideoPlayerViewController alloc] initWithVideoIdentifier:videoIdentifier];
                    [videoPlayerViewController.moviePlayer setShouldAutoplay:NO];
                    [videoPlayerViewController.moviePlayer setAllowsAirPlay:YES];
                    [videoPlayerViewController presentInView:self.view];
                    [self setViewControllers:@[videoPlayerViewController] direction:UIPageViewControllerNavigationDirectionForward animated:YES completion:nil];
                }
                else
                {
                    // TODO: Handle error, Display Alert View
                    
                }
            }];

Where did you put the condition "if ([self isMovingFromParentViewController]) " ?
