### ISSUE TITLE
video playlist

### ISSUE THREAD

**Issue by syrakozz** [0xced/XCDYouTubeKit#125]
could you plz add a playlist logic , 
per example if we can add a several youtube id, to the project, 
and it will play the next item when the current finish , 
and could you plz add a delegation perexample on video complete

**Comment by 0xced** [comment]
Please have a look at my answer to issue #16.

**Comment by syrakozz** [comment]
thank you ,
it will be great if you can add it in the example project, since most of the user ask for it, 
and if you can add some easy api to handle it in the core project it will an excellent feature, 
a queue perexample ..
