### ISSUE TITLE
Higher quality audio...?

### ISSUE THREAD

**Issue by SoneeJohn** [0xced/XCDYouTubeKit#126]
Before I start, I want to thank you for building this awesome and regularly maintained library.

I've been using this class as the backbone for my YouTube downloader which has been really great for the most part. I noticed that the DASH (audio only) the only Itag value for AAC audio is 140. I was wondering if it is possible to get the Itag value of 141 so that I can get higher quality audio. Finally, I've noticed anytime I try to download audio the audio is downloading very slowly and is not taking advantage of all the bandwidth that I have. However, when trying video they download much quicker and is able to use all the bandwidth. I've tested this on multiple computers in multiple locations and the results are always the same. Can you please shed some light on this matter?

Thanks

**Comment by 0xced** [comment]
Sorry, I have no idea about the itag 141 (DASH M4A AAC 256 kbit/s) stream. Manipulating the streams is outside the scope of XCDYouTubeKit. I’d be happy to learn about your findings though, don’t hesitate to post more information here.
