### ISSUE TITLE
video buffer

### ISSUE THREAD

**Issue by syrakozz** [0xced/XCDYouTubeKit#129]
could you plz add some video buffer logic or some tiny preload, 
like facebook its very fast when we play video, 
its like facebook has already prepare the beginning of the video in the background, 
so in this case XCDYouTubeKit will became so much faster

**Comment by 0xced** [comment]
You should be able to achieve preloading by calling the [`prepareToPlay`](https://developer.apple.com/library/prerelease/ios/documentation/MediaPlayer/Reference/MPMediaPlayback_protocol/index.html#//apple_ref/occ/intfm/MPMediaPlayback/prepareToPlay) method on your `MPMoviePlayerController`:
> **Discussion**
If a movie player is not already prepared to play when you call the [`play`](https://developer.apple.com/library/prerelease/ios/documentation/MediaPlayer/Reference/MPMediaPlayback_protocol/index.html#//apple_ref/occ/intfm/MPMediaPlayback/play) method, that method automatically calls this method. However, to minimize playback delay, call this method before you call `play`.
