### ISSUE TITLE
Vevo playback error.

### ISSUE THREAD

**Issue by lacyleo** [0xced/XCDYouTubeKit#130]
This ID: OPf0YbXqDm0
Error:
Playback Error
Error Domain=XCDYouTubeVideoErrorDomain Code=2 "Invalid parameters." UserInfo=0x7f835876df90 {NSURL=https://www.youtube.com/get_video_info?el=detailpage&hl=en&ps=default&video_id=OPfOYbqDmO, NSLocalizedDescription=Invalid parameters.

Its happened with a lot of Vevo videos. Please fix it.

**Comment by airrons** [comment]
the issue also occured to me ~ Any solutions to this problem?

**Comment by lacyleo** [comment]
When using DemoInlineViewController play -> it’s okay, when inline player starting play, get url from MPmoviecontroller player. it’s my way.

**Comment by 0xced** [comment]
The `XCDYouTubeVideoErrorDomain` error code 2 (`XCDYouTubeErrorInvalidVideoIdentifier`) means that the video identifier is invalid. Please double check that there’s no extra space or anything else that would render the video identifier invalid.

The video `OPf0YbXqDm0` works fine for me with the latest version of XCDYouTubeKit (2.1.1).

**Comment by lacyleo** [comment]
Thanks

2015-03-31 1:04 GMT+07:00 Cédric Luthi <notifications@github.com>:

> Closed #130 <https://github.com/0xced/XCDYouTubeKit/issues/130>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/0xced/XCDYouTubeKit/issues/130#event-268754797>.
>



-- 

*Leo.*
Call : 841205927028
Skype: lacy.mobioneer
