### ISSUE TITLE
background play in pod

### ISSUE THREAD

**Issue by syrakozz** [0xced/XCDYouTubeKit#131]
could you pls add the background file logic to the pod

**Comment by 0xced** [comment]
As I already told you in #103:
> Background playback is outside the scope of XCDYouTubeKit.

You can implement a safe (non-hacky) version of background playback yourself, see [Technical Q&A QA1668 — Playing media while in the background using AV Foundation on iOS](Playing media while in the background using AV Foundation on iOS)

**Comment by syrakozz** [comment]
the link is dead

**Comment by 0xced** [comment]
I fixed the link.
