### ISSUE TITLE
New Issue with the signature

### ISSUE THREAD

**Issue by hectordominguez00** [0xced/XCDYouTubeKit#132]
It fails to play video with signature.

Thanks!

**Comment by 0xced** [comment]
I can’t reproduce this issue. Please provide a specific YouTube video identifier which is failing for you. Also, please properly describe what *fails to play* mean, see the [contributing guidelines](https://github.com/0xced/XCDYouTubeKit/blob/master/CONTRIBUTING.md).

**Comment by hectordominguez00** [comment]
Its failing getting  the streaming url in videos with signature.
I think it is failing to decode it.

For example : With this video id: EVr__5Addjw

**Comment by hectordominguez00** [comment]
Im Sorry now its  working again!
