### ISSUE TITLE
XCDYouTubeVideoPlayerViewControllerDidReceiveVideoNotification : app crashed

### ISSUE THREAD

**Issue by ananarola** [0xced/XCDYouTubeKit#133]
While i am running first video all working well but while i am playing another video at that time it crashes app : 
XCDYouTubeVideoPlayerViewControllerDidReceiveVideoNotification at calling this point in XCDYouTubeVideoPlayerViewController.m class

Need help to solve this

**Comment by 0xced** [comment]
Please have a look at the [guidelines for contributing](https://github.com/0xced/XCDYouTubeKit/blob/master/CONTRIBUTING.md#submitting-issues) and provide all required information. I’m sorry I can’t help you with so little information about the crash.

**Comment by 0xced** [comment]
No reply from OP for one month, so I’m closing the issue.
