### ISSUE TITLE
DASH support

### ISSUE THREAD

**Issue by zumbl** [0xced/XCDYouTubeKit#135]
Do you have support to play arbitrary DASH videos through the library? If no, do you know any libraries based out of iOS which have such support?

**Comment by 0xced** [comment]
Playback of DASH videos is outside the scope of XCDYouTubeKit. But you can get the URL of DASH streams with the `XCDYouTubeClient` class. For example, you can get the DASH audio only stream (AAC 128 kbits/s) which is itag 140 just like this: `NSURL *audioOnlyStreamURL = video.streamURLs[@140];`

I even think iOS 8 is able to play DASH streams but as I said earlier, DASH *playback* is outside the scope of XCDYouTubeKit so I’ll let you experiment yourself.
