### ISSUE TITLE
extracted video redirected to youtube.com/devicesupport video

### ISSUE THREAD

**Issue by chawei** [0xced/XCDYouTubeKit#136]
does anyone have problems on playing videos today? there are a bunch of videos redirected to youtube.com/devicesupport video in my app. i know youtube has made some changes on their APIs today, but does that affect anything?

**Comment by SoneeJohn** [comment]
It looks like it has to deal with usage of the YouTube API V2.

**Comment by 0xced** [comment]
As @SoneeJohn said, this issue is about the YouTube v2 API. XCDYouTubeKit is not using the official YouTube API and is still working fine.

**Comment by chawei** [comment]
yep you guys are right. i was using v2 to search and some of those video ids are invalid. thanks for answering!
