### ISSUE TITLE
Youtube - sign in to confirm your age.

### ISSUE THREAD

**Issue by Madhukar83** [0xced/XCDYouTubeKit#137]
Hello, Thanks for your amazing work.  Most of the videos work, but there are some where it says sign in to confirm your age. This is on iOS device though. Here are couple of video id's where I run into this issue. Can you please let me know what's missing or how should I go about it. 

KGZzuVNwJHY
GzaiLoKt3fg

**Comment by Madhukar83** [comment]
Thanks for taking care of this. Works like a charm now.

**Comment by iKorich** [comment]
checked on versions 2.5.0-2.7.3:

Error Domain=XCDYouTubeVideoErrorDomain Code=150 "Sign in to confirm your age" UserInfo={NSURL=https://www.youtube.com/get_video_info?el=detailpage&hl=en&ps=default&video_id=NeQM1c-XCDc, NSLocalizedDescription=Sign in to confirm your age}
