### ISSUE TITLE
Making playlist video problem

### ISSUE THREAD

**Issue by lidoapps** [0xced/XCDYouTubeKit#140]
Hi,
I make an music app using your library.
I make playlist for my app and in the foreground it works perfect, but when the app go background it sometime doesn't change video.

I handle delegate "moviePlayerPlaybackDidFinish:" and "setVideoIdentifier:" to change video 

Thanks

**Comment by 0xced** [comment]
Background playback is outside the scope of XCDYouTubeKit.

I have implemented a [hack](https://github.com/0xced/XCDYouTubeKit/blob/master/XCDYouTubeKit%20Demo/iOS%20Demo/MPMoviePlayerController%2BBackgroundPlayback.h) in the demo project but it is not part of the XCDYouTubeKit library and as such is not supported.

You can implement a safe (non-hacky) version of background playback yourself, see [Technical Q&A QA1668 — Playing media while in the background using AV Foundation on iOS](https://developer.apple.com/library/ios/qa/qa1668/_index.html)
