### ISSUE TITLE
Playback in background fails because of [MPAVController _pausePlaybackIfNecessaryIgnoringVideoLayerAttachment]

### ISSUE THREAD

**Issue by orkenstein** [0xced/XCDYouTubeKit#141]
Thanks again for your BackgroundPlayback category.
I know, you do not support it, but I ask for help.
You register to UIApplication notifications in `+load` to ensure that category receives it as soon as possible. But, sometimes it does not help. My player gets paused by `[MPAVController _pausePlaybackIfNecessaryIgnoringVideoLayerAttachment]` called from `[MPAVController _applicationWillResignActive:]`.
Any chance to register even EARLIER?
Thanks

**Comment by 0xced** [comment]
Have you set the `PlayVideoInBackground` user default to `YES`? This is required for background playback to work.

**Comment by orkenstein** [comment]
@0xced, you mean backgroundPlaybackEnabled = YES
Yes, of course.

**Comment by orkenstein** [comment]
WOW, it works. Just added:
```    [[NSUserDefaults standardUserDefaults] setBool:YES forKey:@"PlayVideoInBackground"];
```

Any idea why it works for iOS 8.3?

**Comment by 0xced** [comment]
This behavior may have changed over the different iOS versions, it’s safer to always set the `PlayVideoInBackground` user default to what you want.
