### ISSUE TITLE
vevos videos playing issue

### ISSUE THREAD

**Issue by ronggong** [0xced/XCDYouTubeKit#145]
Although with version 2.1.3, vevos video still can't be played.
I cloned the master branch, compiled the static library, added includes to search path.
However, vevos video still not working, other videos are played normally.

**Comment by 0xced** [comment]
Please make absolutely sure you are using version 2.1.3. I just tested some VEVO videos and they are playing fine. If a video is still not working for you on version 2.1.3, please report the specific YouTube video identifier having issues.

**Comment by ronggong** [comment]
like these ids: PVjiKRfKpPI, CevxZvSJLk8, KWZGAExj-es. This one works: F_JF8oSxXtM. Thanks.

**Comment by ronggong** [comment]
Besides, could you show me how to compile your demo on iOS? I want to test on your demo if the same problem appears, but it complains ld: 
<b>
library not found for -lXCDYouTubeKit
clang: error: linker command failed with exit code 1 (use -v to see invocation)
</b>
However, I have added libXCDYouTubeKit.a in Link Binary with Libraries.

**Comment by 0xced** [comment]
> like these ids: PVjiKRfKpPI, CevxZvSJLk8, KWZGAExj-es.

I tried them and they are all playing fine.

> Besides, could you show me how to compile your demo on iOS?

You have to open **XCDYouTubeKit Demo.xcworkspace** instead of XCDYouTubeKit Demo.xcodeproj. Choose the *XCDYouTubeKit Demo iOS* scheme and it will run.

Please try to play those videos in the demo app, it has several logs that could help me to understand what’s going on.

**Comment by ronggong** [comment]
It works right now. Thank you. I dragged the XCDYouTubeKit .xcodeproj into my project, and compiled the static library. 
Previously, I only compiled the static library on its own.
Is there any difference between these two compilations?

**Comment by 0xced** [comment]
Glad it works!

Compiling the library on its own or as a dependency for another project is equivalent.
