### ISSUE TITLE
Turn off sound

### ISSUE THREAD

**Issue by chamroeunbm** [0xced/XCDYouTubeKit#148]
Hi,
I want only to play the video and use my own local sound file playing from another source.

How can I turn off the sound and play only video? As far as i know, MPMoviePlayercontroller doesn't have this function and by this "[[MPMusicPlayerController applicationMusicPlayer] setVolume:0]" will turn off everything.

Any suggestion?

**Comment by 0xced** [comment]
Indeed you can’t control volume with a `MPMoviePlayerController`.

Instead I suggest you to use the [XCDYouTubeClient](http://cocoadocs.org/docsets/XCDYouTubeKit/2.1.3/Classes/XCDYouTubeClient.html#//api/name/getVideoWithIdentifier:completionHandler:) API to get a `XCDYouTubeVideo` object and choose a [stream URL](http://cocoadocs.org/docsets/XCDYouTubeKit/2.1.3/Classes/XCDYouTubeVideo.html#//api/name/streamURLs) that you will play with [AVFoundation](https://developer.apple.com/library/ios/documentation/AVFoundation/Reference/AVFoundationFramework/index.html) where you have great control over media playback.

**Comment by chamroeunbm** [comment]
Thanks for guiding me to the right direction. yes, after a few hacking with the AVPlayer, I can get what I want.


Thanks;
