### ISSUE TITLE
Player controls not working in "presentViewController" ?

### ISSUE THREAD

**Issue by sahil263** [0xced/XCDYouTubeKit#150]
I am playing the videos as "InlineView" in  a `presentViewController `

`[self.videoPlayerViewController presentInView:imgArtwork];`

The video is playing fine. But, I am not able to use the player controls.
No play/pause, no full-screen.

How, can I make the player controls work in `presentViewController`?

![ios simulator screen shot 08-jun-2015 4 15 36 pm](https://cloud.githubusercontent.com/assets/4958184/8033288/9f3ca562-0dfa-11e5-8861-cfae6aae995a.png)

**Comment by sahil263** [comment]
I also tried it with `pushViewController`. But, still the player controls are not working...

More information:
. I am adding `presentInView` on an `UIImageView`.

I am not able to figure out what I am missing...

**Comment by sahil263** [comment]
Finally, I figured out the issue.

`presentInView` doesn't works on an `UIImageView`.

**Comment by 0xced** [comment]
Glad you figured it out. That’s probably because `UIImageView` overrides the `userInteractionEnabled` property to return `NO`.

**Comment by sahil263** [comment]
@0xced Yeah!
You are right... I forgot the set the `UIImageView's` `userInteractionEnabled` property to `yes`.

Later I realised that according to my requirements. It's best to use a separate `UIView` for the video player.

Anyways, thanks for your time. I appreciate it!
