### ISSUE TITLE
Warning rewrite JavaScriptCore

### ISSUE THREAD

**Issue by Piero87** [0xced/XCDYouTubeKit#153]
Hi,
i switch the version of my project from iOS 6 to iOS 7 and now i receive this warning:

#warning Rewrite JavaScriptCore code with JSContext + JSValue (available since iOS 7) instead the verbose C API.

how i can fix this? 
 i can simply add the -w flag to silent the warning? or i have do something wrong?

thanks!

**Comment by 0xced** [comment]
Using XCDYouTubeKit by drag&dropping source files is not supported. The only supported ways are CocoaPods or using the static library or framework targets. Please see the [installation][1] instructions.

[1]: https://github.com/0xced/XCDYouTubeKit/blob/2.1.3/README.md#installation

**Comment by Piero87** [comment]
thanks for the answer, i have always add your library in my project with a drag&drop and always work, i can simply silent the warning? or there is something wrong?
