### ISSUE TITLE
setInitialPlaybackTime ignored

### ISSUE THREAD

**Issue by aarsla** [0xced/XCDYouTubeKit#155]
Not sure if this is XCDYouTubeKit related, but here it goes:

[self.videoPlayerViewController.moviePlayer setInitialPlaybackTime:15];

has no effect anymore - video starts from the beginning ...

**Comment by 0xced** [comment]
The `setInitialPlaybackTime:` method belongs to the `MPMoviePlayerController` class, which XCDYouTubeKit has no control over.

I'd suggest you to file a bug on [Apple Bug Reporter](https://bugreport.apple.com) if this stopped working for you.
