### ISSUE TITLE
Move to AVPlayerViewController from the AVKit framework

### ISSUE THREAD

**Issue by BenHetherington** [0xced/XCDYouTubeKit#157]
In iOS 9, MPMoviePlayerViewController will be deprecated. It's probably about time to move away from it, in favour of the AVKit classes, like AVKitPlayerViewController. This could be cause for some refactoring, since AVKitPlayerViewController cannot be subclassed, but if this keeps XCDYouTubeKit working in the future (and with features like Picture-in-Picture), then it should be worth the effort in the long run.

**Comment by 0xced** [comment]
It's already pretty simple to use an `AVPlayerViewController` by creating an `AVPlayer` with a stream URL from a `XCDYouTubeVideo` but I will definitely consider adding a convenience class in the next version of XCDYouTubeKit.

**Comment by neen1** [comment]
@0xced , do you think that you can integrate the AVPlayer before iOS 9 will be released to the public? Would be really amazing and a donation is guaranteed ;)

**Comment by 0xced** [comment]
I’m working on it, but it takes time because I want to support both `AVPlayerViewController` and `MPMoviePlayerViewController`. As I said in my previous comment, it’s already pretty simple to get `AVPlayerViewController` working with XCDYouTubeKit. Try it and you will see it’s only a few lines of code.

**Comment by neen1** [comment]
@0xced - what does the update on the develop build include?

**Comment by 0xced** [comment]
I haven’t pushed anything related to AVPlayerViewController yet but I’m still working on it.

**Comment by neen1** [comment]
Ok cool, looking forward to it, so that we can mentain our app :) 

Anyway, how customizable is the AVPlayer from the User Interface Design side?

**Comment by gomera** [comment]
@0xced Just a tiny note, MPMoviePlayerViewController does not work on tvOS because of the same reason. It is deprecated. Anyway, I am planning to make a fork and try to fix it, will it help or are you almost done with the changes? Thanks.

**Comment by Bruno-Furtado** [comment]
@0xced,

I tried to implement the AVPlayerViewController but it doesn't support web pages, only videos.
http://example.com/video.mp4

I also tried to implement the video with WKWebView. 
It worked but the screen just not coming out of the user's field of view.
http://s16.postimg.org/e5qn89rj9/web_video.png

Anyone have any suggestions?

**Comment by ziopiero** [comment]
Hi,
I have the same issue, I tried to remove MPMoviePlayerViewController  in order to use XCDYouTubeVideo  to stream URL video in tvOS.
But some videos (specially VEVO videos) are restricted  and can't be played.
The same code works fine in iOS9.
Basically, iin iOS9 I can play every videos, in tvOS only few (and not the most interesting for my users).
 Any idea how to fix it ?

**Comment by dehlen** [comment]
Any news on this one ? I am using this library in my app too and would love to see a migration to AVPlayerViewController in order to support this library for further releases.

**Comment by ziopiero** [comment]
Ok, I solved myself (but it's my mistake ;-).
Just remove the MPMoviePlayerViewController and replace it with AVPlayer in this way:
    layer = [AVPlayerLayer playerLayerWithPlayer:myPlayer];
    layer.frame = CGRectMake(....);  // 
    [viewFather.layer addSublayer: layer];
    [viewFather bringSubviewToFront:button];
 
Please note that you CAN'T use CocoaPod for install it in tvOS project, but just drag and drop the source file.
Thank again to @0xced for his amazing library

**Comment by dehlen** [comment]
At the moment this is my approach but I am not quite sure if this is 100% correct.. Well works for now.

```swift

@IBAction func playTrailer(sender:UIButton) {
        if videoIdentifier != nil {
            XCDYouTubeClient.defaultClient().getVideoWithIdentifier(self.videoIdentifier!, completionHandler: {(video:XCDYouTubeVideo?, error:NSError?) in
                if video != nil {
                    var streamURL:NSURL?
                    
                    if video!.streamURLs[36] != nil {
                        streamURL = video!.streamURLs[36] as? NSURL
                    }
                    else if video!.streamURLs[18] != nil {
                        streamURL = video!.streamURLs[18] as? NSURL
                        
                    }
                    else if video!.streamURLs[22] != nil {
                        streamURL = video!.streamURLs[22] as? NSURL
                        
                    }
                    if streamURL != nil {
                        let player = AVPlayer(URL: streamURL!)
                        let playerViewController = AVPlayerViewController()
                        playerViewController.player = player
                        dispatch_async(dispatch_get_main_queue(), {
                            self.presentViewController(playerViewController, animated: true) {
                                playerViewController.player?.play()
                            }
                        })
                    }
                    
                }
            })
        }
    }
```

**Comment by 0xced** [comment]
Here is a slightly simpler version with better error handling:
```swift
func playVideo(videoIdentifier: String?) {
	let playerViewController = AVPlayerViewController()
	self.presentViewController(playerViewController, animated: true, completion: nil)
	
	XCDYouTubeClient.defaultClient().getVideoWithIdentifier(videoIdentifier) { [weak playerViewController] (video: XCDYouTubeVideo?, error: NSError?) in
		if let streamURL = (video?.streamURLs[XCDYouTubeVideoQualityHTTPLiveStreaming] ??
		                    video?.streamURLs[XCDYouTubeVideoQuality.HD720.rawValue] ??
		                    video?.streamURLs[XCDYouTubeVideoQuality.Medium360.rawValue] ??
		                    video?.streamURLs[XCDYouTubeVideoQuality.Small240.rawValue]) as? NSURL {
			playerViewController?.player = AVPlayer(URL: streamURL)
		} else {
			self.dismissViewControllerAnimated(true, completion: nil)
		}
	}
}
```

**Comment by dehlen** [comment]
Thanks works like a charm when providing as? NSURL for all possibilities since otherwise the expression is too complex to solve for the compiler because of the type inference.

**Comment by nokai** [comment]
I have to acknowledge the work and effort for this class. But I think it's very necessary that you enter AVPlayerViewController With PiP, AVSession, etc ... 

Similar to MPMoviePlayerController+BackgroundPlayback.h

My donation would be guaranteed

**Comment by nokai** [comment]
Can you add new features to AVPlayerViewController?

- PiP
- Sound in Background

Similar to MPMoviePlayerController+BackgroundPlayback.h

**Comment by 0xced** [comment]
@nokai Here are [16 lines of boilerplate code][1] from the tvOS demo app ready for you to copy-paste in your project for using `AVPlayerViewController`:

```objc
AVPlayerViewController *playerViewController = [AVPlayerViewController new];
[self presentViewController:playerViewController animated:YES completion:nil];

__weak AVPlayerViewController *weakPlayerViewController = playerViewController;
[[XCDYouTubeClient defaultClient] getVideoWithIdentifier:videoIdentifier completionHandler:^(XCDYouTubeVideo * _Nullable video, NSError * _Nullable error) {
	if (video)
	{
		NSDictionary *streamURLs = video.streamURLs;
		NSURL *streamURL = streamURLs[XCDYouTubeVideoQualityHTTPLiveStreaming] ?: streamURLs[@(XCDYouTubeVideoQualityHD720)] ?: streamURLs[@(XCDYouTubeVideoQualityMedium360)] ?: streamURLs[@(XCDYouTubeVideoQualitySmall240)];
		weakPlayerViewController.player = [AVPlayer playerWithURL:streamURL];
		[weakPlayerViewController.player play];
	}
	else
	{
		[self dismissViewControllerAnimated:YES completion:nil];
	}
}];
```

If you prefer swift, please refer to my [comment above][2].

  [1]: https://github.com/0xced/XCDYouTubeKit/blob/1d784c24cc6d6dd0567fec019ed29bbfd1386e89/XCDYouTubeKit%20Demo/tvOS%20Demo/PlaylistCollectionViewController.m?ts=4#L70-L86
  [2]: #issuecomment-144160209

**Comment by nokai** [comment]
Sorry, but I do not speak now of TVOS

I can not find AVPictureInPictureController in AVPlayerViewController

**Comment by 0xced** [comment]
Quoting the official [AVPlayerViewController documentation][1]:

> Starting in iOS 9, supported iPad models also provide Picture in Picture playback from a player view controller.

> [...]

> #### Participating with Picture in Picture
To participate with Picture in Picture (PiP), take the following steps in your Xcode project:

> 1. Link on or after iOS 9.0.

> 2. In the Xcode Capabilities view for your project, select Audio and AirPlay in the Background Modes section.

> 3. Configure your audio session with an appropriate category, such as [AVAudioSessionCategoryPlayback][2], If you have not already done so in your app.

> To respond to user interactions with the PiP window, implement the methods of the [AVPlayerViewControllerDelegate][3] protocol.

> Having configured your project to support Picture in Picture, the player view controller then provides a PiP button for the user, along with the other playback controls.

  [1]: https://developer.apple.com/library/ios/documentation/AVFoundation/Reference/AVPlayerViewController_Class/index.html
  [2]: https://developer.apple.com/library/ios/documentation/AVFoundation/Reference/AVAudioSession_ClassReference/index.html#//apple_ref/c/data/AVAudioSessionCategoryPlayback
  [3]: https://developer.apple.com/library/ios/documentation/AVKit/Reference/AVPlayerViewControllerDelegate_Protocol/index.html#//apple_ref/occ/intf/AVPlayerViewControllerDelegate

**Comment by rodrigoreis22** [comment]
Looking forward for the next major release with AVPlayerViewController. Donation guaranteed here.

**Comment by Talha-Ghous** [comment]
can we use avplayer for ip camera live streaming ?

**Comment by Ali-Sher** [comment]
can we use avplayer,MPMoviePlayerController or  for ip camera live streaming ?

**Comment by Atimca** [comment]
Hello, somebody use new avplayerviewcontroller with autolayout. In my case I have many warnings after launched app.

**Comment by 0xced** [comment]
@Atimca This is bug in `AVPlayerViewController` itself. You will get these warnings too by simply doing this:
```objc
[self presentViewController:[AVPlayerViewController new] animated:YES completion:nil]
```

**Comment by 0xced** [comment]
I will eventually support `AVPlayerViewController` natively in XCDYouTubeKit 3.0.0. In the meantime, please use this.

Objective-C:
```objc
AVPlayerViewController *playerViewController = [AVPlayerViewController new];
[self presentViewController:playerViewController animated:YES completion:nil];

__weak AVPlayerViewController *weakPlayerViewController = playerViewController;
[[XCDYouTubeClient defaultClient] getVideoWithIdentifier:videoIdentifier completionHandler:^(XCDYouTubeVideo * _Nullable video, NSError * _Nullable error) {
	if (video)
	{
		NSDictionary *streamURLs = video.streamURLs;
		NSURL *streamURL = streamURLs[XCDYouTubeVideoQualityHTTPLiveStreaming] ?: streamURLs[@(XCDYouTubeVideoQualityHD720)] ?: streamURLs[@(XCDYouTubeVideoQualityMedium360)] ?: streamURLs[@(XCDYouTubeVideoQualitySmall240)];
		weakPlayerViewController.player = [AVPlayer playerWithURL:streamURL];
		[weakPlayerViewController.player play];
	}
	else
	{
		[self dismissViewControllerAnimated:YES completion:nil];
	}
}];
```

Swift:
```swift
func playVideo(videoIdentifier: String?) {
	let playerViewController = AVPlayerViewController()
	self.presentViewController(playerViewController, animated: true, completion: nil)
	
	XCDYouTubeClient.defaultClient().getVideoWithIdentifier(videoIdentifier) { [weak playerViewController] (video: XCDYouTubeVideo?, error: NSError?) in
		if let streamURL = (video?.streamURLs[XCDYouTubeVideoQualityHTTPLiveStreaming] ??
		                    video?.streamURLs[XCDYouTubeVideoQuality.HD720.rawValue] ??
		                    video?.streamURLs[XCDYouTubeVideoQuality.Medium360.rawValue] ??
		                    video?.streamURLs[XCDYouTubeVideoQuality.Small240.rawValue]) {
			playerViewController?.player = AVPlayer(URL: streamURL)
		} else {
			self.dismissViewControllerAnimated(true, completion: nil)
		}
	}
}
```

I’m locking this issue to avoid getting more noise.

**Comment by SoneeJohn** [comment]
No longer planned.
