### ISSUE TITLE
Long logn console information..

### ISSUE THREAD

**Issue by NBibikov** [0xced/XCDYouTubeKit#158]
Hello! Thank you very much for great work. I use this library on 2-nd project, but now have trouble. When i added library and initialised video, app crushed. I created new project and moved all my code there. Now video opens but i have very long message in console. How can fix that? 
https://www.dropbox.com/s/r9hsegt3usok5q1/console.txt?dl=0
![screen shot 2015-07-11 at 2 28 21 am](https://cloud.githubusercontent.com/assets/8437488/8630880/ad9833ae-2774-11e5-8602-d9d227e1ebac.png)
![screen shot 2015-07-11 at 2 28 28 am](https://cloud.githubusercontent.com/assets/8437488/8630881/adc14bea-2774-11e5-89de-dbc445c032a0.png)
![screen shot 2015-07-11 at 2 28 39 am](https://cloud.githubusercontent.com/assets/8437488/8630882/adc50fb4-2774-11e5-9411-e9da55e66012.png)

**Comment by 0xced** [comment]
You are using CocoaLumberjack, so as stated in the [README](https://github.com/0xced/XCDYouTubeKit/blob/master/README.md#logging) you are responsible for controlling the log levels with the CocoaLumberjack APIs.

The XCDYouTubeKit iOS demo app [demonstrates](https://github.com/0xced/XCDYouTubeKit/blob/2.2.0/XCDYouTubeKit%20Demo/iOS%20Demo/AppDelegate.m#L36) how you could achieve that.

**Comment by NBibikov** [comment]
Sorry, but i don't understand. I looked in README and demo app, but I don't realize what i need to change. Can you help me?
I used CocoaLumberjack with XCDYouTubeKit in my previous project, but did not have situation like this

**Comment by 0xced** [comment]
Please try to setup CocoaLumberjack with `[DDLog addLogger:logger withLevel:DDLogLevelWarning]` instead of `[DDLog addLogger:logger]`, assuming that’s how you do it.

**Comment by NBibikov** [comment]
Thanks! I will try
