### ISSUE TITLE
XCDYouTubeLog ignores Cocoalumberjack log level

### ISSUE THREAD

**Issue by tfonfara** [0xced/XCDYouTubeKit#160]
Hi,

your define of XCDYouTubeLog provides 'NSUIntegerMax' as log level. If Cocoalumberjack isn't included in the project the XCDYouTubeLogger ignores the property and makes use of XCDYouTubeKitLogLevel. But if Cocoalumberjack is included, the LOG_LEVEL_DEF define (compare with Cocoalumberjack 2.0) is ignored and all log levels will be logged.

Best,
Grogster

**Comment by donpark** [comment]
Having same issue. Logging avalanche starts when a video is played: HTML, javascript, everything.
Working around this by no-oping logging macros defined in XCDYouTubeLogger.h for now.

**Comment by 0xced** [comment]
The `LOG_LEVEL_DEF` macro used in CocoaLumberjack is a trick to remove logs at *compile* time. I chose to always compile all logs for XCDYouTubeKit.

To get rid of the verbose logs, you don’t need to modify XCDYouTubeKit, simply specify the log level when you add the logger. If you want errors and warnings only, just add your logger this way:
```objc
[DDLog addLogger:[DDTTYLogger sharedInstance] withLevel:DDLogLevelWarning];
```

Another option is to use the excellent [NSLogger](https://github.com/fpillet/NSLogger) with my [XCDLumberjackNSLogger](https://github.com/0xced/XCDLumberjackNSLogger) logger. With NSLogger, you’ll be able to filter out verbose log with a simple keyboard shortcut.

**Comment by donpark** [comment]
@0xced I can't do what you suggest because, In my project, I have multiple instances of ddLogLevel setup so I can trace at file-level granularity without noise from rest of the app.

Hack or not, I have no problem using GCDWebServer which uses LOG_LEVEL_DEF just fine to keep its logging system out of app's hair.

**Comment by 0xced** [comment]
Then I’d suggest you to use [dynamic level filtering](https://github.com/0xced/XCDYouTubeKit/blob/2.2.0/XCDYouTubeKit%20Demo/iOS%20Demo/AppDelegate.m#L34-L36) with a trivial [custom formatter](https://github.com/0xced/XCDYouTubeKit/blob/2.2.0/XCDYouTubeKit%20Demo/iOS%20Demo/ContextLogFormatter.m) acting as a filter. That’s what I do in the demo app and it works fine for disabling verbose logs.

Also, I reiterate my suggestion to have a look at t [NSLogger](https://github.com/fpillet/NSLogger) and [XCDLumberjackNSLogger](https://github.com/0xced/XCDLumberjackNSLogger), you might reconsider your logging strategy once you try it! 😉

**Comment by donpark** [comment]
I'll check XCDLumberjackNSLogger. I used to use LumberjackNSLogger combo but left it behind because the bridge wasn't being maintained. Looks like your versioin fixes that problem. Thx. :-)

**Comment by 0xced** [comment]
With version 2.5.0 comes a very flexible way to configure XCDYouTubeKit logging, see the new [XCDYouTubeLogger](http://cocoadocs.org/docsets/XCDYouTubeKit/2.5.0/Classes/XCDYouTubeLogger.html) class documentation.

**Comment by donpark** [comment]
great. thx for making life easier. :-)
