### ISSUE TITLE
NSDateComponentsFormatter is iOS 8.0+ only

### ISSUE THREAD

**Issue by SepiaApps** [0xced/XCDYouTubeKit#162]
NSDateComponentsFormatter usage in XCDYouTubeVideo.m, line #198. Added in June causes a crash in non-ios 8.0+ targets.

**Comment by 0xced** [comment]
Can you please provide a full crash log? I tested on an iPad running iOS 5.1.1 and it’s working fine for me.

Also, please have a look at the [contributing guidelines](https://github.com/0xced/XCDYouTubeKit/blob/master/CONTRIBUTING.md) to learn how to properly report an issue.

**Comment by 0xced** [comment]
No reply from OP for one month, so I’m closing the issue.
