### ISSUE TITLE
pod issue

### ISSUE THREAD

**Issue by anhuijhy** [0xced/XCDYouTubeKit#163]
as below (no 2.2.0)

ios$ pod search XCDYouTubeKit

-> XCDYouTubeKit (2.0.3)
   YouTube video player for iOS and OS X.
   pod 'XCDYouTubeKit', '~> 2.0.3'
   - Homepage: https://github.com/0xced/XCDYouTubeKit
   - Source:   https://github.com/0xced/XCDYouTubeKit.git
   - Versions: 2.0.3, 2.0.2, 2.0.1, 2.0.0 [master repo]

**Comment by 0xced** [comment]
Just run the `pod repo update` command and try again. The search command is local only.
