### ISSUE TITLE
Videos don't play in latest iOS 9 beta

### ISSUE THREAD

**Issue by glennschmidt** [0xced/XCDYouTubeKit#164]
Running the same code, and using the same videos that are working for me in iOS 8, but I am unable to play these on iOS 9.

When using the XCDYouTubeVideoPlayerViewController, the controller appears but the screen remains black (the video doesn't load).

If I take one of the stream URLs and use it to set up an AVPlayerViewController, the VC shows the play arrow symbol with a slash through it (which usually means 'unsupported video format').

I'm using iOS 9 beta 4 and XCDYouTubeKit 2.2.0

**Comment by glennschmidt** [comment]
OK I've solved this myself, though it's probably FAQ-worthy.

The problem was caused by the new App Transport Security restrictions. Seems that the video content is not served securely so by default NSURLSession will refuse to load those URLs.

Workaround was to add this to my info.plist:

	<key>NSExceptionDomains</key>
	<dict>
		<key>googlevideo.com</key>
		<dict>
			<key>NSIncludesSubdomains</key>
			<true/>
			<key>NSThirdPartyExceptionAllowsInsecureHTTPLoads</key>
			<true/>
		</dict>
	</dict>

**Comment by 0xced** [comment]
Thanks for your report. You are right this is FAQ-worthy. I'll add a line in the README and a runtime check with a warning if there is no exception for the googlevideo.com domain.

**Comment by 0xced** [comment]
It seems to me that the googlevideo.com domain is now ATS compliant. Please reopen if you find a video that doesn’t play because of ATS.

**Comment by tulurira** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

tulurira3@naver.com 님께 보내신 메일 <Re: [XCDYouTubeKit] Videos don't play in latest iOS 9 beta (#164)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------
