### ISSUE TITLE
Using XCode 7 Beta 5, there are several compiler errors while using project as a static library

### ISSUE THREAD

**Issue by yoasha** [0xced/XCDYouTubeKit#168]
Errors in the following files:
- XCDYouTubeVideoWebpage.m
- XCDYouTubePlayerScript.m

**Comment by 0xced** [comment]
I just fixed it on the `develop` branch, see 5a927a5cad11728f15e7e8fd46bd3d6b31a2a0bf.

**Comment by yoasha** [comment]
Thank you!
