### ISSUE TITLE
Not getting large thumbnail URLs for some videos

### ISSUE THREAD

**Issue by MoridinBG** [0xced/XCDYouTubeKit#169]
Some videos are not getting the large thumbnail, which is available when using the youtube data api on the same video.
One example is https://www.youtube.com/watch?v=bOMv8f9t3DA

The URL returned by the data API is https://i.ytimg.com/vi/bOMv8f9t3DA/hqdefault.jpg

But it works on other videos. I think all vevo videos I tried had the correct large thumbnail URL.

**Comment by 0xced** [comment]
Please note that `smallThumbnailURL`, `mediumThumbnailURL` and `largeThumbnailURL` properties do not match the thumbnail size of the YouTube Data API.

As the [documentation](http://cocoadocs.org/docsets/XCDYouTubeKit/2.2.0/Classes/XCDYouTubeVideo.html#//api/name/largeThumbnailURL) states:
* `largeThumbnailURL`: A thumbnail URL for an image of large size, i.e. 1'280×720 or 1'980×1'080. May be nil.
* `mediumThumbnailURL`: A thumbnail URL for an image of medium size, i.e. 320×180, 480×360 or 640×480. May be nil.
* `smallThumbnailURL`: A thumbnail URL for an image of small size, i.e. 120×90. May be nil.

The `mediumThumbnailURL` for video id `bOMv8f9t3DA` gives https://i.ytimg.com/vi/bOMv8f9t3DA/sddefault.jpg which is 640×480, i.e. larger than https://i.ytimg.com/vi/bOMv8f9t3DA/hqdefault.jpg (which is 480×360).
