### ISSUE TITLE
Is there is way to know when user XCDYouTubeVideoPlayerViewController dismisses?

### ISSUE THREAD

**Issue by kidsid49** [0xced/XCDYouTubeKit#172]
I want to know when XCDYouTubeVideoPlayerViewController is get dimissed so I can do some house keeping activities.

**Comment by 0xced** [comment]
You have to register for `MPMoviePlayerPlaybackDidFinishNotification`, see https://github.com/0xced/XCDYouTubeKit/blob/2.2.0/XCDYouTubeKit%20Demo/iOS%20Demo/DemoFullScreenViewController.m#L36-L55 for an example.
