### ISSUE TITLE
Not update cocoapods V 2.3

### ISSUE THREAD

**Issue by arno608rw** [0xced/XCDYouTubeKit#174]
![screen shot 2558-09-16 at 22 17 04](https://cloud.githubusercontent.com/assets/3774145/9909090/dc78a65a-5cc0-11e5-87d7-8666a73a1e1b.png)

**Comment by 0xced** [comment]
Version 2.3.0 is definitely available on the master spec repository: CocoaPods/Specs@3f4fded6792d640e98406b813eec84e022e460de

Please run `pod repo update` and try again. If it doesn’t work, please [open an issue on the CocoaPods repository](https://github.com/CocoaPods/CocoaPods/issues/new).

**Comment by 0xced** [comment]
```
$ pod search XCDYouTubeKit


-> XCDYouTubeKit (2.3.0)
   YouTube video player for iOS and OS X.
   pod 'XCDYouTubeKit', '~> 2.3.0'
   - Homepage: https://github.com/0xced/XCDYouTubeKit
   - Source:   https://github.com/0xced/XCDYouTubeKit.git
   - Versions: 2.3.0, 2.2.0, 2.1.3, 2.1.2, 2.1.1, 2.1.0, 2.0.3, 2.0.2, 2.0.1, 2.0.0 [master repo]
```
