### ISSUE TITLE
Audio URL Observations

### ISSUE THREAD

**Issue by SoneeJohn** [0xced/XCDYouTubeKit#177]
Hello,
I created a issue similar to this a while but, I decided to open a new issue to report my findings. Just a little background information before I start, basically when use the url by calling: 

```objc
NSURL *audioOnlyStreamURL = video.streamURLs[@140];
```
and using that as download link, it does not use the maximum bandwidth. When using any other iTag value e.g 22, the download uses the maximum bandwidth with my internet connection. For instance, when downloading a file with a iTag value of 22 the download speed is: 1.5 MB/sec however, when doing the same video with a value of 140 I get around 48 KB/sec.

According, to the 'Readme' file,"The URL extraction algorithms in XCDYouTubeKit are inspired by the YouTube extractor module of the youtube-dl project." Therefore, I decided to test downloading the same file using the youtube-dl project. When executing this command in terminal this is what I got:
```
youtube-dl -v -f 140 https://www.youtube.com/watch?v=_p8AsQhaVKI
```

**Output**: 
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-f', u'140', u'https://www.youtube.com/watch?v=_p8AsQhaVKI']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.08.28
[debug] Python version 2.7.10 - Darwin-15.0.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] _p8AsQhaVKI: Downloading webpage
[youtube] _p8AsQhaVKI: Downloading video info webpage
[youtube] _p8AsQhaVKI: Extracting video information
[youtube] _p8AsQhaVKI: Downloading DASH manifest
[youtube] _p8AsQhaVKI: Downloading DASH manifest
[debug] Invoking downloader on 'https://r4---sn-aphx-cbpe.googlevideo.com/videoplayback?id=fe9f00b1085a54a2&itag=140&source=youtube&requiressl=yes&mv=m&ms=au&mn=sn-aphx-cbpe&mm=31&pl=24&pcm2cms=yes&ratebypass=yes&mime=audio/mp4&gir=yes&clen=137867408&lmt=1433969746992771&dur=8680.686&mt=1442598087&upn=6S5J3lzt0v0&sver=3&key=dg_yt0&fexp=9407701,9408710,9409069,9409207,9414736,9415365,9415485,9416023,9416126,9416328,9417380,9417690,9417707,9418153,9418200,9418203,9418448,9418999,9419805,9420078,9420348,9420372,9421013,9421288&signature=95A157940A0A9DE0AA55EDC0665D9252DBFC5049.05D413BF0BF6DE4A3EF3725760EA909BBF930975&ip=162.252.188.79&ipbits=0&expire=1442619814&sparams=ip,ipbits,expire,id,itag,source,requiressl,mv,ms,mn,mm,pl,pcm2cms,ratebypass,mime,gir,clen,lmt,dur'
[download] Resuming download at byte 26849280
[download] Destination: Apple - WWDC 2015-_p8AsQhaVKI.m4a
[download]  66.7% of 131.48MiB at  1.23MiB/s ETA 00:35
```
Two things that caught my attention was:
* The download speed: **[download]  66.7% of 131.48MiB at  1.23MiB/s ETA 00:35**
* And the download URL: **https://r4---sn-aphx-cbpe.googlevideo.com/videoplayback?id=fe9f00b1085a54a2&itag=140&source=youtube&requiressl=yes&mv=m&ms=au&mn=sn-aphx-cbpe&mm=31&pl=24&pcm2cms=yes&ratebypass=yes&mime=audio/mp4&gir=yes&clen=137867408&lmt=1433969746992771&dur=8680.686&mt=1442598087&upn=6S5J3lzt0v0&sver=3&key=dg_yt0&fexp=9407701,9408710,9409069,9409207,9414736,9415365,9415485,9416023,9416126,9416328,9417380,9417690,9417707,9418153,9418200,9418203,9418448,9418999,9419805,9420078,9420348,9420372,9421013,9421288&signature=95A157940A0A9DE0AA55EDC0665D9252DBFC5049.05D413BF0BF6DE4A3EF3725760EA909BBF930975&ip=162.252.188.79&ipbits=0&expire=1442619814&sparams=ip,ipbits,expire,id,itag,source,requiressl,mv,ms,mn,mm,pl,pcm2cms,ratebypass,mime,gir,clen,lmt,dur**

**Note:** I made note of the download url just to compare it with the one that XCDYouTubeKit generates.
XCDYouTubeKit download URL for iTag 140: **https://r4---sn-aphx-cbpe.googlevideo.com/videoplayback?initcwndbps=628750&ipbits=0&sparams=clen%2Cdur%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&fexp=9405994%2C9408710%2C9409069%2C9412754%2C9413139%2C9415030%2C9415365%2C9415435%2C9415485%2C9416023%2C9416126%2C9416309%2C9416729%2C9417707%2C9418153%2C9418200%2C9418393%2C9418448%2C9419058%2C9419266%2C9419444%2C9419774%2C9420348%2C9421013%2C9421144%2C9421295&lmt=1433969746992771&key=yt5&dur=8680.686&source=youtube&signature=91364D50D7D3233EBD588FC4D93427EADF4ED1D8.C207CA4B888FED06E0C1F45DF7B91BE10A657D43&requiressl=yes&mime=audio%2Fmp4&mn=sn-aphx-cbpe&mm=31&expire=1442620234&clen=137867408&pl=24&mv=m&ms=au&upn=PcVTV1dnwG4&mt=1442598582&gir=yes&pcm2cms=yes&sver=3&itag=140&ip=162.252.188.79&id=o-AJBNQf7YXnX83Zz3rNAXx3J_tC75cMGUF-9mIfxqTDrV**

Now, I expected that the download urls to be different, it's just that something with the XCDYouTubeKit URL does not use the maximum bandwidth of my internet connection. I even tested this at various locations on different Wi-Fi networks with different ISPs just to make sure it wasn't just me. I know this might not be a higher priority issue for most folks but, because we're using this class with our project it's very important to us. I would be most grateful if this issue could be fixed :) 
**Note:** The version I tested in this issue was **2.3.1**, on **OS X**.

**Update:**
I uploaded this image to show the speeds:
(2) is from using XCDYouTubeKit
![screen shot 2015-09-18 at 2 06 07 pm](https://cloud.githubusercontent.com/assets/4827301/9967085/7613e97a-5e0e-11e5-8744-5d0025ceb28d.png)

**Comment by 0xced** [comment]
That's an interesting observation, thanks for the detailed report! I will investigate when I get some time.

**Comment by SoneeJohn** [comment]
@0xced Thanks, I really appreciate it!

**Comment by intari** [comment]
results of my small experiment:

url from current version of XCDYouTubeKit is https://r2---sn-xguxaxjvh-vhne.googlevideo.com/videoplayback?key=yt6&mime=audio%2Fmp4&expire=1459851208&upn=BGsfcLMKsyM&fexp=9416126%2C9416891%2C9420452%2C9422596%2C9423662%2C9427902%2C9428399&signature=57F2A55CC337501DB78D5912C5BF558981EBC91A.A2050D53797DE69C5B047CF6BDFB7D0499D9848A&initcwndbps=3605000&sver=3&gir=yes&clen=101469107&dur=6320.494&lmt=1429526400385290&source=youtube&requiressl=yes&sparams=clen%2Cdur%2Cgcr%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&gcr=ru&mn=sn-xguxaxjvh-vhne&itag=140&ip=92.255.176.201&mm=31&ipbits=0&id=o-AIaKY3rPzyq4XhnhKXssmCXTijAVrpg8QuhNHeRJ8_bT&keepalive=yes&pl=20&ms=au&mv=m&mt=1459829380
attempt to load using wget is 

INARI6:~ dkzm$ wget "https://r2---sn-xguxaxjvh-vhne.googlevideo.com/videoplayback?key=yt6&mime=audio%2Fmp4&expire=1459851208&upn=BGsfcLMKsyM&fexp=9416126%2C9416891%2C9420452%2C9422596%2C9423662%2C9427902%2C9428399&signature=57F2A55CC337501DB78D5912C5BF558981EBC91A.A2050D53797DE69C5B047CF6BDFB7D0499D9848A&initcwndbps=3605000&sver=3&gir=yes&clen=101469107&dur=6320.494&lmt=1429526400385290&source=youtube&requiressl=yes&sparams=clen%2Cdur%2Cgcr%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&gcr=ru&mn=sn-xguxaxjvh-vhne&itag=140&ip=92.255.176.201&mm=31&ipbits=0&id=o-AIaKY3rPzyq4XhnhKXssmCXTijAVrpg8QuhNHeRJ8_bT&keepalive=yes&pl=20&ms=au&mv=m&mt=1459829380" -O t3.mp3
--2016-04-05 14:22:15--  https://r2---sn-xguxaxjvh-vhne.googlevideo.com/videoplayback?key=yt6&mime=audio%2Fmp4&expire=1459851208&upn=BGsfcLMKsyM&fexp=9416126%2C9416891%2C9420452%2C9422596%2C9423662%2C9427902%2C9428399&signature=57F2A55CC337501DB78D5912C5BF558981EBC91A.A2050D53797DE69C5B047CF6BDFB7D0499D9848A&initcwndbps=3605000&sver=3&gir=yes&clen=101469107&dur=6320.494&lmt=1429526400385290&source=youtube&requiressl=yes&sparams=clen%2Cdur%2Cgcr%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&gcr=ru&mn=sn-xguxaxjvh-vhne&itag=140&ip=92.255.176.201&mm=31&ipbits=0&id=o-AIaKY3rPzyq4XhnhKXssmCXTijAVrpg8QuhNHeRJ8_bT&keepalive=yes&pl=20&ms=au&mv=m&mt=1459829380
Resolving r2---sn-xguxaxjvh-vhne.googlevideo.com... 109.194.121.77, 2a02:2698:5400:1::d
Connecting to r2---sn-xguxaxjvh-vhne.googlevideo.com|109.194.121.77|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 101469107 (97M) [audio/mp4]
Saving to: 't3.mp3'

t3.mp3                                           1%[>                                                                                                      ]   1.41M  92.0KB/s   eta 17m 42



after adding &ratebypass=yes to the end of URL:

INARI6:~ dkzm$ wget "https://r2---sn-xguxaxjvh-vhne.googlevideo.com/videoplayback?key=yt6&mime=audio%2Fmp4&expire=1459851208&upn=BGsfcLMKsyM&fexp=9416126%2C9416891%2C9420452%2C9422596%2C9423662%2C9427902%2C9428399&signature=57F2A55CC337501DB78D5912C5BF558981EBC91A.A2050D53797DE69C5B047CF6BDFB7D0499D9848A&initcwndbps=3605000&sver=3&gir=yes&clen=101469107&dur=6320.494&lmt=1429526400385290&source=youtube&requiressl=yes&sparams=clen%2Cdur%2Cgcr%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&gcr=ru&mn=sn-xguxaxjvh-vhne&itag=140&ip=92.255.176.201&mm=31&ipbits=0&id=o-AIaKY3rPzyq4XhnhKXssmCXTijAVrpg8QuhNHeRJ8_bT&keepalive=yes&pl=20&ms=au&mv=m&mt=1459829380&ratebypass=yes" -O t3.mp3
--2016-04-05 14:22:41--  https://r2---sn-xguxaxjvh-vhne.googlevideo.com/videoplayback?key=yt6&mime=audio%2Fmp4&expire=1459851208&upn=BGsfcLMKsyM&fexp=9416126%2C9416891%2C9420452%2C9422596%2C9423662%2C9427902%2C9428399&signature=57F2A55CC337501DB78D5912C5BF558981EBC91A.A2050D53797DE69C5B047CF6BDFB7D0499D9848A&initcwndbps=3605000&sver=3&gir=yes&clen=101469107&dur=6320.494&lmt=1429526400385290&source=youtube&requiressl=yes&sparams=clen%2Cdur%2Cgcr%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&gcr=ru&mn=sn-xguxaxjvh-vhne&itag=140&ip=92.255.176.201&mm=31&ipbits=0&id=o-AIaKY3rPzyq4XhnhKXssmCXTijAVrpg8QuhNHeRJ8_bT&keepalive=yes&pl=20&ms=au&mv=m&mt=1459829380&ratebypass=yes
Resolving r2---sn-xguxaxjvh-vhne.googlevideo.com... 109.194.121.77, 2a02:2698:5400:1::d
Connecting to r2---sn-xguxaxjvh-vhne.googlevideo.com|109.194.121.77|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 101469107 (97M) [audio/mp4]
Saving to: 't3.mp3'

t3.mp3                                          13%[============>                                                                                          ]  13.07M  8.86MB/s             ^C

**Comment by SoneeJohn** [comment]
@intari Thanks. I implemented this in my project and I noticed a significant improvement in download speed. I would like to see what @0xced thinks about this solution.

**Comment by 0xced** [comment]
This issue will be fixed in the next release. Thanks for your contributions.
