### ISSUE TITLE
tvOS and VEVO videos

### ISSUE THREAD

**Issue by ziopiero** [0xced/XCDYouTubeKit#179]
Hi,
I have this issue, I tried to remove MPMoviePlayerViewController  in order to use XCDYouTubeVideo  to stream URL video in tvOS.
But some videos (VEVO specially) are restricts  and can't be played.
The same code works fine in iOS9.
Basically, for  some videos  iin iOS9 I can play it , in tvOS no.
 Any idea how to fix it ?

**Comment by 0xced** [comment]
Do you have a specific example of a VEVO video that does’t play in tvOS? I can play all videos in the playlist [VEVO - Best New Songs Playlist | 2015](https://www.youtube.com/playlist?list=PLvFYFNbi-IBFeP5ALr50hoOmKiYRMvzUq) using the [feature/tvOS](https://github.com/0xced/XCDYouTubeKit/tree/feature/tvOS) branch.

**Comment by ziopiero** [comment]
Hi,
I apologize for that, was a mistake in my code. 
I fixed it.
Thank you again for your library

**Comment by 0xced** [comment]
Great to hear you found a solution!
