### ISSUE TITLE
Support tvOS

### ISSUE THREAD

**Issue by MugunthKumar** [0xced/XCDYouTubeKit#182]
Replace NSURLConnection with NSURLSession
Replace unavailable APIs in tvOS with equivalent ones

**Comment by nickv2002** [comment]
+1
Considering there's not any legitimate way to play YouTube videos on tvOS this would be fantastic.

**Comment by 0xced** [comment]
I’m working on it in the [feature/tvOS](https://github.com/0xced/XCDYouTubeKit/tree/feature/tvOS) branch. I hope to release version 2.4.0 in a few weeks.

**Comment by nokai** [comment]
2015-11-06 [XCDYouTubeKit] JavaScript exception: TypeError: undefined is not an object
2015-11-06 [XCDYouTubeKit] Video operation finished with error: No se ha podido completar la operación. (Error de XCDYouTubeVideoErrorDomain -2.)
Domain: XCDYouTubeVideoErrorDomain
Code: -2
User Info: {
NSURL = "https://www.youtube.com/get_video_info?el=detailpage&hl=es&ps=default&video_id=WBfegRcgb80";
}

**Comment by 0xced** [comment]
I just released version 2.4.0 with tvOS support. 🌟

**Comment by nickv2002** [comment]
Awesome thanks!

Any documentation of how to use it on tvOS?  I assume it mostly works the same as iOS but I'm hoping to use it within TVML/TVJS.  Just a basic example is all I'm looking for…

**Comment by 0xced** [comment]
Yes, it’s the same as on iOS. Please have a look at the [tvOS demo](https://github.com/0xced/XCDYouTubeKit/blob/1d784c24cc6d6dd0567fec019ed29bbfd1386e89/XCDYouTubeKit%20Demo/tvOS%20Demo/PlaylistCollectionViewController.m#L70-L86) for some sample code.

**Comment by nickv2002** [comment]
Thanks again @0xced I've got your demo code working, but what I'd really like to do is present a YouTube video from TVJS (I've got the rest of my interface/app working that way already).

I'm working through the suggestions on this [Apple dev thread](https://forums.developer.apple.com/message/60358#60358) but it's a bit confusing connecting your Objective-C code with JS and the Swift demo code there.  If anyone has suggestions or examples of how they got things to work together that would be awesome.

**Comment by axello** [comment]
Pulled commit 1d784c2 'release/2.4.1' and there was an issue with a class from the gtm-http-fetcher pod complaining there was no such thing as a UIWebview on tvOS. Which is correct and annoying in a network pod. I made it to compile and work by disabling the "GTMHTTPFetcherLoggingWebViewController.m" from the gtm-http-fetcher target.

**Comment by nokai** [comment]
Me too error

**Comment by 0xced** [comment]
@axello @nokai Did you run `pod install` or `pod update`? Because I already removed GTMHTTPFetcherLogViewController.m in 9954aab7b3cda31ed2e45a2dc31416eab78eeec0 to avoid this compilation error.

**Comment by nokai** [comment]
pod install

**Comment by 0xced** [comment]
Why did you run `pod install`? The demo app has the `Pods` directory under source control on purpose: so that you don’t need to run `pod install` and risk to break the project. 😉

**Comment by nokai** [comment]
Mmmm, ups.. Thanks & Sorry

**Comment by nickv2002** [comment]
For those who would like to use XCDYouTubeKit with TVML/TVJS, I worked out a solution (in this Gist)[https://gist.github.com/nickv2002/b7bb28cdccc000bdb910].

@0xced you're welcome to copy that code and integrate it into a sample or documentation for the project.
