### ISSUE TITLE
Is there any way to seek video programmatically in XCDYouTubeKit?

### ISSUE THREAD

**Issue by Hardenn** [0xced/XCDYouTubeKit#185]

**Comment by 0xced** [comment]
`XCDYouTubeVideoPlayerViewController` is a subclass of `MPMoviePlayerViewController` which has a `moviePlayer` property conforming to the [`MPMediaPlayback`](https://developer.apple.com/library/ios/documentation/MediaPlayer/Reference/MPMediaPlayback_protocol/) protocol.

**Comment by Hardenn** [comment]
Thanks a lot for fast reply.
