### ISSUE TITLE
Can't play youtube video on iOS (XCDYouTubeVideoErrorDomain error (-2))

### ISSUE THREAD

**Issue by simplepins** [0xced/XCDYouTubeKit#187]
Hi!

Can't play some youtube videos. For example "EdeVaT-zZt4" works, "MefyRaA2HJs" - no. And getting the error with message: XCDYouTubeVideoErrorDomain error (-2).

iOS 9.0.2

Thanks.

**Comment by namikkaya** [comment]
update version => 2.3.2

**Comment by simplepins** [comment]
It works! Thank you.
