### ISSUE TITLE
Did anybody manage to get an app with this library in the AppStore?

### ISSUE THREAD

**Issue by MoridinBG** [0xced/XCDYouTubeKit#188]
I know, that using the library is kind of "On your own risk" thing, but I wonder what have been the experience of other people with using the library in App Store apps?

I just had a series of weird rejections for an app that I can't really figure if are caused by using this library.
Plenty of apps already on the store either use it or something very similar.

**Comment by tommybananas** [comment]
Out of curiosity, what were your rejection reasons? I'm in the queue right now with my fingers crossed. 

I also noticed that there are apps on the store that break terms of service, like SnapChat uploaders, etc, so I'm hoping this not be the case.

**Comment by twobitlabs** [comment]
Yes, @MoridinBG, we have an app in the app store that has been using this library for months.

**Comment by yoeriboven** [comment]
@tommybananas Did it get approved?

**Comment by hodalgun** [comment]
my app approved in app store
 app link: https://geo.itunes.apple.com/us/app/wow-music/id879911997?mt=8

**Comment by cannyboy** [comment]
app approved in last week with this library

**Comment by 0xced** [comment]
So I guess we can close this issue. 😀

**Comment by MoridinBG** [comment]
Nice to clarify this.
In my case it turned out that the client had put 'download' in the keywords for whatever reason. The rejection reasons turned up to be "Misleading keywords" followed by "Downloading copyrighted content from 3rd parties without their permission" maybe 6 hours later. No downloading whatsoever in the app. I load the url in an AVPlayer and hit play()
