### ISSUE TITLE
why does it play with no audio ?

### ISSUE THREAD

**Issue by codepython** [0xced/XCDYouTubeKit#189]
it just has video.

**Comment by tommybananas** [comment]
This is wrong

**Comment by tommybananas** [comment]
That is not true.

**Comment by codepython** [comment]
The case is when playing on mac os ,not IOS .

**Comment by 0xced** [comment]
I can hear audio very well both on iOS and on OS X. Also, please have a look at the [contributing guidelines](https://github.com/0xced/XCDYouTubeKit/blob/2.3.2/CONTRIBUTING.md) to learn how to file a good bug report.
