### ISSUE TITLE
Deprecated methods on iOS 9

### ISSUE THREAD

**Issue by yoeriboven** [0xced/XCDYouTubeKit#190]
Some methods and classes are deprecated on iOS 9: MPMoviePlayerViewController, NSURLConnection and some encryption methods.
![schermafbeelding 2015-11-02 om 17 31 29](https://cloud.githubusercontent.com/assets/4047804/10887521/cbe5651c-8187-11e5-8526-8906a056732a.png)

**Comment by 0xced** [comment]
This has already been taken care of in c0df2c86ed0bbd9cd187b633f8f4246c78958e1d and b35f73ba55485ffe012cecaea2afa35d07b573ca. I hope to release version 2.4.0 in a few weeks.
