### ISSUE TITLE
Vevo type error while getting stream.

### ISSUE THREAD

**Issue by lacyleo** [0xced/XCDYouTubeKit#194]
Video id:YQHsXMglC9A
Here's log: 
User Info: {
    NSLocalizedDescription = "This video contains content from VEVO. It is restricted from playback on certain sites. Watch on YouTube";
    NSURL = "https://www.youtube.com/get_video_info?el=embedded&hl=en&ps=default&video_id=YQHsXMglC9A";
}

**Comment by abingeorgev** [comment]
Same here. It was playing yesterday. But today, its not working.

**Comment by juliorimo** [comment]
+1

**Comment by 0xced** [comment]
This issue is actually a duplicate of #193.
