### ISSUE TITLE
Video plays without sound

### ISSUE THREAD

**Issue by YoavJivi** [0xced/XCDYouTubeKit#195]
(iOS) Some of my users are complaining about playing video without sounds (all of the videos).
I've managed to get my hands on one of the devices and other apps play video with sound. Could this be an issue with the player?

Yoav

**Comment by FaridHaddad** [comment]
just add this 

[[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryPlayback error:nil];

in your PlayerviewController viewDidLoad and it will work

-Farid

**Comment by 0xced** [comment]
As @FaridHaddad said, the audio session configuration must be handled outside of XCDYouTubeKit.

**Comment by YoavJivi** [comment]
Great thanks

**Comment by tulurira** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

tulurira3@naver.com 님께 보내신 메일 <Re: [XCDYouTubeKit] Video plays without sound (#195)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------
