### ISSUE TITLE
youtube age restriction problem

### ISSUE THREAD

**Issue by codaman** [0xced/XCDYouTubeKit#197]
video id = B3eAMGXFw1o this video returns age restriction problem and also many of them

**Comment by arno608rw** [comment]
![screen shot 2558-11-10 at 22 20 27](https://cloud.githubusercontent.com/assets/3774145/11066114/619c991e-87f9-11e5-8476-ed09f4ddfb3d.png)

**Comment by codaman** [comment]
also youtube-dl gets this error and fixed

**Comment by 0xced** [comment]
This issue is actually a duplicate of #193.
