### ISSUE TITLE
Compiling errors

### ISSUE THREAD

**Issue by sajsanghvi** [0xced/XCDYouTubeKit#203]
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_JSValue", referenced from:
      objc-class-ref in libXCDYouTubeKit.a(XCDYouTubePlayerScript.o)
  "_OBJC_CLASS_$_JSContext", referenced from:
      objc-class-ref in libXCDYouTubeKit.a(XCDYouTubePlayerScript.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

When compiling. Any ideas?

**Comment by 0xced** [comment]
You have to add the JavaScriptCore framework in the *Link Binary With Libraries* build phase or enable the *Link Frameworks Automatically* (CLANG_MODULES_AUTOLINK) build setting.
