### ISSUE TITLE
Need to get XCDYouTubeVideo Only !!

### ISSUE THREAD

**Issue by FaridHaddad** [0xced/XCDYouTubeKit#206]
Hello,

I need to use this library only to get the XCDYouTubeVideo object and not use the XCDYouTubeVideoPlayerViewController ..

How can i achieve this ?? please i really need help

**Comment by 0xced** [comment]
How about [reading the documentation](https://github.com/0xced/XCDYouTubeKit/tree/2.3.3#ios-and-os-x)? ;-)
