### ISSUE TITLE
MPMoviePlayerControllerNew has wrong activation state

### ISSUE THREAD

**Issue by erich852** [0xced/XCDYouTubeKit#207]
Hello! Since the last update (2.3.3) I am facing a issue with XCDYouTubeVideoPlayerViewController. When i init with videoIdentifier at first, works fine. But when i change the video in my table view and init again with the identifier im getting this exception:

Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'movie player <MPMoviePlayerControllerNew: 0x14f41e490> has wrong activation state (1)'

When the prepareToPlay() goes.
In the previous version its working fine for me. Anyone can help me with this?
Thanks for the update for VEVO videos by the way.

sorry. I already fix. Thanks again for the update =D

**Comment by oososo** [comment]
Could you tell us how you fix that?
