### ISSUE TITLE
Vevo / API regex updates

### ISSUE THREAD

**Issue by cannyboy** [0xced/XCDYouTubeKit#208]
Changes to Vevo videos always seem to require me to update the library, and therefore update my app (my app often has Youtube music videos). Are the changes in the Youtube API formats predicable enough to allow me to store a regex string on my server, which I can test against if there is a problem with the compiled version of the library?

**Comment by tulurira** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

tulurira3@naver.com 님께 보내신 메일 <[XCDYouTubeKit] Vevo / API regex updates (#208)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by 0xced** [comment]
This is something I’m thinking about. Changing a regex or some configurable string is not always enough but could work in some cases. This feature request is actually already tracked in #199.

**Comment by cannyboy** [comment]
If not a regex string, then maybe a code snippet in php, ruby etc, which can be run on the server-side as a fallback.
