### ISSUE TITLE
Out of Sync Videos

### ISSUE THREAD

**Issue by SoneeJohn** [0xced/XCDYouTubeKit#212]
1. With the provided XCDYouTubeKit Demo app
2. Using XCDYouTubeKit 2.3.3 and OS X SDK 10.11
3. Running Macbook Pro (Retina) on OS X 10.11.1
4. In the demo app, I entered the video identifier ` NvwRIr5MZuk` and pressed the enter key.
5. I expected the video to play normally.
6. Instead, the player the video was out of sync. In this case the total video time that the player reported was 4:34. However, on YouTube this is reported as 4:17. Also, to really see what I am reporting one will have to view the video on YouTube and then using the demo app. 
Link: https://www.youtube.com/watch?v=NvwRIr5MZuk

Screenshots

Using the Player
<img width="880" alt="screen shot 2015-11-19 at 4 27 19 pm" src="https://cloud.githubusercontent.com/assets/4827301/11283605/e9964660-8edb-11e5-9123-f70d71f6824c.png">

On YouTube
<img width="912" alt="screen shot 2015-11-19 at 4 37 29 pm 1" src="https://cloud.githubusercontent.com/assets/4827301/11283624/fea267a0-8edb-11e5-803c-1b4b3c854bae.png">

**Comment by 0xced** [comment]
Even the official YouTube API says the video is 4:34.

    $ curl -s "https://www.googleapis.com/youtube/v3/videos?id=NvwRIr5MZuk&part=contentDetails&key=YOUTUBE_API_KEY" | jq ".items[0].contentDetails.duration"
    "PT4M34S"

I’m closing the issue here since it really looks like a YouTube problem.

**Comment by SoneeJohn** [comment]
@0xced Okay, thanks for the info.
