### ISSUE TITLE
Framework does not contain CFBundleVersion

### ISSUE THREAD

**Issue by calebd** [0xced/XCDYouTubeKit#214]
Framework does not pass iTunes Connect validation since it does not contain a CFBundleVersion.

**Comment by 0xced** [comment]
Does it still have to match the app’s bundle version or did Apple fix this nonsensical requirement?

**Comment by calebd** [comment]
It does not have to match.

**Comment by 0xced** [comment]
I’m gonna release version 2.4.1 tomorrow with the `CFBundleVersion` key.
