### ISSUE TITLE
This video contains content from SME, who has blocked it on copyright grounds

### ISSUE THREAD

**Issue by Quapper** [0xced/XCDYouTubeKit#215]
Hey, most videos work great now i.e Vevo etc but I am still getting an issue with a few such as this one. Any suggestions? Keep up the great work :)

Using 2.4.1:
VideoID: L03JVPaZpyc

User Info: {
    NSLocalizedDescription = "This video contains content from SME, who has blocked it on copyright grounds.";
    NSURL = "https://www.youtube.com/get_video_info?eurl=https://youtube.googleapis.com/v/L03JVPaZpyc&hl=en&sts=16758&video_id=L03JVPaZpyc";
}

**Comment by 0xced** [comment]
Can you watch this video on YouTube?

**Comment by Quapper** [comment]
Hmm, I just checked and no. It appears that it has been removed. It was from a stored playlist I had. Thanks and apologies.

https://www.youtube.com/watch?v=L03JVPaZpyc
