### ISSUE TITLE
**Crash** [XCDYouTubeVideoPlayerViewController presentInView:] - Attempted to dereference garbage pointer 0x90 

### ISSUE THREAD

**Issue by YoavJivi** [0xced/XCDYouTubeKit#217]
Keep getting this crash from my users.
I can send crashLog if needed

**Comment by 0xced** [comment]
As stated in the [guidelines for contributing](https://github.com/0xced/XCDYouTubeKit/blob/1d784c24cc6d6dd0567fec019ed29bbfd1386e89/CONTRIBUTING.md#submitting-issues):
> If you encounter a crash, provide a stack trace. At the time of the crash, just type the `bt all` command in the (lldb) command prompt. If you got a crash report from HockeyApp or Crashlytics for example, include the stack trace too, preferably in textual form instead of a screenshot for easier searching.

So yes, please provide the crash log and also your code which is calling the `presentInView:` method.

**Comment by YoavJivi** [comment]
I 
This is the stackTrack:
[PDF.pdf](https://github.com/0xced/XCDYouTubeKit/files/57785/PDF.pdf)

And this is the code when using this method:
    if (!self.videoPlayerViewController) {
        self.videoPlayerViewController = [[XCDYouTubeVideoPlayerViewController alloc] initWithVideoIdentifier:self.ytVideoId];
        [self.videoPlayerViewController presentInView:self.videoContainer];
    }

**Comment by YoavJivi** [comment]
This is the stack trace:
[PDF.pdf](https://github.com/0xced/XCDYouTubeKit/files/57861/PDF.pdf)

And this is the code:
    if (!self.videoPlayerViewController) {
        self.videoPlayerViewController = [[XCDYouTubeVideoPlayerViewController alloc] initWithVideoIdentifier:self.ytVideoId];
        [self.videoPlayerViewController presentInView:self.videoContainer];
    }

**Comment by 0xced** [comment]
Can you please upload the *full* crash log as *text* format?

**Comment by YoavJivi** [comment]
Sure
[Untitled.zip](https://github.com/0xced/XCDYouTubeKit/files/58061/Untitled.zip)

**Comment by 0xced** [comment]
This is not the *full* crash log. The *full* crash log includes other useful information as described in [Understanding and Analyzing iOS Application Crash Reports (TN2151)][1].

  [1]: https://developer.apple.com/library/ios/technotes/tn2151/_index.html

**Comment by YoavJivi** [comment]
Sry forgot the rest, here you go

[Untitled.zip](https://github.com/0xced/XCDYouTubeKit/files/58085/Untitled.zip)

**Comment by SepiaApps** [comment]
I'm also seeing the same crash from our users. Do you have any clues on the source of the crash yet?

**Comment by nahum365** [comment]
I'm seeing this crash as well. Any updates on this? Thank you
