### ISSUE TITLE
Crashed on iOS 9 with XCode 7.0

### ISSUE THREAD

**Issue by salmanvs** [0xced/XCDYouTubeKit#218]
Here the Fabric log of the crash -

Fatal Exception: NSInvalidArgumentException
*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]

**Comment by 0xced** [comment]
Could you please provide the full crash log? There is not enough information for me to help you.

**Comment by salmanvs** [comment]
Hi,


Here is the code and logs screen shots.



-(void)presentMPMoviePlayerForCurrentToken:(NSString *)token

{

//token is the YouTube ID

-(void)presentMPMoviePlayerForCurrentToken:(NSString *)token

{


    AppDelegate *delegate = (AppDelegate *) [[UIApplication
sharedApplication] delegate];

    delegate.flagOrientationLandscape = YES; //Used to switch from portrait
mode to land scape





    XCDYouTubeVideoPlayerViewController *videoPlayerViewController =

    [[XCDYouTubeVideoPlayerViewController alloc] initWithVideoIdentifier
:token];

     [self presentMoviePlayerViewControllerAnimated:
videoPlayerViewController];

    delegate.flagOrientationLandscape = NO; //Used to switch from land
scape to portrait mode

}







​



Thanks & Regards
Salman

**Comment by 0xced** [comment]
There’s only a snippet of code, I see no logs and no screenshots. I think you should upload them on GitHub instead of by e-mail.

**Comment by salmanvs** [comment]
Hi,

Please find the attached screen shots.



Thanks

**Comment by 0xced** [comment]
There are still no screenshots, please go to https://github.com/0xced/XCDYouTubeKit/issues/218 with a web browser and upload the logs and screenshots there. **Do not reply by e-mail with attachments**, it doesn’t work.

**Comment by salmanvs** [comment]
These are the fabric logs screen shots-

![log_1](https://cloud.githubusercontent.com/assets/14212202/11722732/65624450-9f90-11e5-963a-e909097c8d56.png)
![log_2](https://cloud.githubusercontent.com/assets/14212202/11722731/655e382e-9f90-11e5-9c12-d727ea34262e.png)

**Comment by 0xced** [comment]
Can you please click on the `</> raw` button and upload the *full* textual crash report? There are probably more information that can help me to diagnose this issue.

**Comment by 0xced** [comment]
Maybe the full crash log is not needed. I see that you are trying to present the video player in landscape. Please delete all your code using the `flagOrientationLandscape` boolean flag and use that instead:

```objc
@interface MyYouTubeVideoPlayerViewController : XCDYouTubeVideoPlayerViewController
@end

@implementation MyYouTubeVideoPlayerViewController

- (UIInterfaceOrientation) preferredInterfaceOrientationForPresentation
{
	return UIInterfaceOrientationLandscapeLeft;
}

@end
```

Then, instead of allocating a `XCDYouTubeVideoPlayerViewController` object, you allocate a `MyYouTubeVideoPlayerViewController`. The video will start in landscape instead of portrait.

**Comment by salmanvs** [comment]
@Oxced, I did the same but app still crashing.

Thanks

**Comment by 0xced** [comment]
Then I suggest you to follow this advice from the [guidelines for contributing][1]:

> If your problem can not be demonstrated with the demo app, please provide a test app yourself. A link to a zipped Xcode project is fine but a GitHub repository with your test app is even better. You don’t need to provide your whole app. **Create a test app with the very minimum code required in order to exhibit your problem. During the process of reducing your test app to the minimum, you are very likely to find the solution to your problem by yourself, try it!**

  [1]: https://github.com/0xced/XCDYouTubeKit/blob/63694fd83cc03597365726596a49b095a0fb01fa/CONTRIBUTING.md#submitting-issues

**Comment by salmanvs** [comment]
Hi,

Ap per you suggestion i created a test app it's working fine on iOS 9 with Xcode 7.0.
I figured out, issue was because of controllers hierarchy.


I am very thankful for your quick replies.

**Comment by 0xced** [comment]
Glad you solved it!
