### ISSUE TITLE
XCode Warning: XCDYouTubeLogger.o was built for newer iOS version (8.0) than being linked (7.0)

### ISSUE THREAD

**Issue by yoasha** [0xced/XCDYouTubeKit#220]
Hi,
I get the following warning after updating to the latest source files of XCDYouTubeKit:
"XCDYouTubeLogger.o was built for newer iOS version (8.0) than being linked (7.0)"

I noticed that iOS deployment target in the project file was recently changed from 7.0 to 8.0, and since my project target is 7.0, it explains the reason for this warning.

Any reason why iOS deployment target was changed? Is iOS 7.0 no longer supported by XCDYouTubeKit library?

Thank you for this great library and for your kind support.

**Comment by 0xced** [comment]
I just released version 2.4.2 which restore iOS 7.0 compatibility, sorry for the trouble.

**Comment by webdevotion** [comment]
I recently updated XCDYouTubeKit and when I try to `Fastlane` my builds I get:

```
Return status of iTunes Transporter was 1: ERROR ITMS-90362: 
"Invalid Info.plist value. The value for the key 'MinimumOSVersion' in bundle
MyAPP.app/Frameworks/XCDYouTubeKit.framework is invalid. The minimum value is 8.0"
```

I use `Carthage`.

**Comment by 0xced** [comment]
@webdevotion Please open a [new issue](https://github.com/0xced/XCDYouTubeKit/issues/new), I don’t think the iTunes issue it related to @yoasha's issue.
