### ISSUE TITLE
Player controls stay after setting controlStyle = MPMovieControlStyleNone

### ISSUE THREAD

**Issue by YoavJivi** [0xced/XCDYouTubeKit#221]
Hey,

For some reason the player controls keep appearing even after i set the property to 'MPMovieControlStyleNone'.

I call 
'self.videoPlayerViewController.moviePlayer.controlStyle = MPMovieControlStyleNone;'
right after '[self.videoPlayerViewController presentInView:self.videoContainer];'.

Thanks

**Comment by ggdiez** [comment]
Sorry but, where is this code?, I'm using 2.5.2 version with CocoaPods and the presentInView with ControlStyle are not in the XCDYouTubeVideoPlayerViewController class.

**Comment by 0xced** [comment]
Pull request #222 was not merged. The presentInView method will disappear in XCDYouTubeKit 3 in favor of view controller containment.

If you need it now I suggest you to subclass XCDYouTubeVideoPlayerViewController and add it in your own code.

**Comment by ggdiez** [comment]
Thank you!!!

When is expected that XCDYouTubeKit 3 is released?

**Comment by kazekim** [comment]
I still can't remove control out. I extends class XCDYouTubeVideoPlayerViewController with name UncontrollableYouTubeVideoPlayerViewController and use  this code 

#import "UncontrollableYouTubeVideoPlayerViewController.h"

@interface UncontrollableYouTubeVideoPlayerViewController ()
@end

@implementation UncontrollableYouTubeVideoPlayerViewController

- (void) viewWillAppear:(BOOL)animated
{
    [super viewWillAppear:animated];
    self.moviePlayer.controlStyle = MPMovieControlStyleNone;
    
}

-(void)presentInView:(UIView *)view{
    

    [super presentInView:view];
    self.moviePlayer.controlStyle = MPMovieControlStyleNone;

}

@end

What's wrong with my code?

Thanks

**Comment by ggdiez** [comment]
@kazekim 

You have to rewrite the presentInView method and in that modify the controlStyle property. 

Something like this: https://github.com/0xced/XCDYouTubeKit/pull/222/files

**Comment by BharatAgarSoftTech** [comment]
XCD should remove below code from "XCDYouTubeVideoPlayerViewController.h"

self.moviePlayer.controlStyle = MPMovieControlStyleEmbedded;

I can set control style from my code, because of the above code I am not able to set control style from my code.

i already try YouTubeXCD.moviePlayer.controlStyle = MPMovieControlStyleNone
but its not working, but after removing one line of code from "XCDYouTubeVideoPlayerViewController.h" everthing is working fine.

Thanks.

**Comment by mehdok** [comment]
I extended `XCDYouTubeVideoPlayerViewController` and override `- (void)presentInView:(UIView *)view`, The result is something like this, and it works:

`VideoPlayer.h`

```
#import <Foundation/Foundation.h>
#import <XCDYouTubeKit/XCDYouTubeKit.h>
#import <objc/runtime.h>

NS_ASSUME_NONNULL_BEGIN

@interface VideoPlayer : XCDYouTubeVideoPlayerViewController
    @property (nonatomic, assign, getter = isEmbedded) BOOL embedded;
@end

NS_ASSUME_NONNULL_END

```

`VideoPlayer.m`

```
#import "VideoPlayer.h"

@implementation VideoPlayer

@synthesize embedded = _embedded;

// we must override this methods to prevent showing controllers
- (void)presentInView:(UIView *)view {
    static const void * const XCDYouTubeVideoPlayerViewControllerKey = &XCDYouTubeVideoPlayerViewControllerKey;
    
    _embedded = YES;
    
    self.moviePlayer.controlStyle = MPMovieControlStyleNone;
    self.moviePlayer.view.frame = CGRectMake(0, 0, view.bounds.size.width, view.bounds.size.height);
    self.moviePlayer.view.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
    if (![view.subviews containsObject:self.moviePlayer.view])
    [view addSubview:self.moviePlayer.view];
    objc_setAssociatedObject(view, XCDYouTubeVideoPlayerViewControllerKey, self, OBJC_ASSOCIATION_RETAIN_NONATOMIC);
}

@end
```
