### ISSUE TITLE
MinimumOSVersion is invalid. The minimum value is 8.0.

### ISSUE THREAD

**Issue by webdevotion** [0xced/XCDYouTubeKit#223]
I recently updated `XCDYouTubeKit` and when I try to `Fastlane` my builds I get:

Return status of iTunes Transporter was 
```
1: ERROR ITMS-90362: 
"Invalid Info.plist value. The value for the key 'MinimumOSVersion' in bundle
MyAPP.app/Frameworks/XCDYouTubeKit.framework is invalid. The minimum value is 8.0"
```

I use `Carthage`. Locking version to `2.4.1` makes my builds pass iTunes Transporter tests again.

**Comment by 0xced** [comment]
I just released version 2.4.3 which should fix this issue. Thanks for your report!
