### ISSUE TITLE
On some devices there is no sound when using XCDYouTubeVideoPlayerViewController

### ISSUE THREAD

**Issue by yoasha** [0xced/XCDYouTubeKit#225]
Hi,
Some of my customers don't have sound when XCDYouTubeVideoPlayerViewController is displayed, just as described on issue #195. The answer for this issue was as follow:
> just add this
> [[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryPlayback error:nil];
> in your PlayerviewController viewDidLoad and it will work
> -Farid

However, I found no explanation about the reason of this issue when I reviewed issue #195. Can you please provide more info of how comes that the same code in the same app has different behaviors on various devices? What parameter (in the app or device) exactly is affecting this behavior?

Another question, I am currently using XCDYouTubeVideoPlayerViewController "as is" to show YouTube videos. Do I have to subclass it with my own custom class in order to override viewDidLoad as explained above, and add the code that should fix this issue?

Thanks a lot for your help!

**Comment by 0xced** [comment]
> However, I found no explanation about the reason of this issue when I reviewed issue #195. Can you please provide more info of how comes that the same code in the same app has different behaviors on various devices? What parameter (in the app or device) exactly is affecting this behavior?

Please read about audio sessions in the [Audio Session Programming Guide][1]. If you do nothing, playing a movie with `XCDYouTubeVideoPlayerViewController` (which is a subclass of `MPMoviePlayerViewController`) will observe the Ring/Silent switch. This is probably why you observed different behaviors on various devices: some had the silent switch on and some other had the silent switch off.

> Another question, I am currently using XCDYouTubeVideoPlayerViewController "as is" to show YouTube videos. Do I have to subclass it with my own custom class in order to override viewDidLoad as explained above, and add the code that should fix this issue?

No, you do not need to subclass `XCDYouTubeVideoPlayerViewController`, you can set the audio session category at application startup or just before presenting the YouTube video player view controller for example.

  [1]: https://developer.apple.com/library/ios/documentation/Audio/Conceptual/AudioSessionProgrammingGuide/Introduction/Introduction.html

**Comment by yoasha** [comment]
Thank you so much for this clear answer. The behavior and the solution are crystal clear now.
