### ISSUE TITLE
Can't find link of download

### ISSUE THREAD

**Issue by swierpa** [0xced/XCDYouTubeKit#226]
Hi. First, thanks you for your fantastic software.

I have a issue finding some download links. For some videos (such as this one https://www.youtube.com/watch?v=F_6IjeprfEs) I'm not able to get the download URL, the method ok XCDYouTube only returns the link of the .flv file. Can you please help me?

Thanks you

**Comment by nickv2002** [comment]
If you just want to download files, what about using [youtube-dl](https://rg3.github.io/youtube-dl/) on your computer?  I was able get a 640 x 480 MP4 video from the link you listed using just `youtube-dl https://www.youtube.com/watch?v=F_6IjeprfEs`

**Comment by swierpa** [comment]
Because I want to do it in a iOS app.

**Comment by 0xced** [comment]
What have you tried? This gives a valid mp4 URL with XCDYouTubeKit 2.5.0:

```objc
[[XCDYouTubeClient defaultClient] getVideoWithIdentifier:@"F_6IjeprfEs" completionHandler:^(XCDYouTubeVideo * _Nullable video, NSError * _Nullable error) {
	NSLog(@"Video: %@\n%@", video.title, video.streamURLs[@(XCDYouTubeVideoQualityMedium360)]);
}];
```

**Comment by swierpa** [comment]
Sorry my mistake. That video works. But for example if you try this one: https://www.youtube.com/watch?v=L-dfUvtkBtw won't work. My code is:

XCDYouTubeClient.defaultClient().getVideoWithIdentifier(videoID, completionHandler: {(video: HelperVideo?, error: NSError?) -> Void in
                                        
                    if video != nil {
                        
                        dispatch_async(dispatch_get_main_queue()) {
                            
                            MBProgressHUD.hideAllHUDsForView(self.view, animated: true)
                        }
                        
                        var streamURLs: [NSObject : AnyObject] = video!.streamURLs
                        
                        var listOfVideoQualityAndLink = Dictionary<String, String>()
                        
                        for(var i = 0; i < streamURLs.count; i++) {

                            if(streamURLs[i] != nil) {
                                print("streamURLs[\(i)]: \(streamURLs[i])")
                                let url = streamURLs[i]?.absoluteString
                            }
                        }
                     }
               })

The output of the print function is:
streamURLs[5]: Optional(https://r3---sn-nfpnnjvh-1gis.googlevideo.com/videoplayback?ipbits=0&upn=GvtpjIc3k-8&key=yt6&fexp=9410706%2C9416126%2C9420452%2C9420540%2C9422596%2C9423491%2C9423662%2C9425698%2C9426413%2C9426942%2C9427016&itag=5&dur=175.020&initcwndbps=808750&sver=3&lmt=1445613795639299&sparams=dur%2Cgcr%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&mn=sn-nfpnnjvh-1gis&pl=24&source=youtube&mm=31&requiressl=yes&ip=93.50.241.9&mime=video%2Fx-flv&expire=1452814363&mt=1452792682&ms=au&id=o-AINIqNtiAA2lJaGTYN9QR56oAmXCiC1FHjzSq8Y8ReR-&mv=m&gcr=it&signature=BCD85A59483CCABD5C3F895D665986CDDFD205B2.9F0BDA2560E866B07DB894781511DCF75D60EAC0)

And this is an flv video.

Thanks you!!

**Comment by 0xced** [comment]
The `streamURLs` property is a dictionary, not an array, you can’t iterate it with `i++`. The keys are YouTube [itag values, **as documented**](http://cocoadocs.org/docsets/XCDYouTubeKit/2.5.0/Classes/XCDYouTubeVideo.html#//api/name/streamURLs) and XCDYouTubeKit defines [constants, **as documented**](http://cocoadocs.org/docsets/XCDYouTubeKit/2.5.0/Constants/XCDYouTubeVideoQuality.html) for mp4 files.

You get a FLV file because 5 is the smallest valid itag value and corresponds to the FLV 240p format.

Here is what you probably want instead:
```swift
if let streamURL = (video?.streamURLs[XCDYouTubeVideoQualityHTTPLiveStreaming] ??
                    video?.streamURLs[XCDYouTubeVideoQuality.HD720.rawValue] ??
                    video?.streamURLs[XCDYouTubeVideoQuality.Medium360.rawValue] ??
                    video?.streamURLs[XCDYouTubeVideoQuality.Small240.rawValue]) {
    print("streamURL: \(streamURL)")
}
```

**Comment by swierpa** [comment]
That's ok but tags are simply numbers. So if you do 
     video?.streamURLs[XCDYouTubeVideoQuality.HD720.rawValue]
or 
    video?.streamURLs[22]
it's the same. This means that the for loop should works, therefore if my loop can  find only streamURLs[5] I think this must be the only tag available for that youtube link.

**Comment by 0xced** [comment]
> This means that the for loop should works, therefore if my loop can find only streamURLs[5] I think this must be the only tag available for that youtube link.

No, this will not work because the keys (itags) do not range from `0` to `count - 1`. Here is how you should iterate the streamURLs dictionary:
```swift
for (itag, streamURL) in streamURLs {
    print("\(itag) -> \(streamURL)\n")
}
```

**Comment by swierpa** [comment]
Ok thanks you very much for your help! I'll try this evening and I'll let you know if I'll success. Thanks
