### ISSUE TITLE
Audio keeps playing for a while in the background even after the video has been closed

### ISSUE THREAD

**Issue by Shivam101** [0xced/XCDYouTubeKit#227]
Hello, 

The above happens only in cases when the XCDYouTubeVideoPlayerViewController is closed even before the video has loaded. In this case, on returning the previous screen or navigating the rest of the app, the video keeps loading, plays audio for a couple of seconds and then stops. 

Thanks!

**Comment by 0xced** [comment]
Can you please show me your code?

**Comment by Shivam101** [comment]
Here :

`override func tableView(tableView: UITableView, didSelectRowAtIndexPath indexPath: NSIndexPath) {
        let itemAtIndex:Items? = MyItems[indexPath.row]
        if  let item:Items = itemAtIndex {
            if let videoURL = item.getVideoURL() {
                
                //get the youtube video id from the URL 
                if let videoIdentifier = HCYoutubeParser.youtubeIDFromYoutubeURL(NSURL(string:videoURL)) {
                    //play using the XCD youtube player
                    let videoPlayerViewController:XCDYouTubeVideoPlayerViewController = XCDYouTubeVideoPlayerViewController(videoIdentifier: videoIdentifier)
                    videoPlayerViewController.modalPresentationStyle = UIModalPresentationStyle.FullScreen
                    videoPlayerViewController
                    videoPlayerViewController.moviePlayer.fullscreen = true
                    self.presentMoviePlayerViewControllerAnimated(videoPlayerViewController)
                }
            }
        }
    }`

**Comment by Shivam101** [comment]
@0xced Any thoughts on what might be the issue ?

**Comment by twobitlabs** [comment]
We ran into the same problem... the solution for us was to make the following call before disposing of XCDYouTubeVideoPlayerViewController:

`[self.youTubeController.moviePlayer setContentURL:nil];`

found the solution from this stackoverflow post:

http://stackoverflow.com/a/14336539/428767

**Comment by 0xced** [comment]
Please have a look at [DemoInlineViewController](https://github.com/0xced/XCDYouTubeKit/blob/190b177c77400e5bf700ea9883a3e1ebab351956/XCDYouTubeKit%20Demo/iOS%20Demo/DemoInlineViewController.m#L24-L25) in the demo project. This demonstrates how to explicitly stop the player when you return to the previous screen.
