### ISSUE TITLE
Expose `isAgeRestricted` to `XCDYouTubeVideo` class.

### ISSUE THREAD

**Issue by SoneeJohn** [0xced/XCDYouTubeKit#229]
Hi, is it possible to expose the `isAgeRestricted` property in the `XCDYouTubeVideoWebpage` class to the header file of the `XCDYouTubeVideo` class?

I'm currently, using the Google API Client for Objective-C to check if a video was marked as age restricted by YouTube, but I trying as much as possible from using it.

**Comment by SoneeJohn** [comment]
So, I did some investigating in the `XCDYouTubeOperation` class and it appears that this might not be possible.

**Comment by 0xced** [comment]
That’s because the webpage is only downloaded if needed to get the stream URLs, so indeed I can’t make this information bubble up to `XCDYouTubeVideo` without sacrificing performance.

**Comment by SoneeJohn** [comment]
@0xced Thanks for informing me. I actually forgot to close this issue :-).
