### ISSUE TITLE
Automatically starts up video on load

### ISSUE THREAD

**Issue by killmyrene** [0xced/XCDYouTubeKit#23]
Hi, I came across your video player and every time I present the video it automatically starts up. Is there a way not to do that?

So I made a popup that is presented modally from the root window and inside is a view 'videoView' which contains the youtube video.

```
XCDYouTubeVideoPlayerViewController *videoPlayerViewController = [[XCDYouTubeVideoPlayerViewController alloc] initWithVideoIdentifier:@"eWbvXB85BZc"];
[videoPlayerViewController.view setFrame:videoView.bounds];
[videoView addSubview:videoPlayerViewController.view];
```

![screen shot 2014-03-10 at 4 10 03 pm](https://f.cloud.github.com/assets/3467628/2378588/78ee3536-a890-11e3-9c82-3339089b0f56.png)

**Comment by priyeshmarvi** [comment]
@0xced autoplay doesn't seems to work.. 

`videoPlayerViewController = [[XCDYouTubeVideoPlayerViewController alloc] initWithVideoIdentifier:videoId];
        [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(youtubeVideoFinishedCallback:) name:MPMoviePlayerPlaybackDidFinishNotification object:videoPlayerViewController.moviePlayer];
            [self presentViewController:videoPlayerViewController animated:YES completion:NULL];
            [videoPlayerViewController.moviePlayer play];`
