### ISSUE TITLE
This video has content from UMG, WMG etc... 

### ISSUE THREAD

**Issue by erich852** [0xced/XCDYouTubeKit#231]
Recently i have this error:

with error: This video presents content from WMG. Watch it on youtube.
Domain: XCDYouTubeVideoErrorDomain
Code:   150

I Think that this are caused by an youtube Api change... Anyone know what i can do to bypass this situation? Thanks a lot!

**Comment by Pranoy1c** [comment]
same issue here too. Just started happening this morning onwards for various channels.

**Comment by JotaP** [comment]
Same behavior here :(

**Comment by JotaP** [comment]
Thanks @0xced, that was a quick fix! We owe you!

**Comment by Pranoy1c** [comment]
Thank you !! @0xced is there a donation page where we can help out?

**Comment by erich852** [comment]
@Pranoy1c There is a Donate button bellow the Psy video in the XCDYouTubeKit home screen here in git hub.

**Comment by erich852** [comment]
Thanks a lot @0xced! You are the best! =D

**Comment by sajsanghvi** [comment]
Hey thanks @0xced ! Is there any way to avoid having to upload a new version of our apps to the app store when api changes like this occur?

**Comment by 0xced** [comment]
@sajsanghvi This feature is planned, see #199.

**Comment by touchbee** [comment]
@0xced I'm still seeing this issue with the latest version (2.5.3). I'm using this video identifier: **wTMFpRwuSYg**

"This video contains content from UMG. It is restricted from playback on certain sites or applications. Watch on YouTube";
    NSURL = "https://www.youtube.com/get_video_info?el=embedded&hl=en&ps=default&video_id=wTMFpRwuSYg";

**Comment by appcornerit** [comment]
+1
