### ISSUE TITLE
Play the next video in Swift?

### ISSUE THREAD

**Issue by seenoevo** [0xced/XCDYouTubeKit#235]
How can I play the next video using Swift language?

https://github.com/0xced/XCDYouTubeKit/issues/16

However, it's written in Objective-C.

How can I achieve this in Swift?

**Comment by devilbags** [comment]
First you need to add observer to listen for videoIdentifier changes
```
NSNotificationCenter.defaultCenter().addObserver(self, selector: Selector("changeVideo:"), name: XCDYouTubeVideoPlayerViewControllerDidReceiveVideoNotification, object:nil )
```
Then add a function to play the next video according to the new video identifier you pass to your videoplayerViewController
```
func changeVideo(notification: NSNotification) {
        dispatch_async(dispatch_get_main_queue()) {
            self.videoPlayer.moviePlayer.prepareToPlay()
        }
}
```
Note: the dispatch method is critical, without it you will get weird errors

**Comment by seenoevo** [comment]
Hmm, could you possibly provide a more concrete example in Swift?...I'm fairly near to this?.....Wouldn't I need to add

`XCDYouTubeVideoPlayerViewController( videoIdentifier: videoID )`

somewhere in changeVideo?

**Comment by lucascoria** [comment]
Did you find a solution for this seenoevo? im facing the same problem.

**Comment by mannanr** [comment]
Any solution to this problem  @seenoevo  @devilbags  @0xced  ? i am stucked on same state. can't fired notifications to check whether video state has changed or not. 
Any help in Swift 3.
