### ISSUE TITLE
Airplay not working?

### ISSUE THREAD

**Issue by cannyboy** [0xced/XCDYouTubeKit#236]
I'm playing a video: https://www.youtube.com/watch?v=_u8nrKl7xS4

.. but the AirPlay option is not appearing.

I've got "Audio, AirPlay and Picture-in-Picture" on in Background Modes. 

I've tried using these settings: 
````
player.allowsExternalPlayback = true
player.usesExternalPlaybackWhileExternalScreenIsActive = true
````

But the AirPlay icon still doesn't appear. 

The same video works with AirPlay in the Youtube app.

**Comment by 0xced** [comment]
AirPlay support is outside the scope of XCDYouTubeKit. However, this might help you, from the official [AVPlayerViewController documentation][1]:

> Starting in iOS 9, supported iPad models also provide Picture in Picture playback from a player view controller.

> [...]

> #### Participating with Picture in Picture
To participate with Picture in Picture (PiP), take the following steps in your Xcode project:

> 1. Link on or after iOS 9.0.

> 2. In the Xcode Capabilities view for your project, select Audio and AirPlay in the Background Modes section.

> 3. Configure your audio session with an appropriate category, such as [AVAudioSessionCategoryPlayback][2], If you have not already done so in your app.

> To respond to user interactions with the PiP window, implement the methods of the [AVPlayerViewControllerDelegate][3] protocol.

> Having configured your project to support Picture in Picture, the player view controller then provides a PiP button for the user, along with the other playback controls.

  [1]: https://developer.apple.com/library/ios/documentation/AVFoundation/Reference/AVPlayerViewController_Class/index.html
  [2]: https://developer.apple.com/library/ios/documentation/AVFoundation/Reference/AVAudioSession_ClassReference/index.html#//apple_ref/c/data/AVAudioSessionCategoryPlayback
  [3]: https://developer.apple.com/library/ios/documentation/AVKit/Reference/AVPlayerViewControllerDelegate_Protocol/index.html#//apple_ref/occ/intf/AVPlayerViewControllerDelegate
