### ISSUE TITLE
how can i get stream url?

### ISSUE THREAD

**Issue by davut5** [0xced/XCDYouTubeKit#237]
can i copy  XCDYoutubeKit StreamUrl link  to AVPlayer()????
can i get link of MPMovieContoller?

**Comment by SoneeJohn** [comment]
@davut5 check out the OS X Demo project specifically, [the AppDelegate](https://github.com/0xced/XCDYouTubeKit/blob/master/XCDYouTubeKit%20Demo/OS%20X%20Demo/AppDelegate.m)

**Comment by 0xced** [comment]
Yes, you can. Please take some time to read the documentation and check the existing examples in the demo projects.
