### ISSUE TITLE
How can I add google api / youtube TVOS in a project?

### ISSUE THREAD

**Issue by nokai** [0xced/XCDYouTubeKit#238]
Hello everyone

I'm trying to add to a project TVOS with swift youtube API for later use this XCDYouTubeKit.

But I get this error ..... "Which does not support TVOS"

How can I fix it? ... Has anyone been able to add?

Regards

**Comment by 0xced** [comment]
If you are talking about the Google APIs Client Library for Objective-C, this will be [fixed soon](https://github.com/google/google-api-objectivec-client/pull/185). You workaround this issue in the meantime by pointing the pod to a [specific commit](https://github.com/0xced/XCDYouTubeKit/blob/871233049d9d32f37035e9b7872cbf3b778e53d3/XCDYouTubeKit%20Demo/Podfile#L23-L24).

If you are talking about something else, please be much more specific in your question.
