### ISSUE TITLE
Is there a shortcut to playing a video once the player has been instantiated?

### ISSUE THREAD

**Issue by sajsanghvi** [0xced/XCDYouTubeKit#242]
Is there a way to just replace the video identifier without having to reinitialize the YouTube player? Each time I play a video I'm using this code (below) but I feel like there is some way to make it faster. Thanks

Code:
XCDYOUTUBEPLAYERCONTROLLER = [[XCDYouTubeVideoPlayerViewController alloc] initWithVideoIdentifier:VIDEOID];
[XCDYOUTUBEPLAYERCONTROLLER presentInView:self.playerController.youtubeplayerView];
[XCDYOUTUBEPLAYERCONTROLLER.moviePlayer play];

**Comment by anilappvolution** [comment]
try this code may be help you
XCDYOUTUBEPLAYERCONTROLLER.videoIdentifier = your videoIdentifier

**Comment by 0xced** [comment]
As @anilappvolution said, you can simply set a new `videoIdentifier`. Instead of relying on KVO, you can add on observer on `XCDYouTubeVideoPlayerViewControllerDidReceiveVideoNotification` and call `play` in the notification callback.
