### ISSUE TITLE
Error in XCDYoutubeVideoPlayerViewController in Swift

### ISSUE THREAD

**Issue by JEKos** [0xced/XCDYouTubeKit#244]
Hi,
I'm trying to make a controller when the user goes to this controller, player will be ready to play , when the user press the start button in the player. I added via cocoa pods the library and I add `#import <XCDYouTubeKit/XCDYouTubeKit.h>` in header of my swift project. But when I run it with the below code, I have an Error "Use of undeclared type 'XCDYouTubeVideoPlayerViewController' . Where is the problem??

`var vidplayer : XCDYouTubeVideoPlayerViewController = XCDYoutubeVideoPlayerViewController(videoIdentifier: "6v2L2UGZJAM")
        self.presentMoviePlayerViewControllerAnimated(vidplayer)
        vidplayer.presentInView(uiView)
        vidplayer.moviePlayer.play()`

**Comment by JEKos** [comment]
ok , I resolved it , I needed to add import `import XCDYouTubeKit` at the top of ViewController.swift

**Comment by 0xced** [comment]
Glad you solved it!

**Comment by osalazarMaplander** [comment]
i have the same problema in objective c I import #import <XCDYouTubeKit/XCDYouTubeKit.h>

without problems but i have error here  XCDYouTubeVideoPlayerViewController *videoPlayerViewController
Use of undeclared identifier 'videoPlayerViewController'
Use of undeclared identifier 'XCDYouTubeVideoPlayerViewController'
i dont know hot to resolve
cant you tell me som lead?
i added @import XCDYouTubeKit; and not work
Thanks
