### ISSUE TITLE
Memory leak from objc_setAssociatedObject call

### ISSUE THREAD

**Issue by thuss** [0xced/XCDYouTubeKit#246]
I use [Leak Inspector](https://github.com/twobitlabs/LeakInspector) and noticed that whenever I'd finish playing a YouTube video in our app I'd get a warning that the XCDYouTubePlayerViewController wasn't getting dealloc'd. I traced it back to the objc_setAssociatedObject call which creates strong references to the controller from any view it's presented in and never nils out those references later.

Removing the call fixed the issue for me on my fork:

https://github.com/twobitlabs/XCDYouTubeKit/commit/f72c16204e3ebe186f2de9d341d1f25ef1411e99

however, are there any side effects from removing it? It's not clear to me why we'd set an associated object but never read its value or nil it out later:

`	
objc_setAssociatedObject(view, XCDYouTubeVideoPlayerViewControllerKey, self, OBJC_ASSOCIATION_RETAIN_NONATOMIC);
`

**Comment by 0xced** [comment]
> however, are there any side effects from removing it?

Yes, this is needed because the controller receives and handles notifications. Doing this would not work because the player view controller would be deallocated at the end of the scope:
```objc
- (void) presentVideoWithIdentifier:(NSString *)identifier inView:(UIView *)view
{
	XCDYouTubeVideoPlayerViewController *videoPlayerViewController = [[XCDYouTubeVideoPlayerViewController alloc] initWithVideoIdentifier:identifier];
	[videoPlayerViewController presentInView:view];
}
```

About your leak issue: the controller is released when the view you presented it in is released (that’s how associated objects work). So you should probably check for a retain cycle keeping your controller from being deallocated. Facebook recently released [FBMemoryProfiler](https://github.com/facebook/FBMemoryProfiler) which could help you tracking down this issue.

**Comment by thuss** [comment]
In our case we move the video player between different views (since we implement our own picture in picture within our app) so having a view retain a controller was causing leaks as the parent view could be long lived. We can workaround it by wrapping the player in another UIView and moving that view around though.

We use the following initializer which is probably why removing the associated object didn't cause us any issues:

```
self.youTubeController = [[XCDYouTubeVideoPlayerViewController alloc] initWithVideoIdentifier:videoId];
[self.youTubeController presentInView:parentView];
```

I feel like having a view retain a controller isn't a great pattern but I understand why you do it in the case above. 

Thanks for the great project, it's definitely saved us a ton of time!

**Comment by 0xced** [comment]
> I feel like having a view retain a controller isn't a great pattern but I understand why you do it in the case above.

You are absolutely right, this feels wrong. This will be addressed in version 3 with proper view controller containment. (MPMoviePlayerViewController is terrible at view controller containment)

> Thanks for the great project, it's definitely saved us a ton of time!

[Donations](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=MGEPRSNQFMV3W) are welcome. 😉
