### ISSUE TITLE
How to handle player state (stopped, playing, seekingBack,...)?

### ISSUE THREAD

**Issue by sonysm** [0xced/XCDYouTubeKit#248]
i don't how to handle even player did stopped, or resuming, seeking?
thanks

**Comment by 0xced** [comment]
`XCDYouTubeVideoPlayerViewController` is a subclass of `MPMoviePlayerViewController` which has a `moviePlayer` with plenty of [notifications](https://developer.apple.com/library/ios/documentation/MediaPlayer/Reference/MPMoviePlayerController_Class/index.html#//apple_ref/doc/uid/TP40006953-CH3-DontLinkElementID_4). See also the iOS Demo app [PlayerEventLogger class](https://github.com/0xced/XCDYouTubeKit/blob/138a0be2f021152fd51a65bc2ac92a5b3524954b/XCDYouTubeKit%20Demo/iOS%20Demo/PlayerEventLogger.m) for some sample code.

**Comment by sonysm** [comment]
how to change to next video?
