### ISSUE TITLE
Error with library after new cocoapods version?

### ISSUE THREAD

**Issue by JEKos** [0xced/XCDYouTubeKit#250]
Hi,
After I updated cocoapods to version 1.0.0, a have this problem below
![img](https://cloud.githubusercontent.com/assets/11445928/15424759/0f831ef2-1e8d-11e6-8594-6afa0017c2b2.png)

I tried to change <> to "" but other problem appears

**Comment by 0xced** [comment]
I suggest you to [file an issue on the CocoaPods](https://github.com/CocoaPods/CocoaPods/issues/new) project. You will have to provide more information than just this error if you want them to be able to help you.

**Comment by jonasman** [comment]
+1 , this doesnt work with the new version.

**Comment by JEKos** [comment]
I fix that, remove the path from bridging header, and add `import XCDYouTubeKit` to your controller that you use it , if you have problem about doesn't build the "module" then, change the Scheme , go to `Product > Scheme > choose the XCDYouTubeKit` , build it only that, then go back to your app scheme, and go to `Window > Projects > and delete the Derived Data` , run it again, and see if there is no problems.
