### ISSUE TITLE
device becomes hot when play video

### ISSUE THREAD

**Issue by letungit90** [0xced/XCDYouTubeKit#255]

**Comment by Pranoy1c** [comment]
check out your CPU and memory usage and use Instruments to figure out where you might be having issues

**Comment by 0xced** [comment]
`XCDYouTubeVideoPlayerViewController` is a subclass of `MPMoviePlayerViewController` which is a system class. All the video playback is basically handled by the system and there’s nothing XCDYouTubeKit can do about that. As @Pranoy1c you might try to profile your app with Instruments and maybe find some code that is CPU intensive but I doubt it would be the player’s fault.

If you find evidence or suspicion that XCDYouTubeKit is the culprit, feel free to reopen this issue.
