### ISSUE TITLE
When playing certain videos, we get error XCDYouTubeVideoErrorDomain

### ISSUE THREAD

**Issue by Pranoy1c** [0xced/XCDYouTubeKit#257]
Since 10 PM June 22nd, when playing certain videos, we get error. Example video ID: 9WbCfHutDSE

JavaScript exception: TypeError: undefined is not an object
2016-06-22 22:50:45.449036 Musictrax[790:69034] [XCDYouTubeKit] Video operation finished with error: This video contains content from VEVO. It is restricted from playback on certain sites. Watch on YouTube
Domain: XCDYouTubeVideoErrorDomain
Code:   150
User Info: {
    AllowedCountries = "{(\n    \"Macau (China)\",\n    Hungary,\n    Vietnam,\n    \"New Caledonia\",\n    Burundi,\n    Andorra,\n    \"Pitcairn Islands\",\n    Guinea,\n    \"Norfolk Island\",\n    Togo,\n    Eritrea,\n    Zambia,\n    China,\n    Syria,\n    Mongolia,\n    Thailand,\n    Netherlands,\n    \"French Guiana\",\n    India,\n    Sudan,\n    Nicaragua,\n    Tanzania,\n    Algeria,\n    Grenada,\n    Venezuela,\n    \"Dominican Republic\",\n    Turkey,\n    \"New Zealand\",\n    Serbia,\n    Japan,\n    Monaco,\n    Finland,\n    Paraguay,\n    Lithuania,\n    Suriname,\n    Dominica,\n    Mauritania,\n    Armenia,\n    Panama,\n    \"St. Martin\",\n    Guernsey,\n    Cambodia,\n    \"Western Sahara\",\n    Azerbaijan,\n    Gabon,\n    Macedonia,\n    Tonga,\n    Bhutan,\n    Lebanon,\n    \"Sval
2016-06-22 22:50:45.449636 Musictrax[790:68456] Error from XCD when playing videoID: 9WbCfHutDSE 

: This video contains content from VEVO. It is restricted from playback on certain sites. Watch on YouTube

**Comment by sajsanghvi** [comment]
Yeah I'm getting that too. Error -2 as well when playing some non vevo videos. Damn

**Comment by Pranoy1c** [comment]
this happens pretty often when youtube changes their decoding algorithm or something. I wonder if there is a way for us to figure out how to fix it ourselves?

**Comment by nvvinhit2020** [comment]
+1

**Comment by zakhej** [comment]
+1

**Comment by ekinox87** [comment]
+1

**Comment by JavierQuerol** [comment]
+1

**Comment by PabloLerma** [comment]
+1

**Comment by alexruperez** [comment]
👍

**Comment by k06a** [comment]
Until #258 is merged you can use my solution this way:
```ruby
pod 'XCDYouTubeKit', :git => 'https://github.com/k06a/XCDYouTubeKit.git', :branch => 'patch-1'
```

**Comment by PabloLerma** [comment]
Perfect, thanks @k06a !

**Comment by salehp** [comment]
Hey @k06a, using your branch I still get "XCDYouTubeKit Failure
This video contains content from VEVO. It is restricted from playback on certain sites. Watch on YouTube" an example video id is: tWbLkXhGEmo.

**Comment by thiemdv** [comment]
@salehp : It works for me. I tested with your video id. Thank you @k06a !

**Comment by pir800** [comment]
If you're someone that prefers not to use pods, I replaced XCDYouTubePlayerScript.m with the file provided by @k06a here:

https://github.com/0xced/XCDYouTubeKit/blob/509bc1a704da62baeefc2d4a7b582fbb62aef7cf/XCDYouTubeKit/XCDYouTubePlayerScript.m

Thanks @k06a

**Comment by 0xced** [comment]
This is now fixed in version 2.5.3, enjoy!

**Comment by nvvinhit2020** [comment]
Hi,

I have this error message

[!] Unable to satisfy the following requirements:


- `XCDYouTubeKit (= 2.5.3)` required by `Podfile`


None of your spec sources contain a spec satisfying the dependency:
`XCDYouTubeKit (= 2.5.3)`.

Please help,


Thanks,

On Fri, Jun 24, 2016 at 3:39 PM, Cédric Luthi <notifications@github.com>
wrote:

> This is now fixed in version 2.5.3, enjoy!
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/0xced/XCDYouTubeKit/issues/257#issuecomment-228289735>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ALJieUT213H0bz3rZdqmJW4k2fPx5DA2ks5qO5exgaJpZM4I8aFi>
> .
>



-- 
*Nguyen Van Vinh*

Cellphone: 0973 158 957
Email : nvvinhit2020@gmail.com

**Comment by k06a** [comment]
`pod repo update && pod install`

**Comment by nvvinhit2020** [comment]
yeah, thank you so much. It works fine with me now ;)


On Fri, Jun 24, 2016 at 4:04 PM, Anton Bukov <notifications@github.com>
wrote:

> pod repo update && pod install
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/0xced/XCDYouTubeKit/issues/257#issuecomment-228295013>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ALJiedIiOin25uRagYO9OpEV2Q7tY_8Fks5qO52WgaJpZM4I8aFi>
> .
>



-- 
*Nguyen Van Vinh*

Cellphone: 0973 158 957
Email : nvvinhit2020@gmail.com

**Comment by 0xced** [comment]
@nvvinhit2020 I suggest you to use `pod "XCDYouTubeKit", "~> 2.5"` instead of `pod "XCDYouTubeKit", "= 2.5.3"` in order to always get the latest version when you upgrade your pods.

**Comment by cannyboy** [comment]
Are the constant VEVO changes predicable enough to handle server-side? .. as mentioned here: 

https://github.com/0xced/XCDYouTubeKit/issues/208#issuecomment-157417380

https://github.com/0xced/XCDYouTubeKit/issues/199

**Comment by JeromeTW** [comment]
Hi 
I have same error like nvvinhit2020
and @k06a 's answer （pod repo update && pod install）is not work for me.

How can i get 2.5.3 or latest version by Cocoapod

**Comment by 0xced** [comment]
You have to run `pod update` instead of `pod repo update && pod install` to update your pods. See [pod install vs. pod update](https://guides.cocoapods.org/using/pod-install-vs-update.html) in the CocoaPods guides.
