### ISSUE TITLE
Youtube video metadata download working before is no longer working

### ISSUE THREAD

**Issue by uBhappy2** [0xced/XCDYouTubeKit#261]
Hi Cedric & team, 

First of all thank you for a wonderful SDK for youtube downloads. I have integrated it with a music education app called Slowhand and Youtube video downloads have been working great! Today I noticed that the call to get video meta data is failing. I have tried it with multiple youtube videos and at different times to rule out rate limiting. Has Youtube made some changes to their APIs recently? 
Here is the error message I am getting while downloading the video metadata

`
2016-06-24 16:11:39.966 Slowhand[67145:4223867] [XCDYouTubeKit] Video operation finished with error: The operation couldn’t be completed. (XCDYouTubeVideoErrorDomain error -2.)
Domain: XCDYouTubeVideoErrorDomain
Code:   -2
User Info: {
    NSURL = "https://www.youtube.com/get_video_info?el=detailpage&hl=en&ps=default&video_id=dzkVoLJ0Hqs";
}
`

Is `get_video_info` an unsupported or deprecated API? Your thoughts/suggestions to workaround/fix this issue? 

Best,
Amit

**Comment by SoneeJohn** [comment]
@uBhappy2 update to v2.5.3 of the library which fixes this issue :).

**Comment by uBhappy2** [comment]
Thank you @SoneeJohn & @0xced!

**Comment by uBhappy2** [comment]
It does not seem like the issue is fully fixed. 

`Analyzing dependencies
Downloading dependencies
Using ORSSerialPort (2.0.2)
Installing XCDYouTubeKit 2.5.3 (was 2.5.2)`

The following video URL works 
https://www.youtube.com/watch?v=llNuwhZWXKA

But the one below does not
https://www.youtube.com/watch?v=AV-0Nfslshs

I had the same issue with v2.5.2. 

Best,
Amit

**Comment by SoneeJohn** [comment]
@uBhappy2 the second url seems to be working fine with the demo application.
Trying cleaning your build folder.
<img width="764" alt="screen shot 2016-06-24 at 4 53 32 pm" src="https://cloud.githubusercontent.com/assets/4827301/16350346/38cd0542-3a2c-11e6-8987-f22b11607713.png">

**Comment by uBhappy2** [comment]
Thank you my friend. Deleting DerivedData and a clean build fixed the issue. 👍
