### ISSUE TITLE
How do i get the error code when the video is not available for my country

### ISSUE THREAD

**Issue by lucascoria** [0xced/XCDYouTubeKit#265]
Hello, i want to inform any and all users that the video cannot play in case the video is not available for their country. here is the code i use to play the video embedded in a view.

```swift
func loadVideo()
    {
        let vidId = self.videosArray[self.currentIndexSelected]["videoID"] as! String
        let videoPlayer: XCDYouTubeVideoPlayerViewController = XCDYouTubeVideoPlayerViewController(videoIdentifier: vidId)
        videoPlayer.presentInView(self.playerView)
        let videoDetails = videosArray[self.currentIndexSelected]
        videoName.text = videoDetails["title"] as? String
        videoPlayer.moviePlayer.play()
    }
```

**Comment by aisgirish** [comment]
I am facing same issue. Someday ago it was working. But now.. Not working..! :(

**Comment by aisgirish** [comment]
When I try Youtube's sample code with YTPlayerView class, I got same error.
But when I add 
@"origin" : @"http://mywebsite.com"
It successfully load video.

So, please add this line into code, so, we can solve this issue.

**Comment by 0xced** [comment]
Please look at the very first [sample code](https://github.com/0xced/XCDYouTubeKit/#present-the-video-in-full-screen) in the README. Basically, you have to observe `MPMoviePlayerPlaybackDidFinishNotification` to get information about the error.
