### ISSUE TITLE
This video contains content from WMG. It is restricted from playback on certain sites. 

### ISSUE THREAD

**Issue by intari** [0xced/XCDYouTubeKit#267]
Starting from 21th July 2016 some videos return errors.
Example video IDs: YykjpeuMNEk , QtXby3twMmI

`[7981    ] 13:42:13.674 | miniPlayer | Main thread | __51-[MiniPlayerView preloadAssetsForStream:withAsset:]_block_invoke [Line 917] Failed to get video for preloading assets including video for stream Coldplay - Hymn For The Weekend (Official video) YykjpeuMNEk Error Domain=XCDYouTubeVideoErrorDomain Code=150 "This video contains content from WMG. It is restricted from playback on certain sites. Watch on YouTube" UserInfo={NSURL=https://www.youtube.com/get_video_info?el=embedded&hl=en&ps=default&video_id=YykjpeuMNEk, NSLocalizedDescription=This video contains content from WMG. It is restricted from playback on certain sites. Watch on YouTube, AllowedCountries={(
`
Looks like like #257

**Comment by SoneeJohn** [comment]
@intari I received a email from a user describing this issue. For some odd reason anytime YouTube changes it's API I'm still able to watch the video. For example, I'm able to play all the video identifiers you reported.

**Comment by SoneeJohn** [comment]
@intari are you still having this issue?

**Comment by AndrewKe** [comment]
I'm also getting a similar error

```
[XCDYouTubeKit] Video operation finished with error: This video contains content from VEVO. It is restricted from playback on certain sites. Watch on YouTube
Domain: XCDYouTubeVideoErrorDomain
Code:   150
User Info: {
    NSLocalizedDescription = "This video contains content from VEVO. It is restricted from playback on certain sites. Watch on YouTube";
    NSURL = "https://www.youtube.com/get_video_info?el=embedded&hl=en&ps=default&video_id=-OziZ-54kZk";
}
```

**Comment by jimmyor** [comment]
I am having the same issue.
`NSLocalizedDescription = "This video contains content from UMG. It is restricted from playback on certain sites. Watch on YouTube";
    NSURL = "https://www.youtube.com/get_video_info?el=embedded&hl=en&ps=default&video_id=lQ6akiGRcL8";`

**Comment by intari** [comment]
I no longer have issue with those vides but instead have issue with https://www.youtube.com/watch?v=XSNpGyG2jSw
Error Domain=XCDYouTubeVideoErrorDomain Code=150 "This video contains content from WMG. It is restricted from playback on certain sites. Watch on YouTube"

**Comment by 0xced** [comment]
Are you still experiencing issues with these two videos with XCDYouTubeKit 2.5.3? For me both videos are playing fine.

**Comment by intari** [comment]
not anymore

**Comment by videoBroadcasting** [comment]
Hello.
Now I have issue with above 2 videos.
https://www.youtube.com/watch?v=XSNpGyG2jSw
https://www.youtube.com/watch?v=z4SoaH_pu-Y

could you help me to fix this issue?
Error Domain=XCDYouTubeVideoErrorDomain Code=150

User Info = {...
NSLocalizationDescription = "This video is unavailable"
...}
