### ISSUE TITLE
Support Picture in picture in iOS 9.0 iPad

### ISSUE THREAD

**Issue by baryon** [0xced/XCDYouTubeKit#269]
Please support PiP

https://developer.apple.com/library/ios/documentation/AVFoundation/Reference/AVPlayerViewController_Class/index.html#//apple_ref/occ/cl/AVPlayerViewController

**Comment by 0xced** [comment]
Support for Picture in Picture (PiP) will be added in XCDYouTubeKit version 3 as it will use AVPlayerViewController.

**Comment by baryon** [comment]
What's schedule of Ver3
