### ISSUE TITLE
Unable to play certain Youtube Videos

### ISSUE THREAD

**Issue by shwetsolanki** [0xced/XCDYouTubeKit#274]
There are certain youtube videos which are not playable. I am unable to understand the type of videos. Here are the few videos which don't playback

```
https://www.youtube.com/watch?v=5Asd813Gcns
https://www.youtube.com/watch?v=Ap1K_Bh-o1o
https://www.youtube.com/watch?v=tZuj_beuMc4
https://www.youtube.com/watch?v=HKU96i_Qh8Y
```

Following are the console logs

> [XCDYouTubeKit] Unexpected player script (not an anonymous function)
[XCDYouTubeKit] JavaScript exception: TypeError: undefined is not an object (evaluating 'window.navigator.userAgent.match')
[XCDYouTubeKit] No signature function in player script
[XCDYouTubeKit] Video operation finished with error: The operation couldn’t be completed. (XCDYouTubeVideoErrorDomain error -2.)
Domain: XCDYouTubeVideoErrorDomain
Code:   -2
User Info: {
    NSURL = "https://www.youtube.com/get_video_info?el=detailpage&hl=en&ps=default&video_id=HKU96i_Qh8Y";
}

**Comment by 0xced** [comment]
Please make sure you are using the latest version of XCDYouTubeKit, i.e. 2.5.3 as of this writing. The four videos should play fine. Feel free to reopen this issue if they don't work with the latest version.
