### ISSUE TITLE
Crash on __pthread_kill:  on ios 10

### ISSUE THREAD

**Issue by ndhblue** [0xced/XCDYouTubeKit#275]
I Added XCDYoutube in ios 10 (swift 3.0) and it crash libsystem_kernel.dylib`__pthread_kill:

	0   CoreFoundation                      0x000000010beb134b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010b3e121e objc_exception_throw + 48
	2   CoreFoundation                      0x000000010bf20f34 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x000000010be36c15 ___forwarding___ + 1013
	4   CoreFoundation                      0x000000010be36798 _CF_forwarding_prep_0 + 120
	5   USFree                              0x0000000106f728d7 -[XCDYouTubeVideoOperation startRequestWithURL:type:] + 583
	6   USFree                              0x0000000106f7250a -[XCDYouTubeVideoOperation startNextRequest] + 570
	7   USFree                              0x0000000106f74af7 -[XCDYouTubeVideoOperation start] + 695
	8   Foundation                          0x000000010a6215ef __NSOQSchedule_f + 201
	9   libdispatch.dylib                   0x000000010dbec0cd _dispatch_client_callout + 8
	10  libdispatch.dylib                   0x000000010dbc9e6b _dispatch_queue_serial_drain + 236
	11  libdispatch.dylib                   0x000000010dbcab9f _dispatch_queue_invoke + 1073
	12  libdispatch.dylib                   0x000000010dbcd3b7 _dispatch_root_queue_drain + 720
	13  libdispatch.dylib                   0x000000010dbcd08b _dispatch_worker_thread3 + 123
	14  libsystem_pthread.dylib             0x000000010e079746 _pthread_wqthread + 1299
	15  libsystem_pthread.dylib             0x000000010e079221 start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException

This is my code:

```swift
var preferredVideoQualities = [XCDYouTubeVideoQuality.small240.rawValue, XCDYouTubeVideoQuality.medium360.rawValue, XCDYouTubeVideoQuality.HD720.rawValue]

 func startXCDYoutube(){
        //let client = XCDYouTubeClient.default()
        
        let videoOperation: XCDYouTubeOperation!
        
        videoOperation = XCDYouTubeClient.default().getVideoWithIdentifier(videoId, completionHandler: { (video, error) in
            
            if ((video) != nil)
            {
                // Do something with the `video` object
                
                let i = XCDYouTubeVideoQuality.medium360.rawValue
                
                
                self._urlDictionary.addEntries(from: (video?.streamURLs)!)
                
                // let url = self._urlDictionary[i] as! URL
                
                
                for itag in self.preferredVideoQualities
                {
                    
                    if ((self._urlDictionary[itag as! NSNumber]) != nil) {
                        
                        self._itagArray.add(itag)
                    }
                    
                }
                if (self._itagArray.contains(kYouTubeVideoQualityMedium360)  ) { //~> Ưu tiên 360p
                    
                    self._selectedItag = kYouTubeVideoQualityMedium360
                    
                }
                else{ //~> Nếu không có 360p thì lấy về cái nhỏ nhất vậy
                    self._selectedItag = Int(self._itagArray[0] as! NSNumber)
                     
                }
                self.stopActivityIndicator()
                self.initPlayer()
            
            }
            else
            {
                // Handle error
         
            }
        })

    }
```
******************************
Can You help me?

**Comment by ndhblue** [comment]
I add XCDYoutube throught  flie Bridging-Header.h

#ifndef Bridging-Header_h
#define Bridging-Header_h
#import"XCDYouTubeKit.h"
#endif /* Bridging-Header_h */

**Comment by 0xced** [comment]
Can you please provide the full error? For unrecognized selectors, you should have a message that says something like *[unrecognized selector sent to instance](http://stackoverflow.com/questions/25853947/how-can-i-debug-unrecognized-selector-sent-to-instance-error)*.

**Comment by ndhblue** [comment]
This is my full error 


[__NSCFType dataTaskWithRequest:completionHandler:]: unrecognized selector sent to instance 0x6000001ca500
2016-10-01 20:38:44.148 FunnyVideo[1138:46073] 
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFType dataTaskWithRequest:completionHandler:]: unrecognized selector sent to instance 0x6000001ca500'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010c10d34b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010bb6e21e objc_exception_throw + 48
	2   CoreFoundation                      0x000000010c17cf34 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x000000010c092c15 ___forwarding___ + 1013
	4   CoreFoundation                      0x000000010c092798 _CF_forwarding_prep_0 + 120
	5   USFree                              0x00000001076fc897 -[XCDYouTubeVideoOperation startRequestWithURL:type:] + 583
	6   USFree                              0x00000001076fc4ca -[XCDYouTubeVideoOperation startNextRequest] + 570
	7   USFree                              0x00000001076feab7 -[XCDYouTubeVideoOperation start] + 695
	8   Foundation                          0x000000010adae5ef __NSOQSchedule_f + 201
	9   libdispatch.dylib                   0x000000010e2e80cd _dispatch_client_callout + 8
	10  libdispatch.dylib                   0x000000010e2c5e6b _dispatch_queue_serial_drain + 236
	11  libdispatch.dylib                   0x000000010e2c6b9f _dispatch_queue_invoke + 1073
	12  libdispatch.dylib                   0x000000010e2c93b7 _dispatch_root_queue_drain + 720
	13  libdispatch.dylib                   0x000000010e2c908b _dispatch_worker_thread3 + 123
	14  libsystem_pthread.dylib             0x000000010e77a746 _pthread_wqthread + 1299
	15  libsystem_pthread.dylib             0x000000010e77a221 start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by 0xced** [comment]
I just created a new project with Xcode 8 / Swift 3 and I can not reproduce this crash. Could you please provide a sample project demonstrating this issue as explained in the [contribution guidelines](https://github.com/0xced/XCDYouTubeKit/blob/master/CONTRIBUTING.md)?

**Comment by ndhblue** [comment]
I checked my project . I can't send me my project, so  i created a new small example . When I set ARC is NO , it error. My project use youtube api , so i have to set ARC is NO.
This is my example  : 
https://www.mediafire.com/?li4yvu4eg537doc

**Comment by 0xced** [comment]
XCDYouTubeKit **MUST** be compiled with ARC, if you compiled it without ARC it will inevitably crash.

Please use CocoaPods, Carthage or manually integrate the XCDYouTubeKit static library or framework as documented in the [installation](https://github.com/0xced/XCDYouTubeKit/tree/2.5.3#installation) section of the README.
