### ISSUE TITLE
Play video, but no audio - iOS10.0.2

### ISSUE THREAD

**Issue by fernandaosbc** [0xced/XCDYouTubeKit#276]
Hi. I've been using this component for a while and it was working like a charm! Thank you very much for that!
Unfortunately, After upgrading to iOS 10.0.2 the videos are playing without sound and the screen won't rotate to landscape mode. The same is occuring on the Demo app.

Is there anything to be done on implementation, or the library must be updated?

I'm running the app on iOS 10.0.2, using XCode 8.0.

Thanks;

**Comment by rricarrdo** [comment]
As from [`here`] (https://github.com/0xced/XCDYouTubeKit/issues/195)

> just add this
> 
> [[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryPlayback error:nil];
> 
> in your PlayerviewController viewDidLoad and it will work
> 
> -Farid
> 

You will have to import <AVFoundation/AVFoundation.h>

**Comment by 0xced** [comment]
Exactly, the audio session configuration must be handled outside of XCDYouTubeKit. Thanks @rricarrdo for your help.
