### ISSUE TITLE
Can't use XCDYoutubeKit on tvOS

### ISSUE THREAD

**Issue by llKoull** [0xced/XCDYouTubeKit#280]
Hi!

I've been using this awesome library in my application called YouTrend for iOS or iPad, but now i want to do a new version for TvOS and something is wrong. Booth functions, the one that starts the video playing and the one that handles the movie stop are giving me errors that i does not see on iOS.

I attach some pictures of the errors (It seems like "import XCDYouTubeKit" is being ignored or there is some error inside the library).

Thanks and best regards!

![1](https://cloud.githubusercontent.com/assets/5525265/19417263/cbd3b518-93a8-11e6-9450-f06a5fdd3757.jpeg)
![2](https://cloud.githubusercontent.com/assets/5525265/19417264/cbfde2f2-93a8-11e6-808d-ce6e817aa639.jpeg)

**Comment by 0xced** [comment]
The `XCDYouTubeVideoPlayerViewController` class is not available on tvOS because it’s a subclass of `MPMoviePlayerViewController` which is not available on tvOS.

Please use this [sample code](https://github.com/0xced/XCDYouTubeKit/issues/157#issuecomment-208328872) for tvOS.
