### ISSUE TITLE
Multi-Target apps

### ISSUE THREAD

**Issue by FlaviaBondJamesBondsHusband** [0xced/XCDYouTubeKit#285]
Line 16 and 17 in the podspec file exclude the file`XCDYouTubeVideoPlayerViewController` on tvOS and macOS for obvious reasons. However, for multi-target projects, ie. projects that have both tvOS and iOS pods, the file is not downloaded. This means that when compiling the iOS project, the preprocessor condition in the umbrella header:

    #if TARGET_OS_IOS || (!defined(TARGET_OS_IOS) && TARGET_OS_IPHONE)
    #import <XCDYouTubeKit/XCDYouTubeVideoPlayerViewController.h>
    #endif
succeeds even though the file has not been downloaded. Could you remove line 16 and 17 from the podspec? It's not even necessary as you aren't even importing it unless the target application is running on an iOS device or sim.

**Comment by 0xced** [comment]
Can you please provide a sample project where this problem occurs? I tried a simple project with two targets with this Podfile and everything works fine for me with CocoaPods 1.1.1.

```ruby
target 'Player-iOS' do
  use_frameworks!
  pod 'XCDYouTubeKit', '~> 2.5'
end

target 'Player-tvOS' do
  use_frameworks!
  pod 'XCDYouTubeKit', '~> 2.5'
end
```
