### ISSUE TITLE
Controlstyle = .none doesn't work

### ISSUE THREAD

**Issue by sovannarithsok** [0xced/XCDYouTubeKit#288]
I have used this code to play a video but I don't want to show player control so I must set controlStyle to none. Unlucky it still does't work. I don't know why it appear.
Note*. I tested it with iOS 10      

    self.videoPlayer = XCDYouTubeVideoPlayerViewController.init(videoIdentifier: "Video_Id")           
    self.videoPlayer.moviePlayer.allowsAirPlay = false
    self.videoPlayer.moviePlayer.controlStyle = .none
    self.videoPlayer.moviePlayer.scalingMode = .aspectFill
    self.videoPlayer.moviePlayer.shouldAutoplay = true
    self.videoPlayer.moviePlayer.prepareToPlay()
    self.videoPlayer.present(in: self.playerView)

<img width="374" alt="screen shot 2016-11-23 at 3 15 31 pm" src="https://cloud.githubusercontent.com/assets/5999202/20554917/9a7d83c0-b191-11e6-840b-37dbdbe7f17a.png">

**Comment by Karov28** [comment]
Try to subclass the `XCDYouTubeVideoPlayerViewController`, and then override `viewWillAppear` method and put your code in it.
