### ISSUE TITLE
Certain video won't play 

### ISSUE THREAD

**Issue by sajsanghvi** [0xced/XCDYouTubeKit#291]
Hey, everything is working great - but on this one video https://www.youtube.com/watch?v=Q0oIoR9mLwc 

The song won't play. Anyone else having this issue?

**Comment by SoneeJohn** [comment]
@sajsanghvi which version of the library are you using?

**Comment by 0xced** [comment]
This video has an encoding issue for the 720p version. The only way to workaround this problem is not to play the 720p version. Here is some code to play the 360p version:

```objc
XCDYouTubeVideoPlayerViewController *videoPlayerViewController = [[XCDYouTubeVideoPlayerViewController alloc] initWithVideoIdentifier:@"Q0oIoR9mLwc"];
videoPlayerViewController.preferredVideoQualities = @[ @(XCDYouTubeVideoQualityMedium360), @(XCDYouTubeVideoQualitySmall240) ];
[self presentMoviePlayerViewControllerAnimated:videoPlayerViewController];
```
