### ISSUE TITLE
Videos with Warner Music Group logo are blocked

### ISSUE THREAD

**Issue by herman5** [0xced/XCDYouTubeKit#293]
Trying to play videos that have the Warner Music Group logo in the bottom right are unplayable. IE try to play this [video](https://www.youtube.com/watch?v=Q0oIoR9mLwc) and it will not work. However, other videos work just fine.

**Comment by JJGEight** [comment]
Are you using the latest version of XCDYouTubeKit? The video is playing for me without any problems.

**Comment by herman5** [comment]
This is on 2.5.3 - oddly enough it's just that one video I listed that will not play, but other videos from WMG play without problem. Closing this issue.

**Comment by 0xced** [comment]
This video has an encoding issue, please see https://github.com/0xced/XCDYouTubeKit/issues/291#issuecomment-266487194
