### ISSUE TITLE
Some videos return errors. Content from UMG etc

### ISSUE THREAD

**Issue by omose14** [0xced/XCDYouTubeKit#296]
Please help.

**Comment by Hamza-Almass** [comment]
yes i also have some videos return errors please help

**Comment by appcornerit** [comment]
+1 video id: JGwWNGJdvx8 (WMG) or JZroLpWR0os (VEVO)

**Comment by vdugnist** [comment]
@omose14 check fix in https://github.com/0xced/XCDYouTubeKit/issues/297

**Comment by omose14** [comment]
@vdugnist  Thank you, ill try it out

**Comment by vdugnist** [comment]
@omose14 close this issue if fix helps

**Comment by 0xced** [comment]
I just released version 2.5.4 which addresses this issue.
