### ISSUE TITLE
I get error code=-1 when play certain video 

### ISSUE THREAD

**Issue by artur7** [0xced/XCDYouTubeKit#299]
Hello. when I try to view video with ID : 2BFMvgI13ko (Resident Evil 7 trailer), I get an error -1, unsupported URL. It happens also on few other videos, eg. with ID = QpPwqVy6j10.
Can you help me?

**Comment by vdugnist** [comment]
@artur7  check fix in https://github.com/0xced/XCDYouTubeKit/issues/297

**Comment by artur7** [comment]
Thanks, it works!!
