### ISSUE TITLE
Error with specific video

### ISSUE THREAD

**Issue by GizumoMoca** [0xced/XCDYouTubeKit#301]
XCDYouTubeKit version to 2.5.4

VideoID: 09R8_2nJtjg
Xcode: 8.2.1
target: 8.0

**Comment by GizumoMoca** [comment]
Domain: XCDYouTubeVideoErrorDomain
Code:   -1
User Info: {
    NSLocalizedDescription = "\U672a\U5bfe\U5fdc\U306eURL";
    NSUnderlyingError = "Error Domain=NSURLErrorDomain Code=-1002 \"\U672a\U5bfe\U5fdc\U306eURL\" UserInfo={NSUnderlyingError=0x158217a30 {Error Domain=kCFErrorDomainCFNetwork Code=-1002 \"(null)\"}, NSErrorFailingURLStringKey=/yts/jsbin/player-ja_JP-vflyRanoY/base.js, NSErrorFailingURLKey=/yts/jsbin/player-ja_JP-vflyRanoY/base.js, NSLocalizedDescription=\U672a\U5bfe\U5fdc\U306eURL}";
}

**Comment by holloandris** [comment]
Same problem here as well!

**Comment by GizumoMoca** [comment]
Import XCDYouTubeKit.framework -> OK
CocoaPods pod 'XCDYouTubeKit' -> NG

**Comment by SoneeJohn** [comment]
Same issue here as well but I haven't been able to reproduce it. However, some of my customers have reported similar issues.

**Comment by Karov28** [comment]
Same here, the @GizumoMoca workaround worked for me too. The video I wanted to launch is xsguzMkWcr0.

**Comment by 0xced** [comment]
Make sure to update your Podfile to target iOS 8 or else XCDYouTubeKit won't be able to upgrade to XCDYouTubeKit 2.5.4 when you run `pod update`.
```ruby
platform :ios, '8.0'
```

The error you are showing (`NSErrorFailingURLKey=/yts/jsbin/player-en_US-vflkk7pUE/base.js`) is an evidence that you are still using version 2.5.3.
