### ISSUE TITLE
Ambiguous use of 'subscript'

### ISSUE THREAD

**Issue by NSMyself** [0xced/XCDYouTubeKit#302]
I've compiled XCDYouTubeKit v2.5 through Carthage but after adding the import in my Bridging-Header file I immediately got an "Ambiguous use of 'subscript'" error whenever i tried to parse an incoming JSON object like this:

`let share = raw?["actions"]?["share"] as? String ?? ""`

The problem lies in the second optional, everytime I try to use it I get that error

**Comment by NSMyself** [comment]
I got around the issue by casting the variable to `[String:AnyObject]` before accessing the subscript:

`let share = (raw?["actions"] as? [String:AnyObject])?["share"] as? String ?? ""`

**Comment by 0xced** [comment]
Unfortunately, I don’t know swift well enough to understand what’s happening but I’m glad you found a solution.
