### ISSUE TITLE
VEVO can not be played

### ISSUE THREAD

**Issue by sycode** [0xced/XCDYouTubeKit#303]
[XCDYouTubeKit] Video operation finished with error: This video contains content from VEVO. It is restricted from playback on certain sites or applications. Watch on YouTube
Domain: XCDYouTubeVideoErrorDomain
Code:   150

**Comment by 0xced** [comment]
Are you using the latest version, i.e. 2.5.4?

**Comment by sycode** [comment]
I'm sorry.
I was using version 2.5.3.
After updating to 2.5.4, it was able to play normally.
Thank you.

**Comment by namhn** [comment]
I can not update to version 2.5.4

**Comment by namhn** [comment]
I just install the 2.5.3
![screen shot 2017-02-09 at 11 59 31 pm](https://cloud.githubusercontent.com/assets/23704454/22793953/f8bb5ece-ef23-11e6-8a55-d09563c17c9a.png)

**Comment by SoneeJohn** [comment]
@namhn try using: `pod update XCDYouTubeKit`

**Comment by namhn** [comment]
I used pod XCDYouTubeKit update but can not update to version 2.5.4

**Comment by namhn** [comment]
![screen shot 2017-02-11 at 1 08 32 am](https://cloud.githubusercontent.com/assets/23704454/22838195/a7baee76-eff6-11e6-9bda-f85a89e3ebdd.png)

**Comment by namhn** [comment]
![screen shot 2017-02-11 at 1 08 32 am](https://cloud.githubusercontent.com/assets/23704454/22838203/b2eacfbe-eff6-11e6-96be-72dba612ce1e.png)

**Comment by SoneeJohn** [comment]
@namhn can I see your podfile?

**Comment by SoneeJohn** [comment]
@namhn or you can try changing the pod file to include: `pod "XCDYouTubeKit", "~> 2.5"`

**Comment by sycode** [comment]
I changed from 2.5.3 to 2.5.4 by changing as follows.

(podfile)
- platform :ios, '7.0'
+ platform :ios, '8.0'

If the target version of ios is 7.0, updating from 2.5.3 was not possible even if pod update was done.
However, when I changed the target version to 8.0, I was able to successfully update to 2.5.4.

**Comment by 0xced** [comment]
Glad you solve it!
