### ISSUE TITLE
we can not play video

### ISSUE THREAD

**Issue by namhn** [0xced/XCDYouTubeKit#305]
![screen shot 2017-02-09 at 11 54 27 pm](https://cloud.githubusercontent.com/assets/23704454/22793709/33fdceaa-ef23-11e6-8174-bf13ffe2f752.png)

**Comment by 0xced** [comment]
Unfortunately, you did not provide enough information for me to help you. Please have a look at how to [submit an issue](https://github.com/0xced/XCDYouTubeKit/blob/97c8fc167493e38bb3adce918bf992776ea7d404/CONTRIBUTING.md#submitting-issues).

**Comment by 0xced** [comment]
No reply from original poster, so I’m closing the issue.
