### ISSUE TITLE
How can I get notification when play video failed

### ISSUE THREAD

**Issue by gauuni** [0xced/XCDYouTubeKit#307]
Firstly, I want to thank you that make a great library for us.
Now I have a problem, I want to show an alert when error occurred.
I try to get notification but failed. 
Any idea to solve this?
Thanks.

**Comment by 0xced** [comment]
How to register for notifications, right from the [README](https://github.com/0xced/XCDYouTubeKit/tree/97c8fc167493e38bb3adce918bf992776ea7d404#present-the-video-in-full-screen):
```objc
- (void) playVideo
{
    XCDYouTubeVideoPlayerViewController *videoPlayerViewController = [[XCDYouTubeVideoPlayerViewController alloc] initWithVideoIdentifier:@"9bZkp7q19f0"];
    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(moviePlayerPlaybackDidFinish:) name:MPMoviePlayerPlaybackDidFinishNotification object:videoPlayerViewController.moviePlayer];
    [self presentMoviePlayerViewControllerAnimated:videoPlayerViewController];
}

- (void) moviePlayerPlaybackDidFinish:(NSNotification *)notification
{
    [[NSNotificationCenter defaultCenter] removeObserver:self name:MPMoviePlayerPlaybackDidFinishNotification object:notification.object];
    MPMovieFinishReason finishReason = [notification.userInfo[MPMoviePlayerPlaybackDidFinishReasonUserInfoKey] integerValue];
    if (finishReason == MPMovieFinishReasonPlaybackError)
    {
        NSError *error = notification.userInfo[XCDMoviePlayerPlaybackDidFinishErrorUserInfoKey];
        // Handle error
    }
}
```

**Comment by gauuni** [comment]
Thank you for your supporting
But I have used it on iOS10, and it didn't receive the notification when error occured

Best regards,

Nguyen Khoi Nguyen
iOS Developer
+84 122 7513 733 (tel:+84%20122%207513%20733)
Contact to Nguyen's Skype (skype:khoinguyeniosdev?chat)
Contact to Nguyen's Gmail (mailto:nguyenkhoinguyen082444@gmail.com)
