### ISSUE TITLE
Private video crash

### ISSUE THREAD

**Issue by mannanr** [0xced/XCDYouTubeKit#310]
I am using XCDYouTubeKit to play videos in my application using swift. But app is crashing with error the file you are trying to play is private.

how to handle or get response from "youtubeVideoPlayer.moviePlaye" if file is not a valid file to play.

Any solution to this problem?

**Comment by SoneeJohn** [comment]
@mannanr As per the [contributing guidelines:](https://github.com/0xced/XCDYouTubeKit/blob/1d784c24cc6d6dd0567fec019ed29bbfd1386e89/CONTRIBUTING.md#submitting-issues)

> If you encounter a crash, provide a stack trace. At the time of the crash, just type the bt all command in the (lldb) command prompt. If you got a crash report from HockeyApp or Crashlytics for example, include the stack trace too, preferably in textual form instead of a screenshot for easier searching.

Are you sure that you are getting a *crash* or simply an error? From what I understand `XCDYouTubeKit` cannot fetch the streams of private videos and will simply return an error in a case like this. Also, it would be help if you provide the code that you are using the play the video.
