### ISSUE TITLE
Switching video quality while playling #57

### ISSUE THREAD

**Issue by akash-mastercreationz** [0xced/XCDYouTubeKit#311]
Hi all,

I wonder is there a way to switch video quality as needed?
I mean to play a particular stream quality according to the network state. For example if user is on 3G I want to play the lowest quality URL but if user moves to wifi I want to seamlessly switch to the better quality stream.

Is there any support for this kind of functionality?

This was the issue #57 . Please solve this.

**Comment by SoneeJohn** [comment]
@akash-mastercreationz unfortunately the stream URLs that you get from XCDYouTubeKit (which is from YouTube) doesn't use [Adaptive bitrate streaming](https://en.wikipedia.org/wiki/Adaptive_bitrate_streaming) which would allow the functionality that you described.

**Comment by akash-mastercreationz** [comment]
@SoneeJohn do you mean that if wifi speed is very good, the quality of the video will be good(or high) And in case if the wifi goes down or slow (slow speed network) then also  the quality of the remains the same and it takes much time for buffering. 

Actually i want some solution so that if the speed of the wifi is high then the video should be of high quality and if anyhow the speed of the wifi goes slow (or very bad network) the quality of the video goes low, the video remain playing in low quality without delay(or without taking much time to load video).

**Comment by SoneeJohn** [comment]
@akash-mastercreationz Yes that is correct. You will have to manually find a way to implement that.

**Comment by 0xced** [comment]
Thanks @SoneeJohn for replying. I'm replicating my statement from #57, nothing has changed since 2014:

> This kind of functionality is called [Adaptive bitrate streaming](http://en.wikipedia.org/wiki/Adaptive_bitrate_streaming). Apple supports [HTTP Adaptive Streaming](https://developer.apple.com/streaming/) in iOS but unfortunately, YouTube doesn’t have HTTP Live Streaming files to serve for iOS devices.
> 
> What @Darso suggests might work but without even trying I can already predict that the switch will be anything but seamless.
> 
> Currently, there is no solution to this problem. In the future, YouTube could provide HTTP Live Streaming files and XCDYouTubeKit would take advantage of it (it is already the case for live videos only) or Apple could add support for [MPEG-DASH](http://en.wikipedia.org/wiki/Dynamic_Adaptive_Streaming_over_HTTP) in iOS. Unfortunately, I don’t see either of these possibilities become a reality any time soon.

**Comment by akash-mastercreationz** [comment]
Thanks @SoneeJohn , @0xced  for the help.
