### ISSUE TITLE
XCDYouTubeKit does not work now

### ISSUE THREAD

**Issue by chaocharleswang** [0xced/XCDYouTubeKit#314]
Hi,

XCDYouTubeKit does not work now.
Please check with that.

Many thanks!

**Comment by mhuusko5** [comment]
👍 "The video contains content from VEVO. It is restricted..."

**Comment by chaocharleswang** [comment]
Thanks for your update.

**Comment by hodalgun** [comment]
All vevo videos does not work now
Please help me!!

**Comment by flamme0011** [comment]
It is not working for me too. What can we do for solution?
Please help us!!!
Thanks

**Comment by chaocharleswang** [comment]
I found some other videos (not Vevo) also do not work, e.g.,

ADELE - HELLO (COVER BY LEROY SANCHEZ)
https://www.youtube.com/watch?v=vlZ9kjCrGJw

**Comment by chaocharleswang** [comment]
I found https://github.com/rg3/youtube-dl can work.
Thanks.

**Comment by bdfantini** [comment]
I see this error on console:

```
[XCDYouTubeKit] JavaScript exception: TypeError: undefined is not an object
[XCDYouTubeKit] Video operation finished with error: The operation couldn’t be completed. (XCDYouTubeVideoErrorDomain error -2.)
```

**Comment by JmyW** [comment]
I got same problem, the StreamURL is retrieved failed since a couple hours ago. 
It did work fine in past several weeks with 2.5.4 but now. Looks like YouTube did some change on Tue. again. Please help, thanks.

**Comment by Hamza-Almass** [comment]
the XCDYoutubeKit Not working now please help

**Comment by tin612** [comment]
I got the same problem.

**Comment by bdfantini** [comment]
Guys, now I don't have time to make a PR, but we've found the solution for this, just modify the regex on this line: https://github.com/0xced/XCDYouTubeKit/blob/master/XCDYouTubeKit/XCDYouTubePlayerScript.m#L71

to:

`@"[\"']signature[\"']\\s*,\\s*([^\()]+)\\("`

**Comment by 0xced** [comment]
I’m working on it.

**Comment by hodalgun** [comment]
i'm working on it too
thanks

**Comment by 0xced** [comment]
@hodalgun I already have a solution and will publish a new release in a few minutes, you can stop working on it. 😉

**Comment by hodalgun** [comment]
@0xced Ok!!!  Thank so much

**Comment by chaocharleswang** [comment]
Cool. Thanks!

**Comment by vninfo** [comment]
Great!. It works. Thanks.
