### ISSUE TITLE
unsupported URL

### ISSUE THREAD

**Issue by red010182** [0xced/XCDYouTubeKit#318]
Nice work for this project! However, most youtube videos work, but some fail.

Failed to play videos:
https://www.youtube.com/watch?v=JRMOMjCoR58
https://www.youtube.com/watch?v=--zku6TB5NY

ENV:
iPhone 6, iOS 10
non-fullscreen
everything default setting

I'm not sure if it's due to youtube ads, because both video get over 40 million watches and typically more popular video get higher possibilities to show ads.

Full error message:

```
[XCDYouTubeKit] Video operation finished with error: unsupported URL
Domain: XCDYouTubeVideoErrorDomain
Code:   -1
User Info: {
    NSLocalizedDescription = "unsupported URL";
    NSUnderlyingError = "Error Domain=NSURLErrorDomain Code=-1002 \"unsupported URL\" UserInfo={NSUnderlyingError=0x17025de80 {Error Domain=kCFErrorDomainCFNetwork Code=-1002 \"(null)\"}, NSErrorFailingURLStringKey=/yts/jsbin/player-en_US-vflOnuOF-/base.js, NSErrorFailingURLKey=/yts/jsbin/player-en_US-vflOnuOF-/base.js, NSLocalizedDescription=unsupported URL}";
}
```

**Comment by Hamza-Almass** [comment]
i also got the same message with the error domain

**Comment by 0xced** [comment]
Please make sure to use the latest version of XCDYouTubeKit, i.e. version 2.5.5. If you ran `pod update` without updating the iOS platform to iOS 8 in your Podfile, XCDYouTubeKit will be stuck at version 2.5.3.

```ruby
platform :ios, '8.0'
```

**Comment by entotsu** [comment]
Thank you for great framework.

I still have a same problem.

At version 2.5.5, Also Failed to get video url at these videos:
https://www.youtube.com/watch?v=eAZciRL4STE
https://www.youtube.com/watch?v=qkJL-l5RoBw

with same error...

```
 [XCDYouTubeKit] Video operation finished with error: unsupported URL
Domain: XCDYouTubeVideoErrorDomain
Code:   -1
User Info: {
    NSLocalizedDescription = "unsupported URL";
    NSUnderlyingError = "Error Domain=NSURLErrorDomain Code=-1002 \"unsupported URL\" UserInfo={NSUnderlyingError=0x60000005b120 {Error Domain=kCFErrorDomainCFNetwork Code=-1002 \"(null)\"}, NSErrorFailingURLStringKey=/yts/jsbin/player-vflppxuSE/en_US/base.js, NSErrorFailingURLKey=/yts/jsbin/player-vflppxuSE/en_US/base.js, NSLocalizedDescription=unsupported URL}";
}

```

ENV:
iPhone 6s, iOS 10
everything default setting
