### ISSUE TITLE
how can fix this problem please 

### ISSUE THREAD

**Issue by Hamza-Almass** [0xced/XCDYouTubeKit#319]
hello friends 
i install the pod file 2.5  it is stuck on 2.5.3 version i enter the platform for  iOS 8.0 also stuck on version 2.5.3 the message which i got it is
the operation couldn't be completed (XCDYoutubeVideoErrorDomain error -2)
also i got the message for most url Unsupported URL
how can i fix this problem please

**Comment by red010182** [comment]
Check out #320

**Comment by Hamza-Almass** [comment]
my friend i use the
 pod repo update
pod update
and all is succeeding now tell me when i install pod i got this message
[!] Unable to find a specification for `XCDYouTubeKit (~> 2.5)`
what's the wrong ?

**Comment by Hamza-Almass** [comment]
i solved my friend 
i remove my pod master and install it again now i get the version 2.5.5
thank you very much
