### ISSUE TITLE
Update Pods version of 2.5.5

### ISSUE THREAD

**Issue by patrickjquinn** [0xced/XCDYouTubeKit#324]
Hi there,

The Pods version is still 2.5.4, would it be possible to update this to 2.5.5? Its causing chaos with my project 👍

**Comment by 0xced** [comment]
The [2.5.5 spec](https://github.com/CocoaPods/Specs/blob/43917abc207e7f97514a3df3c4972a1a9ff64640/Specs/7/d/3/XCDYouTubeKit/2.5.5/XCDYouTubeKit.podspec.json) is already published. Please run `pod update` to update XCDYouTubeKit to the latest version.

**Comment by patrickjquinn** [comment]
Oh! Sorry, pods where being cached, my bad!
