### ISSUE TITLE
Start Playing the video from specific time(like from 50th second).

### ISSUE THREAD

**Issue by akash-mastercreationz** [0xced/XCDYouTubeKit#327]
Can we play the viodeo from specific time .(like if the last played video was stoped at 40th second and when the user plays the same video after some time, it will start from 40th second)

**Comment by SoneeJohn** [comment]
@akash-mastercreationz if you're using `AVPlayer` to can use the `-seekToTime:` [method](https://developer.apple.com/reference/avfoundation/avplayer/1385953-seektotime?language=objc)

**Comment by 0xced** [comment]
You can try this:
```objc
XCDYouTubeVideoPlayerViewController *videoPlayerViewController = [[XCDYouTubeVideoPlayerViewController alloc] initWithVideoIdentifier:videoIdentifier];
videoPlayerViewController.moviePlayer.initialPlaybackTime = 40;
```

If it doesn’t work, try setting the initialPlaybackTime when receiving `XCDYouTubeVideoPlayerViewControllerDidReceiveVideoNotification`.
