### ISSUE TITLE
change video quality while video is playing or streaming?

### ISSUE THREAD

**Issue by kuldeep13990** [0xced/XCDYouTubeKit#330]
i want to change video quality as per user selection while video is playing like youtube.

i change quality by below code.

videoPlayerViewController.preferredVideoQualities = @[@(XCDYouTubeVideoQualityMedium360)];

but there's no reflection in video quality in video player.

how to refresh videoPlayer so it can play with changed quality?

**Comment by 0xced** [comment]
> I want to change video quality as per user selection while video is playing like youtube.

This has already been discussed in #57 and #311 and the answer is basically: you can’t. Sorry.
