### ISSUE TITLE
Custom player views design

### ISSUE THREAD

**Issue by ninoid** [0xced/XCDYouTubeKit#333]
Is possible to use the same functionlalities with other players controls layout and style? 
Like custom slider which is same as one one used by original youtube app, or custom play and pause images which are centered in player?
Thanks for any advice! :]

**Comment by varunmehta77** [comment]
@ninoid  Hey you get any solution?
I am also looking for same but didn't get any solution for this.
Plz, suggest if you find any solution.
Thanks
