### ISSUE TITLE
MPMoviePlayerViewController got deprecated in iOS9. Can you please update it to have AVPlayerViewController?

### ISSUE THREAD

**Issue by srinivasgadda** [0xced/XCDYouTubeKit#339]
XCDYouTubeVideoPlayerViewController is a subclass to MPMoviePlayerViewController and we need to use XCDYouTubeVideoPlayerViewController to play a video. It is better to have it subclass from AVPlayerViewController since MPMoviePlayerViewController deprecated in iOS 9.

**Comment by 0xced** [comment]
Plase refer to https://github.com/0xced/XCDYouTubeKit/issues/157#issuecomment-208328872 if you absolutely want to use AVPlayerViewController.
