### ISSUE TITLE
"skipping input stream" log

### ISSUE THREAD

**Issue by NikKovIos** [0xced/XCDYouTubeKit#341]
Hello!
There is a problem - after implementing player in Swift 3 by this [comment](https://github.com/0xced/XCDYouTubeKit/issues/157#issuecomment-208328872)
after dismissing a player there is a log, thas is continue to appear every second:
` [aqme] 254: AQDefaultDevice (173): skipping input stream 0 0 0x0`

I'm using simulator IphoneSE

**Comment by 0xced** [comment]
This log is produced by the AudioToolbox framework. There is nothing that XCDYouTubeKit can do about it, sorry.
