### ISSUE TITLE
How to support iOS7.0?

### ISSUE THREAD

**Issue by light-bo** [0xced/XCDYouTubeKit#344]
I want to support **iOS 7.0**, i want to know where the codes that invoke api which only support iOS 8.0 and later, then i can modify it to support iOS7.0?  Looking forward to your reply. ^_^

**Comment by Bigjohn123** [comment]
我决定写个宏，真机调试，遇到崩溃或者出问题的地方就改用ios7被高版本废弃的方法

**Comment by 0xced** [comment]
I remember that the `-[XCDYouTubeVideo debugDescription]` method uses `NSDateComponentsFormatter` which is only available since iOS 8. I will not provide further guidance to enable iOS 7 support, sorry.
