### ISSUE TITLE
Compile time issue 

### ISSUE THREAD

**Issue by swalehap** [0xced/XCDYouTubeKit#347]
Building on Xcode9 beta. 
Error: Implicit conversion from nullable pointer 'Method _Nullable' (aka 'struct objc_method *') to non-nullable pointer type 'Method _Nonnull' (aka 'struct objc_method *')

Filename : XCDYoutubeLogger.m
Line:
const char * typeEncoding = method_getTypeEncoding(class_getClassMethod(DDLogClass, logSeletor));

method : initialize
Pls fix this issue.

How can we get compiled version of XCDYoutube library?

**Comment by 0xced** [comment]
I have released version 2.5.6 with Xcode 9 support.
