### ISSUE TITLE
Does XCDYouTubeKit support audio only?

### ISSUE THREAD

**Issue by oososo** [0xced/XCDYouTubeKit#364]
Does XCDYouTubeKit support audio only? Thank you very much.

**Comment by KiranPanesar** [comment]
`XCDYouTubeClient`'s `-getVideoWithIdentifier:videoId:completionHandler:` method will give you the raw MP4 URLs. You can then pass them to the audio player of your choosing. I would recommend [FreeStreamer](https://github.com/muhku/FreeStreamer) as I'm unsure if the default Apple frameworks will support this behaviour.

If you want to use core Apple frameworks, you can also try using the `getVideoWithIdentifier:videoId:completionHandler:` method described above, playing the URL in an `AVPlayerViewController`, and then disconnecting the `AVPlayerLayer` from the player. This will basically cut off any visual output from the player, as described in this Apple Q&A: https://developer.apple.com/library/content/qa/qa1668/_index.html
