### ISSUE TITLE
<1> finished with error - code: -999 in tvOS app.

### ISSUE THREAD

**Issue by NarayananKannan** [0xced/XCDYouTubeKit#368]
I tried to create the AVPlayerView with the streamURL (the streamURL works on the browser) I get the following error in the console and nothing more.

Task <B5EB0721-1725-41E7-B6F0-9D5D43D2D8D6>.<1> finished with error - code: -999

**Comment by Wouter125** [comment]
Same issue over here, audio is playing but video is missing. Also noticed that on load I'm getting the following warning:

`[XCDYouTubeKit] JavaScript exception: TypeError: window.matchMedia is not a function. (In 'window.matchMedia("(max-width: 656px)")', 'window.matchMedia' is undefined)`

I've been using the SDK for over a year now, and these issues just started. Unfortunately, I don't think this SDK is still supported. Most of the issues are unanswered and the last update is almost a year ago.
