### ISSUE TITLE
button to rotate the view(not device orientation)

### ISSUE THREAD

**Issue by alpamys-qanybet** [0xced/XCDYouTubeKit#371]
I was able to achieve fullscreen player to be in landscape mode while my application in portrait only(locked and ignoring device orientation), by rotating the view of XCDYouTube in [react-native-youtube](https://github.com/inProgress-team/react-native-youtube), `RCTYoutubeStandalone.m`

```
float   angle = M_PI / 2;
CGAffineTransform transform = CGAffineTransformMakeRotation(angle);
...
videoPlayerViewController.view.transform = transform;
```

Now I want the user him/herself rotate the XCDYoutube view only and have the button as Youtube has for fullscreen, but in my case just to rotate from Portrait to Landscape and vice versa. And implement my functionality in your library,as I understood it is impossible to do it in [react-native-youtube](https://github.com/inProgress-team/react-native-youtube).

**Comment by Eramirez06** [comment]
Can you explain me how may i change the archivo to rotate to landscape the video always
