### ISSUE TITLE
JavaScript exception: TypeError: window.matchMedia is not a function

### ISSUE THREAD

**Issue by sixty8** [0xced/XCDYouTubeKit#375]
[XCDYouTubeKit] JavaScript exception: TypeError: window.matchMedia is not a function. (In 'window.matchMedia("(max-width: 656px)")', 'window.matchMedia' is undefined)

**Comment by simran-lbbd** [comment]
Facing the same issue

**Comment by edgarnsr** [comment]
Same here

**Comment by grossmae** [comment]
See #383. You will have to manually add it to your project until the PR is merged by the maintainer.

**Comment by sixty8** [comment]
@ SoneeJohn i do this in XCDYoubePlayerScript.m  to stop the Type error

`// javascript injection to stop window.matchMedia type error. 
	NSString * addMatchMediajs = @"var window=this;window.matchMedia=function(a){return false;};";
	NSString *script = [string stringByTrimmingCharactersInSet:[NSCharacterSet whitespaceAndNewlineCharacterSet]];
	script=[script stringByReplacingOccurrencesOfString:@"var window=this;" withString:addMatchMediajs];
	[_context evaluateScript:script];
	
	// replace this line:
	/*	NSString *script = [string stringByTrimmingCharactersInSet:[NSCharacterSet whitespaceAndNewlineCharacterSet]];
	[_context evaluateScript:script];
	*/`

**Comment by SoneeJohn** [comment]
@sixty8 Can you open a PR with these changes so I can have a look?

**Comment by sixty8** [comment]
see #397
