### ISSUE TITLE
Show Subtitles

### ISSUE THREAD

**Issue by ogezue** [0xced/XCDYouTubeKit#377]
I have enabled to display subtitles on my youtube settings for every video, but I don't get them in AVPlayer. Is there a setting in XCDYoutubeKit to enable them?

**Comment by SoneeJohn** [comment]
Unfortunately, there isn’t.

**Comment by ogezue** [comment]
are there alternatives?

**Comment by SoneeJohn** [comment]
@ogezue You will most likely have to do download the video and then process it by adding the subtitles manually. If you want to show then while streaming (which is what you seem that you want) then you will have to build additional custom work.

**Comment by ogezue** [comment]
I don't have any idea how to achieve this. Can you point me into the right direction? 
Why is it working in Browser?

**Comment by gonzo-oin** [comment]
@ogezue 
You can use YouTube API for downloading subtiles and [integrating manually](https://developer.apple.com/documentation/avfoundation/media_assets_playback_and_editing/adding_subtitles_and_alternative_audio_tracks) to the AVAsset. 
You also can use an alternative player like VLC or ffmpeg, it may be more easy to integrate subtiles.
