### ISSUE TITLE
XCDYouTubeKit and ipv6

### ISSUE THREAD

**Issue by SMorozovMinsk** [0xced/XCDYouTubeKit#380]
HI,
I using XCDYouTubeKit in my tvOS app. But instead AVPlayerViewController I use AVPlayer.
On iPV4 it's works fine. But when I test my app on iPV6 it's don't work. I received some thing like this:

    "m_Limit" = "m_LimitAll";
    "r_Attributes" = 1;
    sync = syna;

Do you know XCDYouTubeKit works with iPV6?

**Comment by mtkopone** [comment]
We ran into the same issue. But turns out no videos could be played from any source on the phone.
The solution was to restart the phone :facepalm:
