### ISSUE TITLE
-2 The operation couldn’t be completed. (XCDYouTubeVideoErrorDomain error -2.)

### ISSUE THREAD

**Issue by sixty8** [0xced/XCDYouTubeKit#382]
Is this the end of XCDYouTubeVideo?

**Comment by SoneeJohn** [comment]
It appear to be an issue with a JavaScript function. A possible fix was proposed here 

https://github.com/rg3/youtube-dl/pull/17464

I will work on implementing this fix and running the unit tests that the library contains to confirm. However, I won’t be able to until this weekend. Maybe @0xced might have it fixed by then. :-)

**Comment by SoneeJohn** [comment]
See #383

**Comment by yangjianwei2015** [comment]
Sdk internal breakpoint ，
info：
errorcode = "150",
"reason":"This video is unavailable."

**Comment by yangjianwei2015** [comment]
https://github.com/0xced/XCDYouTubeKit/pull/383/files

**Comment by yangjianwei2015** [comment]
thank you  [marktgodfrey](https://github.com/marktgodfrey)

**Comment by darkForestCat** [comment]
@yangjianwei2015 does this work right now, still getting the errors also after your fix in the XCDYouTubePlayerScript.m file.May be I am doing something in a wrong way?

**Comment by dimacorp** [comment]
@darkForestCat hey, how do you request this specific commit/pull request with a podfile? I tried the following:
    pod "XCDYouTubeKit", :git => 'https://github.com/0xced/XCDYouTubeKit.git', :branch => 'master', :commit => 'bf5cfb4'

pod update worked ok but it looks the code is still original (don't see the proposed fix).

**Comment by JmyW** [comment]
Can 0xced help to add the solution in code for cocoapod? thank you so much!

**Comment by JmyW** [comment]
Same as @darkForestCat, moved all lib. files into my project for resolving it. :-)

**Comment by JmyW** [comment]
Are you guys still workable? I'm getting error again today :-(

**Comment by JmyW** [comment]
Thanks, @SoneeJohn. Your solution is worked fine. Thank you.

**Comment by SoneeJohn** [comment]
Fixed in version [2.6.0](https://github.com/0xced/XCDYouTubeKit/releases/tag/2.6.0)
