### ISSUE TITLE
Error Domain=XCDYouTubeVideoErrorDomain Code=-2

### ISSUE THREAD

**Issue by dota2AndTI** [0xced/XCDYouTubeKit#385]
Error Domain=XCDYouTubeVideoErrorDomain Code=-2
版本2.5.6还是会出现这个问题，希望尽快解决

**Comment by SoneeJohn** [comment]
See #383. You will have to manually add it to your project until the PR is merged by the maintainer.

**Comment by SoneeJohn** [comment]
Fixed in version [2.6.0](https://github.com/0xced/XCDYouTubeKit/releases/tag/2.6.0)
