### ISSUE TITLE
New issues after #383 

### ISSUE THREAD

**Issue by khoozhiyan1997** [0xced/XCDYouTubeKit#389]
Here is the log for the new issue 

2018-09-14 08:46:52.091010+0800 Xenon[6874:57809] [XCDYouTubeKit] JavaScript exception: TypeError: window.matchMedia is not a function. (In 'window.matchMedia("(max-width: 656px)")', 'window.matchMedia' is undefined)
2018-09-14 08:46:52.167571+0800 Xenon[6874:57809] [XCDYouTubeKit] JavaScript exception: TypeError: window.matchMedia is not a function. (In 'window.matchMedia("(max-width: 656px)")', 'window.matchMedia' is undefined)
2018-09-14 08:46:52.178131+0800 Xenon[6874:57809] [XCDYouTubeKit] No signature function in player script
2018-09-14 08:46:52.182321+0800 Xenon[6874:57809] XCDYouTubeVideoErrorDomain
2018-09-14 08:46:52.183981+0800 Xenon[6874:57809] [XCDYouTubeKit] Video operation finished with error: この動画は再生できません。
Domain: XCDYouTubeVideoErrorDomain
Code:   150
User Info: {
    AllowedCountries = "{(\n    \"\\U30ab\\U30ca\\U30c0\",\n    \"\\U4ecf\\U9818\\U30ae\\U30a2\\U30ca\",\n    \"\\U30c8\\U30f3\\U30ac\",\n    \"\\U30b9\\U30ea\\U30e9\\U30f3\\U30ab\",\n    \"\\U30eb\\U30ef\\U30f3\\U30c0\",\n    \"\\U30a2\\U30eb\\U30b8\\U30a7\\U30ea\\U30a2\",\n    \"\\U30d1\\U30e9\\U30b0\\U30a2\\U30a4\",\n    \"\\U30de\\U30ab\\U30aa\\Uff08\\U4e2d\\U56fd\\Uff09\",\n    \"\\U30b9\\U30a6\\U30a7\\U30fc\\U30c7\\U30f3\",\n    \"\\U30c8\\U30eb\\U30af\\U30e1\\U30cb\\U30b9\\U30bf\\U30f3\",\n    \"\\U30de\\U30e8\\U30c3\\U30c8\\U5cf6\",\n    \"\\U30b8\\U30e3\\U30de\\U30a4\\U30ab\",\n    \"\\U30d6\\U30e9\\U30b8\\U30eb\",\n    \"\\U30b9\\U30ed\\U30d0\\U30ad\\U30a2\",\n    \"\\U30e2\\U30fc\\U30ea\\U30b7\\U30e3\\U30b9\",\n    \"\\U30ad\\U30eb\\U30ae\\U30b9\",\n    \"\\U6771\\U30c6\\U30a3\\U30e2\\U30fc\\U30eb\",\n    \"\\U30d4\\U30c8\\U30b1\\U30a2\\U30f3\\U8af8\\U5cf6\",\n    \"\\U30a2\\U30eb\\U30d0\",\n    \"\\U30db\\U30f3\\U30b8\\U30e5\\U30e9\\U30b9\",\n    \"\\U30bf\\U30fc\\U30af\\U30b9\\U30fb\\U30ab\\U30a4\\U30b3\\U30b9\\U8af8\\U5cf6\",\n    \"\\U30ac\\U30f3\\U30d3\\U30a2\",\n    \"\\U30b8\\U30e3\\U30fc\\U30b8\\U30fc\",\n    \"\\U30b9\\U30fc\\U30c0\\U30f3\",\n    \"\\U30cb\\U30a6\\U30a8\",\n    \"\\U30bd\\U30de\\U30ea\\U30a2\",\n    \"\\U30a2\\U30eb\\U30e1\\U30cb\\U30a2\",\n    \"\\U30b9\\U30ea\\U30ca\\U30e0\",\n    \"\\U30b7\\U30f3\\U30ac\\U30dd\\U30fc\\U30eb\",\n    \"\\U82f1\\U9818\\U30f4\\U30a1\\U30fc\\U30b8\\U30f3\\U8af8\\U5cf6\",\n    \"\\U30b3\\U30fc\\U30c8\\U30b8\\U30dc\\U30ef\\U30fc\\U30eb\",\n    \"\\U30ad\\U30e5\\U30e9\\U30bd\\U30fc\",\n    \"\\U30cb\\U30b8\\U30a7\\U30fc\\U30eb\",\n    \"\\U30de\\U30ea\",\n    \"\\U30d1\\U30e9\\U30aa\",\n    \"\\U30d6\\U30fc\\U30bf\\U30f3\",\n    \"\\U30b5\\U30f3\\U30fb\\U30de\\U30eb\\U30bf\\U30f3\",\n    \"\\U30d1\\U30ca\\U30de\",\n    \"\\U30ec\\U30e6\\U30cb\\U30aa\\U30f3\\U5cf6\",\n    \"\\U30b5\\U30a6\\U30b8\\U30a2\\U30e9\\U30d3\\U30a2\",\n    \"\\U30a6\\U30a9\\U30ea\\U30b9\\U30fb\\U30d5\\U30c4\\U30ca\",\n    \"\\U30b5\\U30f3\\U30fb\\U30d0\\U30eb\\U30c6\\U30eb\\U30df\\U30fc\\U5cf6\",\n    \"\\U30d9\\U30ca\\U30f3\",\n    \"\\U30d6\\U30eb\\U30f3\\U30b8\",\n    \"\\U897f\\U30b5\\U30cf\\U30e9\",\n    \"\\U30d9\\U30cd\\U30ba\\U30a8\\U30e9\",\n    \"\\U30ad\\U30d7\\U30ed\\U30b9\",\n    \"\\U30b5\\U30f3\\U30d4\\U30a8\\U30fc\\U30eb\\U5cf6\\U30fb\\U30df\\U30af\\U30ed\\U30f3\\U5cf6\",\n    \"\\U30aa\\U30de\\U30fc\\U30f3\",\n    \"\\U30d0\\U30c1\\U30ab\\U30f3\\U5e02\\U56fd\",\n    \"\\U30ac\\U30fc\\U30f3\\U30b8\\U30fc\",\n    \"\\U30d0\\U30df\\U30e5\\U30fc\\U30c0\",\n    \"\\U30df\\U30e3\\U30f3\\U30de\\U30fc\",\n    \"\\U30d7\\U30a8\\U30eb\\U30c8\\U30ea\\U30b3\",\n    \"\\U30ab\\U30f3\\U30dc\\U30b8\\U30a2\",\n    \"\\U30bf\\U30a4\",\n    \"\\U30ad\\U30ea\\U30d0\\U30b9\",\n    \"\\U30bb\\U30f3\\U30c8\\U30d8\\U30ec\\U30ca\",\n    \"\\U30e9\\U30c8\\U30d3\\U30a2\",\n    \"\\U30b9\\U30a4\\U30b9\",\n    \"\\U30ab\\U30fc\\U30dc\\U30d9\\U30eb\\U30c7\",\n    \"\\U30ac\\U30fc\\U30ca\",\n    \"\\U30e2\\U30fc\\U30ea\\U30bf\\U30cb\\U30a2\",\n    \"\\U30b0\\U30a2\\U30c6\\U30de\\U30e9\",\n    \"\\U30ab\\U30bf\\U30fc\\U30eb\",\n    \"\\U30a2\\U30e1\\U30ea\\U30ab\\U5408\\U8846\\U56fd\",\n    \"\\U30ce\\U30fc\\U30d5\\U30a9\\U30fc\\U30af\\U5cf6\",\n    \"\\U30e2\\U30ca\\U30b3\",\n    \"\\U30af\\U30a6\\U30a7\\U30fc\\U30c8\",\n    \"\\U30ac\\U30a4\\U30a2\\U30ca\",\n    \"\\U30c1\\U30e5\\U30cb\\U30b8\\U30a2\",\n    \"\\U30cf\\U30f3\\U30ac\\U30ea\\U30fc\",\n    \"\\U30dc\\U30ea\\U30d3\\U30a2\",\n    \"\\U30c9\\U30df\\U30cb\\U30ab\\U56fd\",\n    \"\\U30a2\\U30eb\\U30bc\\U30f3\\U30c1\\U30f3\",\n    \"\\U30de\\U30e9\\U30a6\\U30a4\",\n    \"\\U30d0\\U30cf\\U30de\",\n    \"\\U30a8\\U30eb\\U30b5\\U30eb\\U30d0\\U30c9\\U30eb\",\n    \"\\U4ecf\\U9818\\U6975\\U5357\\U8af8\\U5cf6\",\n    \"\\U30c9\\U30df\\U30cb\\U30ab\\U5171\\U548c\\U56fd\",\n    \"\\U30bf\\U30f3\\U30b6\\U30cb\\U30a2\",\n    \"\\U30b7\\U30ea\\U30a2\",\n    \"\\U30aa\\U30fc\\U30b9\\U30c8\\U30ea\\U30a2\",\n    \"\\U30aa\\U30e9\\U30f3\\U30c0\\U9818\\U30ab\\U30ea\\U30d6\",\n    \"\\U30e2\\U30f3\\U30c8\\U30bb\\U30e9\\U30c8\",\n    \"\\U30b8\\U30d6\\U30c1\",\n    \"\\U30a4\\U30e9\\U30af\",\n    \"\\U30a4\\U30f3\\U30c9\",\n    \"\\U30b3\\U30f3\\U30b4\\U5171\\U548c\\U56fd\\Uff08\\U30d6\\U30e9\\U30b6\\U30d3\\U30eb\\Uff09\",\n    \"\\U30e2\\U30ed\\U30c3\\U30b3\",\n    \"\\U30b1\\U30a4\\U30de\\U30f3\\U8af8\\U5cf6\",\n    \"\\U30a2\\U30bc\\U30eb\\U30d0\\U30a4\\U30b8\\U30e3\\U30f3\",\n    \"\\U30d0\\U30eb\\U30d0\\U30c9\\U30b9\",\n    \"\\U30dd\\U30fc\\U30e9\\U30f3\\U30c9\",\n    \"\\U30eb\\U30af\\U30bb\\U30f3\\U30d6\\U30eb\\U30af\",\n    \"\\U30ab\\U30e1\\U30eb\\U30fc\\U30f3\",\n    \"\\U30af\\U30ea\\U30b9\\U30de\\U30b9\\U5cf6\",\n    \"\\U30ae\\U30ea\\U30b7\\U30e3\",\n    \"\\U30e8\\U30eb\\U30c0\\U30f3\",\n    \"\\U30d0\\U30fc\\U30ec\\U30fc\\U30f3\",\n    \"\\U30b5\\U30f3\\U30de\\U30ea\\U30ce\",\n    \"\\U30d5\\U30e9\\U30f3\\U30b9\",\n    \"\\U30d1\\U30ec\\U30b9\\U30c1\\U30ca\\U81ea\\U6cbb\\U533a\",\n    \"\\U30b8\\U30d6\\U30e9\\U30eb\\U30bf\\U30eb\",\n    \"\\U7c73\\U9818\\U30b5\\U30e2\\U30a2\",\n    \"\\U30df\\U30af\\U30ed\\U30cd\\U30b7\\U30a2\\U9023\\U90a6\",\n    \"\\U30c8\\U30b1\\U30e9\\U30a6\",\n    \"\\U30a4\\U30bf\\U30ea\\U30a2\",\n    \"\\U30ca\\U30df\\U30d3\\U30a2\",\n    \"\\U30a6\\U30ac\\U30f3\\U30c0\",\n    \"\\U30ab\\U30b6\\U30d5\\U30b9\\U30bf\\U30f3\",\n    \"\\U30b7\\U30a8\\U30e9\\U30ec\\U30aa\\U30cd\",\n    \"\\U30d5\\U30a9\\U30fc\\U30af\\U30e9\\U30f3\\U30c9\\U8af8\\U5cf6\",\n    \"\\U30d5\\U30a3\\U30ea\\U30d4\\U30f3\",\n    \"\\U30a8\\U30ea\\U30c8\\U30ea\\U30a2\",\n    \"\\U30aa\\U30fc\\U30b9\\U30c8\\U30e9\\U30ea\\U30a2\",\n    \"\\U30d9\\U30eb\\U30ae\\U30fc\",\n    \"\\U30a8\\U30b8\\U30d7\\U30c8\",\n    \"\\U30b0\\U30a2\\U30e0\",\n    \"\\U30b3\\U30e2\\U30ed\",\n    \"\\U30a2\\U30e9\\U30d6\\U9996\\U9577\\U56fd\\U9023\\U90a6\",\n    \"\\U30af\\U30c3\\U30af\\U8af8\\U5cf6\",\n    \"\\U30ae\\U30cb\\U30a2\",\n    \"\\U30a2\\U30f3\\U30c9\\U30e9\",\n    \"\\U5317\\U30de\\U30ea\\U30a2\\U30ca\\U8af8\\U5cf6\",\n    \"\\U30a2\\U30f3\\U30ae\\U30e9\",\n    \"\\U30ea\\U30d2\\U30c6\\U30f3\\U30b7\\U30e5\\U30bf\\U30a4\\U30f3\",\n    \"\\U30b9\\U30ed\\U30d9\\U30cb\\U30a2\",\n    \"\\U30cf\\U30fc\\U30c9\\U5cf6\\U30fb\\U30de\\U30af\\U30c9\\U30ca\\U30eb\\U30c9\\U8af8\\U5cf6\",\n    \"\\U30a6\\U30af\\U30e9\\U30a4\\U30ca\",\n    \"\\U30d0\\U30f3\\U30b0\\U30e9\\U30c7\\U30b7\\U30e5\",\n    \"\\U30e1\\U30ad\\U30b7\\U30b3\",\n    \"\\U30d1\\U30ad\\U30b9\\U30bf\\U30f3\",\n    \"\\U30c8\\U30fc\\U30b4\",\n    \"\\U30c9\\U30a4\\U30c4\",\n    \"\\U30e2\\U30eb\\U30c7\\U30a3\\U30d6\",\n    \"\\U30a8\\U30c1\\U30aa\\U30d4\\U30a2\",\n    \"\\U4ecf\\U9818\\U30dd\\U30ea\\U30cd\\U30b7\\U30a2\",\n    \"\\U30de\\U30eb\\U30bf\",\n    \"\\U8d64\\U9053\\U30ae\\U30cb\\U30a2\",\n    \"\\U30b5\\U30f3\\U30c8\\U30e1\\U30fb\\U30d7\\U30ea\\U30f3\\U30b7\\U30da\",\n    \"\\U9999\\U6e2f\\Uff08\\U4e2d\\U56fd\\Uff09\",\n    \"\\U30ca\\U30a6\\U30eb\",\n    \"\\U30c1\\U30e3\\U30c9\",\n    \"\\U30e9\\U30aa\\U30b9\",\n    \"\\U30b9\\U30da\\U30a4\\U30f3\",\n    \"\\U30bb\\U30cd\\U30ac\\U30eb\",\n    \"\\U30ea\\U30d9\\U30ea\\U30a2\",\n    \"\\U30bb\\U30f3\\U30c8\\U30af\\U30ea\\U30b9\\U30c8\\U30d5\\U30a1\\U30fc\\U30fb\\U30cd\\U30fc\\U30f4\\U30a3\\U30b9\",\n    \"\\U4e2d\\U592e\\U30a2\\U30d5\\U30ea\\U30ab\\U5171\\U548c\\U56fd\",\n    \"\\U30bb\\U30eb\\U30d3\\U30a2\",\n    \"\\U30ec\\U30d0\\U30ce\\U30f3\",\n    \"\\U30c7\\U30f3\\U30de\\U30fc\\U30af\",\n    \"\\U30b3\\U30b3\\U30b9\\Uff08\\U30ad\\U30fc\\U30ea\\U30f3\\U30b0\\Uff09\\U8af8\\U5cf6\",\n    \"\\U30bb\\U30f3\\U30c8\\U30eb\\U30b7\\U30a2\",\n    \"\\U30cb\\U30e5\\U30fc\\U30b8\\U30fc\\U30e9\\U30f3\\U30c9\",\n    \"\\U30eb\\U30fc\\U30de\\U30cb\\U30a2\",\n    \"\\U4e2d\\U56fd\",\n    \"\\U30d9\\U30ea\\U30fc\\U30ba\",\n    \"\\U30d5\\U30a7\\U30ed\\U30fc\\U8af8\\U5cf6\",\n    \"\\U5357\\U30b8\\U30e7\\U30fc\\U30b8\\U30a2\\U5cf6\\U30fb\\U5357\\U30b5\\U30f3\\U30c9\\U30a4\\U30c3\\U30c1\\U8af8\\U5cf6\",\n    \"\\U30dc\\U30c4\\U30ef\\U30ca\",\n    \"\\U30ae\\U30cb\\U30a2\\U30d3\\U30b5\\U30a6\",\n    \"\\U30a2\\U30eb\\U30d0\\U30cb\\U30a2\",\n    \"\\U30ea\\U30c8\\U30a2\\U30cb\\U30a2\",\n    \"\\U30d1\\U30d7\\U30a2\\U30cb\\U30e5\\U30fc\\U30ae\\U30cb\\U30a2\",\n    \"\\U30b1\\U30cb\\U30a2\",\n    \"\\U30a8\\U30b9\\U30c8\\U30cb\\U30a2\",\n    \"\\U30b8\\U30e7\\U30fc\\U30b8\\U30a2\",\n    \"\\U30e2\\U30eb\\U30c9\\U30d0\",\n    \"\\U30aa\\U30fc\\U30e9\\U30f3\\U30c9\\U8af8\\U5cf6\",\n    \"\\U30b6\\U30f3\\U30d3\\U30a2\",\n    \"\\U30dc\\U30b9\\U30cb\\U30a2\\U30fb\\U30d8\\U30eb\\U30c4\\U30a7\\U30b4\\U30d3\\U30ca\",\n    \"\\U30aa\\U30e9\\U30f3\\U30c0\",\n    \"\\U30ea\\U30d3\\U30a2\",\n    \"\\U30ce\\U30eb\\U30a6\\U30a7\\U30fc\",\n    \"\\U30de\\U30eb\\U30c6\\U30a3\\U30cb\\U30fc\\U30af\",\n    \"\\U5927\\U97d3\\U6c11\\U56fd\",\n    \"\\U30da\\U30eb\\U30fc\",\n    \"\\U30a4\\U30a8\\U30e1\\U30f3\",\n    \"\\U30b3\\U30f3\\U30b4\\U6c11\\U4e3b\\U5171\\U548c\\U56fd\\Uff08\\U30ad\\U30f3\\U30b7\\U30e3\\U30b5\\Uff09\",\n    \"\\U30d5\\U30a3\\U30f3\\U30e9\\U30f3\\U30c9\",\n    \"\\U30c1\\U30a7\\U30b3\",\n    \"\\U5357\\U30a2\\U30d5\\U30ea\\U30ab\",\n    \"\\U30e2\\U30f3\\U30c6\\U30cd\\U30b0\\U30ed\",\n    \"\\U30de\\U30b1\\U30c9\\U30cb\\U30a2\",\n    \"\\U30b9\\U30ef\\U30b8\\U30e9\\U30f3\\U30c9\",\n    \"\\U30cb\\U30ab\\U30e9\\U30b0\\U30a2\",\n    \"\\U30ad\\U30e5\\U30fc\\U30d0\",\n    \"\\U30b8\\U30f3\\U30d0\\U30d6\\U30a8\",\n    \"\\U30e2\\U30f3\\U30b4\\U30eb\",\n    \"\\U30b3\\U30ed\\U30f3\\U30d3\\U30a2\",\n    \"\\U30a2\\U30d5\\U30ac\\U30cb\\U30b9\\U30bf\\U30f3\",\n    \"\\U5357\\U6975\",\n    \"\\U30b9\\U30d0\\U30fc\\U30eb\\U30d0\\U30eb\\U8af8\\U5cf6\\U30fb\\U30e4\\U30f3\\U30de\\U30a4\\U30a8\\U30f3\\U5cf6\",\n    \"\\U30d5\\U30a3\\U30b8\\U30fc\",\n    \"\\U30bd\\U30ed\\U30e2\\U30f3\\U8af8\\U5cf6\",\n    \"\\U30a2\\U30a4\\U30b9\\U30e9\\U30f3\\U30c9\",\n    \"\\U30ed\\U30b7\\U30a2\",\n    \"\\U30cb\\U30e5\\U30fc\\U30ab\\U30ec\\U30c9\\U30cb\\U30a2\",\n    \"\\U30a8\\U30af\\U30a2\\U30c9\\U30eb\",\n    \"\\U65e5\\U672c\",\n    \"\\U30c4\\U30d0\\U30eb\",\n    \"\\U30c8\\U30eb\\U30b3\",\n    \"\\U30de\\U30ec\\U30fc\\U30b7\\U30a2\",\n    \"\\U30cf\\U30a4\\U30c1\",\n    \"\\U30b5\\U30e2\\U30a2\",\n    \"\\U30e2\\U30b6\\U30f3\\U30d3\\U30fc\\U30af\",\n    \"\\U30af\\U30ed\\U30a2\\U30c1\\U30a2\",\n    \"\\U30b7\\U30f3\\U30c8\\U30fb\\U30de\\U30fc\\U30eb\\U30c6\\U30f3\",\n    \"\\U30dd\\U30eb\\U30c8\\U30ac\\U30eb\",\n    \"\\U30de\\U30f3\\U5cf6\",\n    \"\\U30c1\\U30ea\",\n    \"\\U30d6\\U30fc\\U30d9\\U5cf6\",\n    \"\\U30b0\\U30ec\\U30ca\\U30c0\",\n    \"\\U30d0\\U30cc\\U30a2\\U30c4\",\n    \"\\U30d9\\U30c8\\U30ca\\U30e0\",\n    \"\\U30a2\\U30a4\\U30eb\\U30e9\\U30f3\\U30c9\",\n    \"\\U30b0\\U30a2\\U30c9\\U30eb\\U30fc\\U30d7\",\n    \"\\U30ec\\U30bd\\U30c8\",\n    \"\\U30ca\\U30a4\\U30b8\\U30a7\\U30ea\\U30a2\",\n    \"\\U30b3\\U30b9\\U30bf\\U30ea\\U30ab\",\n    \"\\U30a4\\U30ae\\U30ea\\U30b9\",\n    \"\\U30de\\U30c0\\U30ac\\U30b9\\U30ab\\U30eb\",\n    \"\\U30c8\\U30ea\\U30cb\\U30c0\\U30fc\\U30c9\\U30fb\\U30c8\\U30d0\\U30b4\",\n    \"\\U30a4\\U30b9\\U30e9\\U30a8\\U30eb\",\n    \"\\U30bf\\U30b8\\U30ad\\U30b9\\U30bf\\U30f3\",\n    \"\\U30de\\U30fc\\U30b7\\U30e3\\U30eb\\U8af8\\U5cf6\",\n    \"\\U30a2\\U30f3\\U30c6\\U30a3\\U30b0\\U30a2\\U30fb\\U30d0\\U30fc\\U30d6\\U30fc\\U30c0\",\n    \"\\U30a4\\U30e9\\U30f3\",\n    \"\\U30bb\\U30f3\\U30c8\\U30d3\\U30f3\\U30bb\\U30f3\\U30c8\\U53ca\\U3073\\U30b0\\U30ec\\U30ca\\U30c7\\U30a3\\U30fc\\U30f3\\U8af8\\U5cf6\",\n    \"\\U30a6\\U30eb\\U30b0\\U30a2\\U30a4\",\n    \"\\U30d6\\U30eb\\U30ac\\U30ea\\U30a2\",\n    \"\\U30ac\\U30dc\\U30f3\",\n    \"\\U30a4\\U30f3\\U30c9\\U30cd\\U30b7\\U30a2\",\n    \"\\U30a2\\U30f3\\U30b4\\U30e9\",\n    \"\\U53f0\\U6e7e\",\n    \"\\U30bb\\U30fc\\U30b7\\U30a7\\U30eb\"\n)}";
    NSLocalizedDescription = "\U3053\U306e\U52d5\U753b\U306f\U518d\U751f\U3067\U304d\U307e\U305b\U3093\U3002";
    NSURL = "https://www.youtube.com/get_video_info?el=embedded&hl=ja&ps=default&video_id=MfTbHITdhEI";
}

**Comment by SoneeJohn** [comment]
@khoozhiyan1997 I am getting these issues as well. Will investigate :-)

**Comment by SoneeJohn** [comment]
@khoozhiyan1997 However, the issue you seem to be having is due to the region you're in.

**Comment by khoozhiyan1997** [comment]
The video are able to play before, but now it can't @SoneeJohn :(

**Comment by jiny90** [comment]
Same here. Any advance?

**Comment by flamme0011** [comment]
Same here too? Any solution or advice?

**Comment by SoneeJohn** [comment]
See #390

**Comment by khoozhiyan1997** [comment]
Thanks @SoneeJohn 👍

**Comment by SoneeJohn** [comment]
Fixed in version [2.6.0](https://github.com/0xced/XCDYouTubeKit/releases/tag/2.6.0)
