### ISSUE TITLE
Xcode 10 warnings: "Messaging unqualified id"

### ISSUE THREAD

**Issue by yoasha** [0xced/XCDYouTubeKit#393]
I have XCDYouTubeKit embedded as a static library in my workspace and I'm getting on Xcode 10.0 several warnings of "Messaging unqualified id".

Anyone else encountered this?

![image](https://user-images.githubusercontent.com/5601548/45931127-db85f880-bf71-11e8-883c-17e193c61ee0.png)

**Comment by wanghuajian620** [comment]
![2019-02-25 11 26 13](https://user-images.githubusercontent.com/31924547/53312488-34c2d100-38f0-11e9-89d6-fef724f5b4cc.png)
