### ISSUE TITLE
HD720 raw value can't be found anymore since 2.6.0

### ISSUE THREAD

**Issue by Wouter125** [0xced/XCDYouTubeKit#396]
I'm now running on 2.6.0 and fetching videos fine, but there are issues popping up. Videos that are available in 720p aren't being downloaded anymore. Only medium360 or below. 

So I think something is still not completely right in the regex or edits that are being done after #383 and #390.

@SoneeJohn I think you might have an explanation for this, so if you could update me around this issue, that would be lovely. Also thank you so much for all the contributions and merging so far.

**Comment by SoneeJohn** [comment]
Unfortunately, that's not a problem that that was caused due to the regex. The videos you're talking about aren't available in HD720p (`itag 22`) because some video don't contain it. However, most videos that exhibit this issue have a H720p version but it's with `itag 136` which contains only the video but no audio. 

This video here: https://www.youtube.com/watch?v=tg00YEETFzg isn't available in `itag 22` however, this video is: https://www.youtube.com/watch?v=_g8aLVGXyc0

See https://en.wikipedia.org/wiki/Talk:YouTube/Archive_22#Moved_from_YouTube#Quality_formats for more information on the itag values.

**Comment by Wouter125** [comment]
Thanks for the super quick follow up! I'm still stuck with a few additional questions and would love to see them answered if you find the time.

1. Before #383 and #390, I often obtained a 720p video without any problems. Even videos that do have issues right now. Is this because of a switch that YT made? Shifting videos from `itag 22` to `itag 136`?

2. Also why is this only happening to 720p videos? All 240p and 360p videos seem unharmed and having the `itag 36` and `itag 18` instead of `itag 133` and `itag 134`. 

3. I'm not really aware of all video codecs, and youtube specifics. So the million dollar question, is this something that can be fixed on our end? Like fetching the audio from a low res video, while showing the high res video? I assume YT is doing the same nowadays?

**Comment by SoneeJohn** [comment]
No problem.

> Before #383 and #390, I often obtained a 720p video without any problems. Even videos that do have issues right now. Is this because of a switch that YT made? Shifting videos from itag 22 to itag 136

I believe YouTube made a change with how they are serving certain videos.

> Also why is this only happening to 720p videos? All 240p and 360p videos seem unharmed and having the itag 36 and itag 18 instead of itag 133 and itag 134

Unfortunately, I can't answer that question. ;-) 

> So the million dollar question, is this something that can be fixed on our end? Like fetching the audio from a low res video, while showing the high res video?

One solution would be to fetch the `itag 136` and display it to the user while using the `itag 140` which should give you the audio for the video. However, doing this would involve doing some additional work. Currently, `AVPlayer` doesn't support that.

**Comment by SoneeJohn** [comment]
I think you would lose those features. Essentially what you will need to do is find a way to sync two `AVPlayer`s or something similar. Could be a bit challenging but I bet it can be done.

**Comment by Wouter125** [comment]
Solved it with two AVPlayers that are synced up. Extended this library to fetch 1080p videos and a separate audio track and works like a charm. Got a fallback on the player to see the difference between every player every 0.5s. This way I can sync them up if the difference becomes too big. Also if one of the player is not ready or can't catch up I'm pausing them and let them buffer both.

Thanks for your pointers. I might optimise it in the near future, but for now this is doing the trick. Luckily I'm not asked to add scrubbing, so haven't tried that, but everything else works!

**Comment by weiran** [comment]
I have a tvOS app which does this using VLCKit: https://github.com/weiran/watch-it-later

VLCKit can also play VP9 videos, and on an Apple TV 4K it can decode 4K30 with the odd dropped frame.
