### ISSUE TITLE
Cannot open project 'XCDYouTubeKit'

### ISSUE THREAD

**Issue by oTranAnhMinh** [0xced/XCDYouTubeKit#411]
Hello,

The project ‘XCDYouTubeKit’ is damaged and cannot be opened due to a parse error. Examine the project file for invalid edits or unresolved source control conflicts.

Please help to fix it.

Thanks,

**Comment by oTranAnhMinh** [comment]
Thank you so much.

**Comment by pigeon** [comment]
Thanks @gshaviv Fixed problem for me. Created PR

**Comment by SoneeJohn** [comment]
@gshaviv Thanks!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
