### ISSUE TITLE
YT getVideoWithIdentifier not working anymore?

### ISSUE THREAD

**Issue by JonJC** [0xced/XCDYouTubeKit#413]
I'm using v2.7.1

Videos that I used to be able to access using **getVideoWithIdentifier** are now returning this error:
 _Error Domain=XCDYouTubeVideoErrorDomain Code=150 "This video is unavailable." UserInfo={NSURL=https://www.youtube.com/get_video_info?el=embedded&hl=en&ps=default&video_id=co6WMzDOh1o, NSLocalizedDescription=This video is unavailable., AllowedCountries={(....._

The list of Allowed Countries DOES include my country

Here's an example YT id that used to work (but no longer does): _co6WMzDOh1o_
THere are many more.

**Comment by dauletkali** [comment]
+1

**Comment by JonJC** [comment]
is anyone else having issues?

**Comment by fangyuxi** [comment]
+1

**Comment by fangyuxi** [comment]
@JonJC @dauletkali 
I have used the latest version and the problem has been solved.
I copied the source code into the project, without cocopods.

**Comment by dauletkali** [comment]
@fangyuxi , thank you. version 2.7.1 solves the issue
