### ISSUE TITLE
Unable to resolve live stream (but worked on the VoD recorded from live stream)

### ISSUE THREAD

**Issue by tvbsddc** [0xced/XCDYouTubeKit#417]
Hi All, 
Tonight (round 23:00 GMT+8, 2019.01.10) we have an issue on resolving the m3u8 url for live streams (the live stream from news channels in Taiwan). However it still works well if we try to resolve the urls from some VoD that is recorded/stored by youtube . 
Does anyone have the same issue?
The Kit version is 2.7.1, used in iOS app. 

ex: 
Not working:  https://www.youtube.com/watch?v=Hu1FkdAOws0  (pure live streaming)
Still Working: https://www.youtube.com/watch?v=id6wnqD3cXc  (was a live streaming and now is a VoD)

-- Kenex

**Comment by BreeeZe** [comment]
I'm having the same issue with a livestream from ert.gr
https://www.youtube.com/watch?v=MRDeOhioF3g

The issue started today, the error I get from XCDYouTubeKit is:
Video operation finished with error: This video is unavailable.
Domain: XCDYouTubeVideoErrorDomain
Code:   150
User Info: {
    AllowedCountries = "{(\n    \"Caribbean Netherlands\",\n    Hungary,\n    Vietnam,\n    \"New Caledonia\",\n    Burundi,\n    Andorra,\n    \"Pitcairn Islands\",\n    Guinea,\n    \"Norfolk Island\",\n    Togo,\n    Eritrea,\n    Zambia,\n    China,\n    Syria,\n    Mongolia,\n    Thailand,\n    Netherlands,\n    \"French Guiana\",\n    India,\n    Sudan,\n    Nicaragua,\n    Tanzania,\n    Algeria,\n    Grenada,\n    Venezuela,\n    \"Dominican Republic\",\n    Turkey,\n    \"New Zealand\",\n    Serbia,\n    Japan,\n    Monaco,\n    Finland,\n    Paraguay,\n    Lithuania,\n    Suriname,\n    Dominica,\n    Mauritania,\n    Armenia,\n    Panama,\n    \"St. Martin\",\n    Guernsey,\n    Cambodia,\n    \"Western Sahara\",\n    Azerbaijan,\n    Gabon,\n    Macedonia,\n    Tonga,\n    Bhutan,\n    Lebanon,\n    \"Svalbard & Jan Mayen\",\n    \"Falkland Islands\",\n    Montserrat,\n    \"Cura\\U00e7ao\",\n    \"St. Helena\",\n    Peru,\n    \"Isle of Man\",\n    \"Congo - Kinshasa\",\n    Liberia,\n    Oman,\n    Ethiopia,\n    Vanuatu,\n    Romania,\n    Nepal,\n    Norway,\n    Niger,\n    \"South Sudan\",\n    \"So. Georgia & So. Sandwich Isl.\",\n    Turkmenistan,\n    Germany,\n    Aruba,\n    Comoros,\n    \"French Polynesia\",\n    Belgium,\n    Somalia,\n    \"U.S. Outlying Islands\",\n    \"American Samoa\",\n    Albania,\n    \"Sint Maarten\",\n    \"Myanmar (Burma)\",\n    Anguilla,\n    Botswana,\n    \"Faroe Islands\",\n    \"Solomon Islands\",\n    Cuba,\n    Guyana,\n    Nauru,\n    \"North Korea\",\n    \"El Salvador\",\n    Honduras,\n    Moldova,\n    Taiwan,\n    \"Equatorial Guinea\",\n    Chile,\n    Uzbekistan,\n    Bermuda,\n    \"British Indian Ocean Territory\",\n    Liechtenstein,\n    Argentina,\n    Libya,\n    Tajikistan,\n    \"Costa Rica\",\n    Canada,\n    Italy,\n    \"Congo - Brazzaville\",\n    Guam,\n    Qatar,\n    Mexico,\n    \"R\\U00e9union\",\n    Malaysia,\n    Cameroon,\n    Slovakia,\n    \"Cayman Islands\",\n    \"\\U00c5land Islands\",\n    Iran,\n    Micronesia,\n    \"San Marino\",\n    Poland,\n    Maldives,\n    Cyprus,\n    Israel,\n    Uruguay,\n    Palau,\n    Belarus,\n    Bangladesh,\n    Nigeria,\n    Russia,\n    Gibraltar,\n    \"Northern Mariana Islands\",\n    Ireland,\n    Croatia,\n    \"Timor-Leste\",\n    Brazil,\n    Barbados,\n    Colombia,\n    \"Cook Islands\",\n    Portugal,\n    \"Christmas Island\",\n    Bahamas,\n    Pakistan,\n    Bolivia,\n    \"Heard & McDonald Islands\",\n    Mali,\n    Ghana,\n    \"Antigua & Barbuda\",\n    \"Sri Lanka\",\n    Iraq,\n    \"South Africa\",\n    Kuwait,\n    \"Puerto Rico\",\n    Czechia,\n    Gambia,\n    \"Cape Verde\",\n    Latvia,\n    Fiji,\n    \"Palestinian Territories\",\n    Martinique,\n    \"St. Lucia\",\n    Mayotte,\n    Iceland,\n    \"British Virgin Islands\",\n    Switzerland,\n    Singapore,\n    \"Guinea-Bissau\",\n    Austria,\n    Namibia,\n    Mauritius,\n    Benin,\n    Tokelau,\n    Afghanistan,\n    \"St. Kitts & Nevis\",\n    Swaziland,\n    Bahrain,\n    \"United States\",\n    Chad,\n    Brunei,\n    Angola,\n    \"Papua New Guinea\",\n    \"United Arab Emirates\",\n    Kazakhstan,\n    Spain,\n    Guatemala,\n    \"Cocos (Keeling) Islands\",\n    \"U.S. Virgin Islands\",\n    Ukraine,\n    \"French Southern Territories\",\n    Philippines,\n    \"S\\U00e3o Tom\\U00e9 & Pr\\U00edncipe\",\n    \"South Korea\",\n    Djibouti,\n    Jamaica,\n    Slovenia,\n    Samoa,\n    Luxembourg,\n    Tuvalu,\n    Senegal,\n    \"Wallis & Futuna\",\n    Estonia,\n    Seychelles,\n    \"Saudi Arabia\",\n    Morocco,\n    Greece,\n    Georgia,\n    Kenya,\n    Tunisia,\n    \"Hong Kong (China)\",\n    Malta,\n    \"St. Vincent & Grenadines\",\n    \"Vatican City\",\n    \"Marshall Islands\",\n    Jersey,\n    \"Turks & Caicos Islands\",\n    \"St. Barth\\U00e9lemy\",\n    Laos,\n    Ecuador,\n    Yemen,\n    Belize,\n    Malawi,\n    Antarctica,\n    Sweden,\n    Greenland,\n    \"Bosnia & Herzegovina\",\n    Jordan,\n    Zimbabwe,\n    \"Bouvet Island\",\n    France,\n    \"Trinidad & Tobago\",\n    Mozambique,\n    Egypt,\n    \"United Kingdom\",\n    Lesotho,\n    Australia,\n    Uganda,\n    Kyrgyzstan,\n    Denmark,\n    \"Central African Republic\",\n    \"Sierra Leone\",\n    Montenegro,\n    Kiribati,\n    \"Burkina Faso\",\n    Niue,\n    Guadeloupe,\n    Indonesia,\n    Madagascar,\n    \"C\\U00f4te d\\U2019Ivoire\",\n    \"St. Pierre & Miquelon\",\n    Rwanda,\n    Haiti,\n    Bulgaria,\n    \"Macau (China)\"\n)}";
    NSLocalizedDescription = "This video is unavailable.";
    NSURL = "https://www.youtube.com/get_video_info?el=embedded&hl=en&ps=default&video_id=MRDeOhioF3g";
}

**Comment by SoneeJohn** [comment]
Thanks for the reports. Will look into this.

**Comment by BreeeZe** [comment]
I compiled my app pulling the pod from your 'develop' branch and the livestreams work again 👍

**Comment by bekarttech** [comment]
> I compiled my app pulling the pod from your 'develop' branch and the livestreams work again 👍

What does this exactly mean? Could you please write more explicitly what you have done?

**Comment by BreeeZe** [comment]
> > I compiled my app pulling the pod from your 'develop' branch and the livestreams work again 👍
> 
> I am suffering from the same problem. Live streams does not work and returns error code -2 (NoStreamAvailable) .What does this exactly mean? Could you please write more explicitly what you have done?

In your podfile you can define that you want to pull the pod from the github source directly.
The fixes where done on the "develop" branch, and you can define this in your podfile like this:

`pod 'XCDYouTubeKit', :git => "https://github.com/0xced/XCDYouTubeKit.git", :branch => "develop"`

Do note, that you are using code which might not be considered "stable" by the developer.

**Comment by pvegh** [comment]
for me the error is this (pod for develop)

[XCDYouTubeKit] Video operation finished with error: The operation couldn’t be completed. (XCDYouTubeVideoErrorDomain error -2.)
Domain: XCDYouTubeVideoErrorDomain
Code:   -2
User Info: {
}
Error Domain=XCDYouTubeVideoErrorDomain Code=-2 "(null)"
video: nil

**Comment by chinthaka** [comment]
I am afraid same issue here. 
```
[XCDYouTubeKit] Video operation finished with error: The operation couldn’t be completed. (XCDYouTubeVideoErrorDomain error -2.)
Domain: XCDYouTubeVideoErrorDomain
Code:   -2
User Info: {
}
```

**Comment by SoneeJohn** [comment]
@chinthaka  @pvegh  Please give me the video ID. Also, please clean your build folder and delete your Derived data.

**Comment by pvegh** [comment]
I don't have the ID anymore, it was the video in spacex.com/webcast before they switched to the iridium 8 recording. I guess I'll see when they switch to the "waiting for live webcast" again.
But I deleted derived data and tested a random live video from YT, which works. Too bad I didn't test it BEFORE :/

**Comment by chinthaka** [comment]
This is a live stream id. 7LEc9CCsrSY

**Comment by dpwilhelmsen** [comment]
Using the `XCDYouTubeKit OS X Demo`,  I can confirm that the `master` branch currently does not work with live videos. It works fine with normal youtube videos. When I switch to `develop` live streams work again. The video ID I've been using is `deWeERCVc2o`

**Comment by tvbsddc** [comment]
Sorry for the late update. 
In our case, we have confirmed that it work successfully with the develop branch.
Thanks for all the promot reply and support from you. (the develop team and the ones who echoed the issue.)

**Comment by SoneeJohn** [comment]
Fixed in latest update. Thanks for all the reports.
