### ISSUE TITLE
JavaScript exception: ReferenceError: Can't find variable: XMLHttpRequest

### ISSUE THREAD

**Issue by mavris** [0xced/XCDYouTubeKit#425]
Hi,
I updated to 2.7.3 and I still have this issue:
Video ids:
`eP0nRMlG960`
`kR1lDumQ9q8`
`ssdaFZYZ9dU`

Related:
https://github.com/0xced/XCDYouTubeKit/issues/420
https://github.com/0xced/XCDYouTubeKit/issues/418

**Comment by lexuanquynh** [comment]
same issue

**Comment by kingsofteng** [comment]
Same
