### ISSUE TITLE
Unable to stream age gated video '6kLq3WMV1nU'

### ISSUE THREAD

**Issue by nithin-george** [0xced/XCDYouTubeKit#431]
I am trying a age restricted video but it seems it is not able to get any urls and failing. I believe embed is not allowed here. I have attached the link below from youtube-dl where it seems to be working.

[https://github.com/ytdl-org/youtube-dl/blob/98998cded6e179b35055177f75fc921d99ee5938/youtube_dl/extractor/youtube.py#L440](url)

Getting error below
```
[XCDYouTubeKit] Video operation finished with error: Sign in to confirm your age
Domain: XCDYouTubeVideoErrorDomain
Code:   150
User Info: {
    NSLocalizedDescription = "Sign in to confirm your age";
    NSURL = "https://www.youtube.com/get_video_info?el=detailpage&hl=en&ps=default&video_id=6kLq3WMV1nU";
}
```

**Comment by SoneeJohn** [comment]
Were you able to get that working with the latest version of `youtube-dl`. I might have to use the cookie feature in `XCDYouTubeKit` to get that working.

**Comment by nithin-george** [comment]
Hi @SoneeJohn Yeah probably thats why. But how does youtube-dl work without any log in? Pretty weird unless its using some defaults. Any examples on how to use the cookie feature. Thanks

**Comment by SoneeJohn** [comment]
Working on a fix so you can do this without needing cookies.
