### ISSUE TITLE
HTTP ERROR 403

### ISSUE THREAD

**Issue by xingzhi** [0xced/XCDYouTubeKit#432]
sometimes, Analyzed download link gives response "HTTP ERROR 403 occurs"

**Comment by SoneeJohn** [comment]
Can you give me a URL that displays this issue?

**Comment by xingzhi** [comment]
https://www.youtube.com/watch?v=qS6F64mj6LY

**Comment by xingzhi** [comment]
> Can you give me a URL that displays this issue?

https://www.youtube.com/watch?v=qS6F64mj6LY

**Comment by xingzhi** [comment]
> > Can you give me a URL that displays this issue?
> 
> https://www.youtube.com/watch?v=qS6F64mj6LY

thanks, 2.7.5 fix this issue

**Comment by xingzhi** [comment]
> Can you give me a URL that displays this issue?



> Can you give me a URL that displays this issue?

thanks, 2.7.5 fix this issue
