### ISSUE TITLE
Cannot play video 

### ISSUE THREAD

**Issue by xcd247** [0xced/XCDYouTubeKit#436]
Video playback error. This video is unavailable XCDYoutubeVideoErrorDomain (150)

**Comment by JonJC** [comment]
I'm getting same on any video I attempt to play. I'm using 2.7.6

**Comment by SoneeJohn** [comment]
@JonJC What video ID and did you clean you build folder?

**Comment by JonJC** [comment]
@Soneé John<mailto:notifications@github.com> -  here's a example:

"BUOxIO2Fx1Q"

but it's happening on all videos I've tried over last week

Yes, I've done a Clean Build Folder.


________________________________

**Comment by JonJC** [comment]
Sorry - my bad, I've fixed it.
My carthage was old, and was not building XCD properly.
