### ISSUE TITLE
VEVO videos can't be played

### ISSUE THREAD

**Issue by sycode** [0xced/XCDYouTubeKit#437]
[XCDYouTubeKit] No signature function in player script
[XCDYouTubeKit] Video operation finished with error: 
Domain: XCDYouTubeVideoErrorDomain
Code:   150

**Comment by sycode** [comment]
Thank you for confirming.
I fixed the code(fix regex expression) but the app crashed.

> *** Terminating app due to uncaught exception 'NSRangeException', reason: '-[__NSCFString substringWithRange:]: Range {9223372036854775807, 0} out of bounds; string length 1169095'

**Comment by emrecelikors** [comment]
There are 3 commits that passed by SoneeJohn. Did you implement all of them ?

**Comment by sycode** [comment]
After fixing the regular expression, I applied 4 commits and it worked fine.
Thank you so much!
