### ISSUE TITLE
Could you please add pod 2.7.7

### ISSUE THREAD

**Issue by dlpigpen** [0xced/XCDYouTubeKit#439]
There was a release for version 2.7.7 but cocoapod is in v2.7.6. Could you please release it too on the Cocoapod?

**Comment by MehmetSait** [comment]
++

**Comment by SoneeJohn** [comment]
The pod is currently at 2.7.7 (https://github.com/CocoaPods/Specs/blob/master/Specs/7/d/3/XCDYouTubeKit/2.7.7/XCDYouTubeKit.podspec.json)

Can I see your pod file?

**Comment by dlpigpen** [comment]
Thank You. Now it works.
