### ISSUE TITLE
XCDYouTubeVideoErrorDomain

### ISSUE THREAD

**Issue by MehmetSait** [0xced/XCDYouTubeKit#440]
hi all 
i have an error, Error Domain=XCDYouTubeVideoErrorDomain Code=-2 "(null)" 

how can i fixe it

**Comment by MehmetSait** [comment]
hi,
sometimes play, sometimes don't play video, this is so interesting.  videoId is 2lEkmTycteI

**Comment by leftyfl1p** [comment]
Also receiving this on a lot of videos that have tagged music in them.

**Comment by thejogsa** [comment]
Hi Getting same problem from this library. Is there any solution ?
**Error Domain=XCDYouTubeVideoErrorDomain Code=-2 "(null)"**

**Comment by whereiswhere** [comment]
I received this bug too, just from yesterday. it seems affect all the videos.

**Comment by leftyfl1p** [comment]
This issue is fixed in 2.8.1 and should be closed.
