### ISSUE TITLE
Background playback is not working on iOS 12.2.x+

### ISSUE THREAD

**Issue by darkForestCat** [0xced/XCDYouTubeKit#442]
I note that background playback is not working on 12.2.Currently using the hack with checking when the app goes background to play the video after the pause, but sometimes it does not work properly and create a little pause.

`
@objc func playerStateChanged() {
        if currentVideoController.moviePlayer.playbackState == .interrupted {
             currentVideoController.moviePlayer.play()
        }
    }
`

**Comment by ivkuznetsov** [comment]
You should disable video track of currentItem of your AVPlayer right before getting to background and enable it back when you open the app. Then the video won’t be interrupted, and you won’t need the hack

**Comment by SoneeJohn** [comment]
Closed with v2.8.2
