### ISSUE TITLE
Error Domain=XCDYouTubeVideoErrorDomain Code=-2

### ISSUE THREAD

**Issue by MehmetSait** [0xced/XCDYouTubeKit#444]
hi, some videos some times play, some times can't play
error log is:   Error Domain=XCDYouTubeVideoErrorDomain Code=-2 "(null)" UserInfo={NSURL=https://www.youtube.com/get_video_info?el=detailpage&hl=en&ps=default&video_id=J8IamfOsmjY

**Comment by thedoubler** [comment]
It's because there's no data in key `url_encoded_fmt_stream_map` Might be a YouTube change?

**Comment by SoneeJohn** [comment]
What version of the library are you running?

**Comment by SoneeJohn** [comment]
![Screen Shot 2019-07-31 at 2 42 09 PM](https://user-images.githubusercontent.com/4827301/62238621-61987a00-b3a1-11e9-83a0-12d2697ab1d1.png)

**Comment by MehmetSait** [comment]
i use latest version(Version 2.7.8) sometimes working, but sometimes not work. especially when switching automatically like youtube.

**Comment by thedoubler** [comment]
> i use latest version(Version 2.7.8) sometimes working, but sometimes not work. especially when switching automatically play like youtube.

Downloading, I guess is same for playing, for some video works and other don't, on latest version

**Comment by thejogsa** [comment]
Hi Getting same problem from this library. Is there any solution ?
**Error Domain=XCDYouTubeVideoErrorDomain Code=-2 "(null)"**

Video operation finished with error: The operation couldn’t be completed. (XCDYouTubeVideoErrorDomain error -2.)
Domain: XCDYouTubeVideoErrorDomain
Code: -2
User Info: {
NSURL = "https://www.youtube.com/get_video_info?el=detailpage&hl=en&ps=default&video_id=x4YPZxmoKDs";
}

**Comment by SoneeJohn** [comment]
@thejogsa Please show me your full console output when you got this error.

**Comment by huahua0521** [comment]
Hi~I had the same problem in version 2.7.4 ~
video_id=1wuOie3jvfA ,and here is my console...

 [XCDYouTubeKit] No signature function in player script
 [XCDYouTubeKit] Video operation finished with error: Unable to complete the assignment。（XCDYouTubeVideoErrorDomain error -2 。）
Domain: XCDYouTubeVideoErrorDomain
Code:   -2
User Info: {
}
 [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C14.1:2][0x123b8c7a0] get output frames failed, state 8196
 [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C14.1:2][0x123b8c7a0] get output frames failed, state 8196
TIC Read Status [14:0x0]: 1:57
TIC Read Status [14:0x0]: 1:57

Is there any solution ?

**Comment by davydovct** [comment]
Same issue here. First I thought it was because the video I’ve tried to download was in 720 with 50 fps, but then I’ve tried others and they worked fine. Still can’t find the reason. 
You can test it with this video for example: NRFePM_flFI

PS: 360 quality displayed well, problem appears only in 720p

**Comment by yoasha** [comment]
Hi All,

I can see this issue is opened for quite some time. Any news about it?

I didn't have any issues up until today, and now, all of the sudden I keep getting "XCDYouTubeVideoErrorDomain error -2" (with empty User Info) for any youtube ID that I play (i.e. SUXWAEX2jlg). The error is returned when I call `[[XCDYouTubeClient defaultClient] getVideoWithIdentifier:completionHandler:]`

I am using the latest version downloaded directly from github.

Any help will be appreciated!

**Comment by dgsquare82** [comment]
> Hi All,
> 
> I can see this issue is opened for quite some time. Any news about it?
> 
> I didn't have any issues up until today, and now, all of the sudden I keep getting "XCDYouTubeVideoErrorDomain error -2" (with empty User Info) for any youtube ID that I play (i.e. SUXWAEX2jlg). The error is returned when I call `[[XCDYouTubeClient defaultClient] getVideoWithIdentifier:completionHandler:]`
> 
> I am using the latest version downloaded directly from github.
> 
> Any help will be appreciated!

The same issue happens to me just now. It's very tragic cause I've been using this library for my paid mobile service. Hope someone will figure this out asap. 😢

**Comment by ghislainleblanc** [comment]
I have it too since this morning (Sept 11 2019).

All videos are affected.

**Comment by chaocharleswang** [comment]
Fixed on youtube–dl

https://github.com/ytdl-org/youtube-dl/commit/bf1317d257d13188601c837c983830355c6203e5
________________________________
