### ISSUE TITLE
Can Youtube know that their video is playing from which bundle id?

### ISSUE THREAD

**Issue by mobileonekh** [0xced/XCDYouTubeKit#446]
Hi,
Will Youtube know that the video is playing from which bundle id(app_id)?
If youtube knows, than it'll disable its admob or block the video.

Thanks;

**Comment by gonzo-oin** [comment]
I think they can't know the app bundle id. The HTTP request made by the framework don't send this kind of information to YouTube. In fact, it use a [session configuration](https://github.com/0xced/XCDYouTubeKit/blob/33e9463aba099c047a26d984a80d37bec42c0639/XCDYouTubeKit/XCDYouTubeVideoOperation.m#L91) named "ephemeral" that is perfect to improve privacy according to [apple documentation](https://developer.apple.com/documentation/foundation/nsurlsessionconfiguration/1410529-ephemeralsessionconfiguration?language=objc).

You can also check the entire XCDYouTubeVideoOperation.m file by yourself to be sure.

**Comment by mobileonekh** [comment]
@gonzo-oin , Thank for your explanation.
Anyhow, I think Youtube know this via one way or the other because it blocked Admob on my app which use this library.

**Comment by darkForestCat** [comment]
@mobileonekh so AdMob has disabled advertising in the app that uses this library in august 2019?
