### ISSUE TITLE
Not work any more

### ISSUE THREAD

**Issue by chaocharleswang** [0xced/XCDYouTubeKit#447]
Not work any more

**Comment by chaocharleswang** [comment]
@SoneeJohn Please have a check. Thanks!

**Comment by chaocharleswang** [comment]
youtube–dl should have fixed it

https://github.com/ytdl-org/youtube-dl/commit/bf1317d257d13188601c837c983830355c6203e5

**Comment by SoneeJohn** [comment]
I am aware of the issue and I am working on a fix :-)
