### ISSUE TITLE
(String?) $R0 = “The operation couldn’t be completed. (XCDYouTubeVideoErrorDomain error -2.)

### ISSUE THREAD

**Issue by ghislainleblanc** [0xced/XCDYouTubeKit#448]
It looks like getVideoWithIdentifier isn't working since this morning (Sept 11 2019).

**Comment by chaocharleswang** [comment]
youtube–dl should have fixed it

https://github.com/ytdl-org/youtube-dl/commit/bf1317d257d13188601c837c983830355c6203e5
