### ISSUE TITLE
Error Domain=XCDYouTubeVideoErrorDomain Code=-2 "(null)")

### ISSUE THREAD

**Issue by letam245** [0xced/XCDYouTubeKit#449]
getVideoWithIdentifier not working, return video nil

![Screen Shot 2019-09-11 at 11 50 16 AM](https://user-images.githubusercontent.com/28547581/64725921-682f0c80-d48a-11e9-87f9-53083a7d1558.png)

when we can expect this to be fixed?

**Comment by SoneeJohn** [comment]
@letam245 fixed in v2.8.1
