### ISSUE TITLE
XCDYouTubeVideoPlayerViewController "Implementing deprecated class" Warning

### ISSUE THREAD

**Issue by joro1** [0xced/XCDYouTubeKit#450]
I've just this evening updated to version 2.8.1 (from 2.6.0) and am now getting the following warning:

XCDYouTubeVideoPlayerViewController.m
@implementation XCDYouTubeVideoPlayerViewController
Implementing deprecated class

Short of turning off or ignoring warnings in XCode can you please advise as to what I need to do to clear this warning? Thank you.

**Comment by joro1** [comment]
I do now see the issue -- XCDYouTubeVideoPlayerViewController inherits from the deprecated iOS MPMoviePlayerViewController class, i.e.:

@interface XCDYouTubeVideoPlayerViewController : MPMoviePlayerViewController

Should I just ignore the warning? (Or is there a way to clear the warning that I've missed?)
Thank you.

**Comment by whereiswhere** [comment]
I meet the same warning,

**Comment by simformsolutions** [comment]
It's a crashing app in iOS 13+ 
**Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'MPMoviePlayerViewController is no longer available. Use AVPlayerViewController in AVKit.'**

**Comment by SoneeJohn** [comment]
I silenced the warning in https://github.com/0xced/XCDYouTubeKit/commit/b12328732456196020e22f9f79e46ef692a7bf94

if you're targeting iOS 13.0+ do not use `XCDYouTubeVideoPlayerViewController` instead use `XCDYouTubeClient` or `XCDYouTubeVideoOperation`
