### ISSUE TITLE
Not working on iOS 13

### ISSUE THREAD

**Issue by Josuevm** [0xced/XCDYouTubeKit#451]
With the new Xcode update (version 11) is no longer working. I'm getting this error:

> 'NSInvalidArgumentException', reason: 'MPMoviePlayerViewController is no longer available. Use AVPlayerViewController in AVKit.'

I'm using 'XCDYouTubeKit', '~> 2.8.1'. Checking previous issues seems to be fixed on that version but it's not working.

**Comment by SoneeJohn** [comment]
I'll look into this

**Comment by SoneeJohn** [comment]
Are you getting that error when building the app with Xcode 11 or just the app is running?

**Comment by Josuevm** [comment]
When the app is running

**Comment by SoneeJohn** [comment]
Okay, you need `AVPlayerViewController` and `XCDYouTubeClient`. See my post here:

https://github.com/0xced/XCDYouTubeKit/issues/445#issuecomment-522670657

**Comment by Josuevm** [comment]
The problem is that I'm working with Ionic 3, so I can't use native code
