### ISSUE TITLE
Resolution ID error

### ISSUE THREAD

**Issue by dota2AndTI** [0xced/XCDYouTubeKit#454]
Assertion failure in -[XCDYouTubeVideoOperation handleConnectionSuccessWithData:response:requestType:], /Users/ivy/Desktop/workspace/*********/***********/Pods/XCDYouTubeKit/XCDYouTubeKit/XCDYouTubeVideoOperation.m:178
2019-10-16 08:45:07.851330+0800 **********[16586:1046306] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Failed to decode response from https://www.youtube.com/get_video_info?el=detailpage&hl=en&ps=default&video_id=ogalmk6K0zs (response.textEncodingName = (null), data.length = 0)'
*** First throw call stack:
(0x19905a98c 0x198d830a4 0x198f5cd1c 0x1993928f4 0x1007ae3e0 0x1007ae018 0x19c2712cc 0x19c281800 0x19941f61c 0x1993293d8 0x1994218a4 0x199329070 0x19942229c 0x199421d68 0x100dd9298 0x100dcac04 0x100dcd808 0x100dccc88 0x100ddc168 0x100ddca90 0x198d77f64 0x198d7aae0)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by SoneeJohn** [comment]
I wasn't able to reproduce this with the ID `ogalmk6K0zs`. That exception is thrown when the response data is empty.

**Comment by dota2AndTI** [comment]
NSAssert(responseString.length > 0, @"Failed to decode response from %@ (response.textEncodingName = %@, data.length = %@)", response.URL, response.textEncodingName, @(data.length));

**Comment by hannessolo** [comment]
Hi, I am having this issue too. The problem is that I am writing my app in Swift. This error throws an NSException, so this actually crashes the entire app, and I cannot catch the exception.

**Comment by hannessolo** [comment]
After updating to the latest version, I found that the app now no longer crashes, but the video is not loaded either. I will investigate further.

**Comment by KaranMehta3984** [comment]
@hannessolo 
any luck ?

**Comment by hannessolo** [comment]
> @hannessolo
> any luck ?

Unfortunately I can't remember, and don't work at the same job anymore.

**Comment by KaranMehta3984** [comment]
Thanks for ur response

**Comment by ipuntes** [comment]
You have to add &html5=1 at XCDYouTubeVideoOperation.m requests of the url https://www.youtube.com/get_video_info? . Just done and works fine. In the future, that file needs to be fixed by adding this.

**Comment by KaranMehta3984** [comment]
Thanks Buddy…..
