### ISSUE TITLE
Some youTube links not loading video.

### ISSUE THREAD

**Issue by NikKovIos** [0xced/XCDYouTubeKit#456]
Some links are returned, but not loaded. For example [this](https://r7---sn-gvnuxaxjvh-3ggl.googlevideo.com/videoplayback?expire=1573085312&ei=IAzDXbK8DZSs7QSnmp2oCg&ip=62.183.124.38&id=o-AEqdKBxnAe7KFL81mbiizKA3o4ahOcrVkL4qckkWMKxS&itag=22&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-gvnuxaxjvh-3ggl%2Csn-n8v7kn7l&ms=au%2Crdu&mv=m&mvi=6&pcm2cms=yes&pl=24&initcwndbps=646250&mime=video%2Fmp4&ratebypass=yes&dur=560.413&lmt=1495166132867568&mt=1573063573&fvip=15&fexp=23842630&c=WEB&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cmime%2Cratebypass%2Cdur%2Clmt&sig=ALgxI2wwRQIgDFnQBfvjV7su2QEGXDC0iQ57zw-yBnwEtEwLV7jbW-oCIQDURgkba_uhbXl_XKm8t3M3viJTNS8uPa-Mpv22MvfJpQ%3D%3D&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AHylml4wRgIhAIgK1DqbM9ex4J9cSjPmXfqBkJqtvuaN1_5lT68pEPN5AiEA37aGlCtUe2EJpLrpvoYwQOO0EqIzNsUv65ZUlKMKngQ%3D). https://www.youtube.com/watch?v=550S-6XVRsw
The 360p [link](https://r15---sn-n8v7kn7l.googlevideo.com/videoplayback?expire=1573085908&ei=dA7DXYX-I6KEv_IPyu-8-Ag&ip=62.183.124.38&id=o-ABqi50JH5KQxpjR5z8eAgmfEcve-EnN8aS2Wnj8s2hKH&itag=135&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=youtube&requiressl=yes&mime=video%2Fmp4&gir=yes&clen=69344090&dur=560.359&lmt=1495283370646857&fvip=15&keepalive=yes&fexp=23842630&c=WEB&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=ALgxI2wwRAIgZIBPQ7ar2wcNXhVgfvW_PVSFcwvXhmI_iU57P4MdCpECIAEJTbKkkJdvNwUlfEGoXQOpfWQSEZYKgFpk0Znvov4_&ratebypass=yes&redirect_counter=1&cm2rm=sn-gvnuxaxjvh-3ggl7k&req_id=8c72c6e90d46a3ee&cms_redirect=yes&mm=29&mn=sn-n8v7kn7l&ms=rdu&mt=1573064230&mv=m&mvi=14&pl=24&lsparams=mm,mn,ms,mv,mvi,pl&lsig=AHylml4wRgIhAP8NvtVcYfH5cI8d8YRJ95XtBz-dQXfosVUOwd2gBwgRAiEAsd1c6hxOsBgT9iD3q-djnYaKHuvxri1ID0OFK2HrHQU=) works well.

The problem with 720p video link only, so i created a workaround for this to fetch 360p video link in that case and in other case use 720p.

```
static func canPlay(url: URL) -> Bool {
        let asset = AVAsset(url: url)
        let length = Float(asset.duration.value) / Float(asset.duration.timescale)
        return length != 0.0
    }

static func getYouTubeURL(
        code: String,
        highQuality: Bool = true,
        completion: @escaping VideoServiceYouTubeLinkFetchHandler) {
        XCDYouTubeClient.default().getVideoWithIdentifier(code) { (video: XCDYouTubeVideo?, error: Error?) in
            guard let streamURLs = video?.streamURLs else { completion(nil); return }
            if highQuality {
                let streamURL = streamURLs[XCDYouTubeVideoQualityHTTPLiveStreaming]
                    ?? streamURLs[YouTubeVideoQuality.hd720]
                    ?? streamURLs[YouTubeVideoQuality.medium360]
                    ?? streamURLs[YouTubeVideoQuality.small240]
                completion(streamURL)
            } else {
                let streamURL = streamURLs[YouTubeVideoQuality.medium360]
                    ?? streamURLs[YouTubeVideoQuality.small240]
                completion(streamURL)
            }
        }
    }

VideoService.getYouTubeURL(code: code) { [weak targetViewController] url in
                if let u = url {
                    if canPlay(url: u) {
                        playerVC.player = AVPlayer(url: u)
                    } else {
                        VideoService.getYouTubeURL(code: code, highQuality: false) { [weak targetViewController] url in
                            if let u = url {
                                playerVC.player = AVPlayer(url: u)
                            } else {
                                targetViewController?.dismiss(animated: true, completion: nil)
                            }
                        }
                    }
                } else {
                    targetViewController?.dismiss(animated: true, completion: nil)
                }
            }
```

**Comment by tanphamanhh** [comment]
same issue here

**Comment by SoneeJohn** [comment]
Thanks! I will look into this!

**Comment by SoneeJohn** [comment]
For those wondering how to work around this please use the querying functionality in `XCDYouTubeKit` or `XCDYouTubeVideoQueryOperation`

Here is an example on how to use it (example also in the macOS demo)
```
[[XCDYouTubeClient defaultClient] getVideoWithIdentifier:@"" completionHandler:^(XCDYouTubeVideo *video, NSError *error) {
	
	if (video)
	{
	
		[[XCDYouTubeClient defaultClient] queryVideo:video cookies:nil completionHandler:^(NSDictionary * _Nonnull streamURLs, NSError * _Nullable streamError, NSDictionary<id,NSError *> * _Nonnull streamErrors)
		 {			
			if (streamURLs)
			{
				NSURL *url = streamURLs[XCDYouTubeVideoQualityHTTPLiveStreaming] ?: streamURLs[@(XCDYouTubeVideoQualityHD720)] ?: streamURLs[@(XCDYouTubeVideoQualityMedium360)] ?: streamURLs[@(XCDYouTubeVideoQualitySmall240)];
		
			}
			else
			{
				//Error
			}
		}];
	}
	else
	{
		//Error
	}
}];

```
