### ISSUE TITLE
MPMoviePlayerViewController

### ISSUE THREAD

**Issue by YangKunCheng** [0xced/XCDYouTubeKit#457]
2019-11-27 01:02:11.769952+0800 FitMe[12486:277665] Consumed extension
2019-11-27 01:02:12.443919+0800 FitMe[12486:277373] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'MPMoviePlayerViewController is no longer available. Use AVPlayerViewController in AVKit.'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23c4f02e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff50b97b20 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23c4ee6c +[NSException raise:format:] + 188
	3   MediaPlayer                         0x00007fff277e0c99 -[MPMoviePlayerViewController initWithContentURL:] + 94
	4   FitMe                               0x0000000100ba263f -[XCDYouTubeVideoPlayerViewController initWithVideoIdentifier:] + 495

iOS13

**Comment by SoneeJohn** [comment]
@YangKunCheng What version of the project you're using? The latest demo app no longer use `MPMoviePlayerViewController`

**Comment by abdelrahman-badary** [comment]
The library still have MPMoviePlayerViewController as the parent class of XCDYouTubeVideoPlayerViewController and the README clearly state to use XCDYouTubeVideoPlayerViewController so i think this should still be open i am using the latest release `2.14`

**Comment by SoneeJohn** [comment]
@abdelrahman-badary if you're targeting iOS 8 or later it's best to use `XCDYouTubeClient` and `AVPlayerViewController` the `README` has an example on how you can go about doing this :-)
