### ISSUE TITLE
getVideoWithIdentifier always returns error code -2

### ISSUE THREAD

**Issue by MhmdSalah** [0xced/XCDYouTubeKit#458]
Starting yesterday i noticed that XCDYouTubeKit fails and returns error code -2
i tried multiple videos with no success.

**Comment by rajugautam** [comment]
Happening with me too. Looks like some YouTube changes are stopping from getting stream urls.

**Comment by SoneeJohn** [comment]
@MhmdSalah Please give me an identifier that is causing you issues.

**Comment by den-zv** [comment]
Facing the same problem.
I believe you can try any ID to debug that. E. g. `cfOa1a8hYP8`, it gives me an error mentioned above.

**Comment by SoneeJohn** [comment]
@den-zv  Are you using the latest version of library. I am able to play `cfOa1a8hYP8`

![Screen Shot 2020-01-23 at 1 48 44 AM](https://user-images.githubusercontent.com/4827301/72959938-81be5a00-3d82-11ea-8ca9-dce44bf1ac35.png)

**Comment by cristea2017** [comment]
i use pod "XCDYouTubeKit", "~> 2.8.2" and not fails :)  maybe video is private or have restriction ...

**Comment by antonvilyams** [comment]
Yes, just update the library to the latest version.

**Comment by demistry** [comment]
Still have the same problem with a lot of video IDs including this XW6JBwv4lig

**Comment by demistry** [comment]
And i have updated to 2.8.2 seems youtube did some sort of restriction on video streaming...
