### ISSUE TITLE
AVPlayer error on some (music) videos

### ISSUE THREAD

**Issue by CWftw** [0xced/XCDYouTubeKit#459]
I am getting this error when trying to play Rap God (https://www.youtube.com/watch?v=XbGs_qK2PQA):

AVPlayer Error: Localized Description: Cannot Open; Domain: AVFoundationErrorDomain; Code: -11828

It doesn't seem to be all videos yet, but is this related to the issues YouTube-DL are having today?
https://github.com/ytdl-org/youtube-dl/issues/23819

**Comment by SoneeJohn** [comment]
@CWftw Thanks! This issue should be fixed in the latest version of the library.
