### ISSUE TITLE
Additional patterns in XCDYouTubePlayerScript

### ISSUE THREAD

**Issue by Nikitos9I** [0xced/XCDYouTubeKit#463]
Hello!

Many of those who use your library sometimes encounter a problem when YouTube updates its patterns (it takes time until you update the library, until we pull up the changes, and until Apple approves a new version of our app: all this time, users will not play videos from YouTube)

We have the ability to pull up these patterns from the server without updating the application

As a solution I can offer this option: add a new parameter **additionalPatterns** to the XCDYouTubePlayerScript file in the initialiser and use them if they are non-nil. Else use your hardcoded patterns.

I hope for a quick response and cooperation.
Best regards,
Nikita Savinov

**Comment by SoneeJohn** [comment]
I was thinking of doing something similar. It was actually planned in https://github.com/0xced/XCDYouTubeKit/issues/199

Would you mind opening a pull request to add this?

**Comment by Nikitos9I** [comment]
> I was thinking of doing something similar. It was actually planned in #199
> 
> Would you mind opening a pull request to add this?

Yea, I will do it

**Comment by CWftw** [comment]
This was a greatly needed feature. Thank you!
