### ISSUE TITLE
Parse Video Error!!!

### ISSUE THREAD

**Issue by oTranAnhMinh** [0xced/XCDYouTubeKit#465]
Hello,

Currently, some videos are limited by country. Please help to check it. 

Domain: XCDYouTubeVideoErrorDomain
Code:   -2
User Info: {
    AllowedCountries = "{(\n    \"United States\"\n)}";
    NSLocalizedDescription = "The uploader has not made this video available in your country.";
    NSURL = "https://www.youtube.com/get_video_info?eurl=https://youtube.googleapis.com/v/jOAoQO9UOHs&hl=en&sts=&video_id=jOAoQO9UOHs";
}

Thank you,

**Comment by SoneeJohn** [comment]
Are you in the United States?

**Comment by oTranAnhMinh** [comment]
> Are you in the United States?

No. I live in Vietnam. 
I have selected some VEVO videos with the region in the United States and occasionally receive this error.

**Comment by SoneeJohn** [comment]
Interesting. Well based on the error message that is why you're getting that error. What I suggest is using a VPN or proxy to change your IP to a US one and try again.
