### ISSUE TITLE
Not working anymore 

### ISSUE THREAD

**Issue by Red-Mak** [0xced/XCDYouTubeKit#467]
Hi,
Im using XCDYouTubeClient in my iOS and tvOS but from some days i noticed that i can’t get direct url to the video.

Could you please check, thanks :)

**Comment by gonzo-oin** [comment]
Hello @Red-Mak,
Did you test with the latest version `2.9.0` ?
Can you please share the URLs that don't work ?

**Comment by Red-Mak** [comment]
Thank you for the quick answer
here's alink that doesn't work : https://www.youtube.com/watch?v=JDcAlo8i2y8

**Comment by SoneeJohn** [comment]
Video plays fine on my end, please confirm you've updated to v2.9.0 and that you've cleaned you build folder.

<img width="592" alt="Screen Shot 2020-02-09 at 9 43 27 PM" src="https://user-images.githubusercontent.com/4827301/74115351-40e98200-4b85-11ea-9122-453ce6845590.png">

**Comment by Red-Mak** [comment]
not sure what happened, but i switch to use SPM instead of cocoapods and it works ..
