### ISSUE TITLE
XCDYouTubeVideoErrorDomain error -2

### ISSUE THREAD

**Issue by StevenKuo** [0xced/XCDYouTubeKit#468]
Could I know what did error mean?

[XCDYouTubeKit] Video operation finished with error: The operation couldn’t be completed. (XCDYouTubeVideoErrorDomain error -2.)
Domain: XCDYouTubeVideoErrorDomain
Code:   -2
User Info: {
}

**Comment by gonzo-oin** [comment]
This mean the URL you pass to XCDYouTubeKit is unavailable. Is your network restricted, could you share the code that used `XCDYouTubeKit` and maybe the video URL that cause the issue?

**Comment by SoneeJohn** [comment]
Can you let me know which version of the library you're using and the video identifier?

**Comment by StevenKuo** [comment]
I can get URL by the others video identifier correctly, the error only happened by specific one.

XCDYouTubeKit (2.8.3)
video identifier: cdqP6wI8TCc

**Comment by SoneeJohn** [comment]
@StevenKuo Thanks! I was able to reproduce this issue. I will look into it further

**Comment by SoneeJohn** [comment]
@StevenKuo The latest update should fix your issue, unfortunately, the video will have no audio. It appears YouTube is only serving itags that contain video only and no audio.
