### ISSUE TITLE
Full screen for swift - XCDYouTubeKit Demo/iOS Demo/AVPlayerViewControllerManager.swift not works

### ISSUE THREAD

**Issue by anveshfactorly** [0xced/XCDYouTubeKit#474]
Hello there

I have tried swift version of it and when i click on default icon of full screen video stop and shows black screen

Any solution ?

**Comment by SoneeJohn** [comment]
Hi, are you trying this on the simulator? I haven't add any issues like the one your described.

![Screen Shot 2020-04-06 at 7 32 30 AM](https://user-images.githubusercontent.com/4827301/78554221-c762be80-77d8-11ea-808a-e797ad26a365.png)

**Comment by cristea2017** [comment]
> Hello there
> 
> I have tried swift version of it and when i click on default icon of full screen video stop and shows black screen
> 
> Any solution ?

you can create own full screen using avplayerlayer
check this app: https://apps.apple.com/us/app/iburn-music-player-stream/id1506178737?ls=1
