### ISSUE TITLE
Apple Watch support

### ISSUE THREAD

**Issue by mobile-appz** [0xced/XCDYouTubeKit#481]
Is this library theoretically possible to port to use on Apple Watch for youtube audio streaming from the Apple Watch cellular connection without using an iphone at all?

**Comment by SoneeJohn** [comment]
Theoretically it could work (watchOS uses `AVAudioPlayer`) but because this library uses `JavaScriptCore` which isn't available on watchOS it won't build.

**Comment by mobile-appz** [comment]
> Theoretically it could work (watchOS uses `AVAudioPlayer`) but because this library uses `JavaScriptCore` which isn't available on watchOS it won't build.

Thanks
