### ISSUE TITLE
should have default lastError in XCDYouTubeVideoOperation

### ISSUE THREAD

**Issue by TerryHug2305** [0xced/XCDYouTubeKit#484]
[XCDYouTubeKit] Video operation finished with error: (null)
Domain: (null)
Code:   0
User Info: (null)
[7769:55767764] *** Assertion failure in -[XCDYouTubeClient getVideoWithIdentifier:cookies:customPatterns:completionHandler:], /Pods/XCDYouTubeKit/XCDYouTubeKit/XCDYouTubeClient.m:69
[7769:55767764] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Both `video` and `error` can not be nil if the operation was not canceled.

when all requests passed, no errors happened, Assert make app crash.  I think should add a default lastError, Can make this happen? thanks

**Comment by tungdangplus** [comment]
I sometimes get this issue too, then I try way:

XCDYouTubeClient.default().getVideoWithIdentifier(videoTrack.Id) { (xcdVideo, xcdError) in
       DispatchQueue.main.async {
            if (xcdVideo != nil) {
                XCDYouTubeClient.default().queryVideo(xcdVideo!, cookies: nil) { (streamURLs: [AnyHashable: Any]?, 
                streamError: Error?, streamErrors: [AnyHashable: Error]?) in 
                    if (streamURLs != nil) {
                          let url1: URL? = streamURLs?[XCDYouTubeVideoQuality.HD720.rawValue] as? URL
                    } else {
                         print(streamError)
                         print(streamErrors)
                    }
            } else {
                   print(xcdError!.localizedDescription)
            }
      }
}

So far I don't get that crash again

**Comment by fightveryexplosion** [comment]
I get this same error in the latest 2.14.1. It seems to be happening randomly, but it seems to happen quite often in my case.
A default error or something like it seems like a good idea! At the moment the app just crashes..

**Comment by euroboy** [comment]
Happens quite often to me too lately

**Comment by phuocmobytelab** [comment]
any fix for this issue?

**Comment by fragm** [comment]
This error occurs and the app crashes.
VideoIdentifier = VEI4TYQp9Is

**Comment by palsantosh** [comment]
This error occurs and the app crashes.
VideoIdentifier = xilDDRctnjw

**Comment by SoneeJohn** [comment]
> app crash. Any fix??
> VideoIdentifier = xilDDRctnjw

What version of the library are you using?

**Comment by palsantosh** [comment]
> > app crash. Any fix??
> > VideoIdentifier = xilDDRctnjw
> 
> What version of the library are you using?

I'm using version (2.14.1)

**Comment by SoneeJohn** [comment]
Please update to the latest version 2.15.0

**Comment by palsantosh** [comment]
> Please update to the latest version 2.15.0

Now its working!! Now I can play video successfully. Thanks!!

**Comment by topcoder917** [comment]
Should I update what library version?
you mean pod?
