### ISSUE TITLE
App Store Rejection

### ISSUE THREAD

**Issue by Frankenxtein** [0xced/XCDYouTubeKit#485]
An update to my App got rejected today. Here's the message sent by Apple.

> From Apple
> 5. 2.3 Legal: Intellectual Property - Audio/Video Downloading
> Guideline 5.2.3 - Legal
> 
> 
> Your app contains content or features that may violate the rights of one or more third parties. Specifically, your app provides potentially unauthorized access to third-party audio or video streaming, catalogs, and discovery services.
> 
> Your app and its contents should not infringe upon the rights of another party. In the event your app infringes another party’s rights, you are responsible for any liability to Apple because of a claim.
> 
> Next Steps
> 
> To resolve this issue, please attach documentary evidence in the App Review Information section in App Store Connect evidencing that you have all necessary rights or permissions to the third-party audio or video streaming, catalogs, and discovery services in your app.

Has anyone faced this issue lately? Is this because of the library? What solutions do anyone suggest?

**Comment by DmytroBrovkin** [comment]
Our app update was rejected with same response. We don’t use this library, but our app uses same mechanism of parsing YT streams. Looks like Apple has new validation guidelines for apps with Youtube content. We will have a call with review team in few days. I will post the results after.

**Comment by Frankenxtein** [comment]
Please don't forget to post the results.  Any idea where am i supposed to get the documentary evidence?

**Comment by Frankenxtein** [comment]
> Our app update was rejected with same response. We don’t use this library, but our app uses same mechanism of parsing YT streams. Looks like Apple has new validation guidelines for apps with Youtube content. We will have a call with review team in few days. I will post the results after.

Please don't forget to post the results afterwards, I have no idea where can i get the documentary evidence.

**Comment by Frankenxtein** [comment]
> Our app update was rejected with same response. We don’t use this library, but our app uses same mechanism of parsing YT streams. Looks like Apple has new validation guidelines for apps with Youtube content. We will have a call with review team in few days. I will post the results after.

@DmytroBrovkin did you manage to get a call with the app review team? Any specifics behind the rejection?

**Comment by DmytroBrovkin** [comment]
I still waiting for a call. They said in the message 3-5 business days, which ends this Friday. Will update as soon as have a call.

**Comment by oososo** [comment]
> I still waiting for a call. They said in the message 3-5 business days, which ends this Friday. Will update as soon as have a call.

Hello , Did you receive that call?

**Comment by DmytroBrovkin** [comment]
![CC1F908B-CBA5-4D43-8C6B-B948DAC8ED1E](https://user-images.githubusercontent.com/11684536/85048728-bbdd2d80-b161-11ea-81ad-71a7991e5d30.jpeg)

just got a reply today

**Comment by dlpigpen** [comment]
I had the same issue yesterday. Well, there seems have new guideline about streaming services API

**Comment by oososo** [comment]
> ![CC1F908B-CBA5-4D43-8C6B-B948DAC8ED1E](https://user-images.githubusercontent.com/11684536/85048728-bbdd2d80-b161-11ea-81ad-71a7991e5d30.jpeg)
> 
> just got a reply today

What would apple say? I hope your app will pass the review.If not, I want to know what 's the problem.

**Comment by MhmdSalah** [comment]
Does anybody know how can they detect the presence of this lib in the app? is there a way to hide it? They did not even open my app udpate (i am sure because i made the app crash upon initial run and they rejected for this reason) so there is some kind of a scan software that detects this lib. I tried: change all files names and class names. delete all comments. remove all mentions of youtube. 
If you guys can find something, please tell.

**Comment by darkForestCat** [comment]
There is an official way to present youtube video

> What would apple say? I hope your app will pass the review.If not, I want to know what 's the problem.

It is  not  the official way of presenting YouTube videos.Hmmmmm what could be the problem?))

**Comment by DmytroBrovkin** [comment]
Just had a quick chat with owners of Musi app. They have exactly same situation and can’t bypass the Apple Review. I think it is the end :)

**Comment by MhmdSalah** [comment]
Guys i have a suggestion. Apple can't be scanning every app individually by reverse engineering. We have to scrap this lib to make it harder for them to find it.

My suggestion is a pull request with the following changes:
- delete all .plist files, they are not hidden in ipa files during compilation
- change all .h and .m file names and class names, e.g. find and replace XCDYouTube to xStreamLib or someing
- delete all comments
- delete any mention of youtube in strings inside the lib, and change it to string variable with setters so we can grab these values from a remote link and set them in runtime
- there could be more ways to help, maybe change some stuff in .h files to scrap their look after compilation 

If anybody is able to make this change, maybe it will be very easy to test by someone and then we can find a solution for everybody.

**Comment by DmytroBrovkin** [comment]
> Guys i have a suggestion. Apple can't be scanning every app individually by reverse engineering. We have to scrap this lib to make it harder for them to find it.
> 
> My suggestion is a pull request with the following changes:
> 
> * delete all .plist files, they are not hidden in ipa files during compilation
> * change all .h and .m file names and class names, e.g. find and replace XCDYouTube to xStreamLib or someing
> * delete all comments
> * delete any mention of youtube in strings inside the lib, and change it to string variable with setters so we can grab these values from a remote link and set them in runtime
> * there could be more ways to help, maybe change some stuff in .h files to scrap their look after compilation
> 
> If anybody is able to make this change, maybe it will be very easy to test by someone and then we can find a solution for everybody.

We don’t use this library, and still blocked. Renaming files won’t help.

**Comment by MhmdSalah** [comment]
> We don’t use this library, and still blocked. Renaming files won’t help.

Then your code has something in common with this lib. Could you please check if your code mentions any of these links in a string:
-https://www.youtube.com/get_video_info
-https://www.googleapis.com/youtube/
-https://developers.google.com/youtube/

**Comment by darkForestCat** [comment]
> > Guys i have a suggestion. Apple can't be scanning every app individually by reverse engineering. We have to scrap this lib to make it harder for them to find it.
> > My suggestion is a pull request with the following changes:
> > 
> > * delete all .plist files, they are not hidden in ipa files during compilation
> > * change all .h and .m file names and class names, e.g. find and replace XCDYouTube to xStreamLib or someing
> > * delete all comments
> > * delete any mention of youtube in strings inside the lib, and change it to string variable with setters so we can grab these values from a remote link and set them in runtime
> > * there could be more ways to help, maybe change some stuff in .h files to scrap their look after compilation
> > 
> > If anybody is able to make this change, maybe it will be very easy to test by someone and then we can find a solution for everybody.
> 
> We don’t use this library, and still blocked. Renaming files won’t help.

do you use the official way of showing YouTube videos?

**Comment by Frankenxtein** [comment]
> Just had a quick chat with owners of Musi app. They have exactly same situation and can’t bypass the Apple Review. I think it is the end :)


Did Apple call you? What did the Apple representative say?

**Comment by Frankenxtein** [comment]
> > > Guys i have a suggestion. Apple can't be scanning every app individually by reverse engineering. We have to scrap this lib to make it harder for them to find it.
> > > My suggestion is a pull request with the following changes:
> > > 
> > > * delete all .plist files, they are not hidden in ipa files during compilation
> > > * change all .h and .m file names and class names, e.g. find and replace XCDYouTube to xStreamLib or someing
> > > * delete all comments
> > > * delete any mention of youtube in strings inside the lib, and change it to string variable with setters so we can grab these values from a remote link and set them in runtime
> > > * there could be more ways to help, maybe change some stuff in .h files to scrap their look after compilation
> > > 
> > > If anybody is able to make this change, maybe it will be very easy to test by someone and then we can find a solution for everybody.
> > 
> > 
> > We don’t use this library, and still blocked. Renaming files won’t help.
> 
> do you use the official way of showing YouTube videos?

The Official player is based on javascript i think and defies the purpose of this library.

**Comment by darkForestCat** [comment]
> > do you use the official way of showing YouTube videos?
> 
> The Official player is based on javascript i think and defies the purpose of this library.

"We don’t use this library, and still blocked. Renaming files won’t help." - He sad that he does not use this library, so I  was curious  what YouTube library does he use.

**Comment by DmytroBrovkin** [comment]
We’ve created our own library in Swift, based on youtube-dl python code.

**Comment by darkForestCat** [comment]
Try using official library

**Comment by cujo30227** [comment]
I’m using using the official implementation in my app https://developers.google.com/youtube/v3/guides/ios_youtube_helper  
Received the same rejection today, and appealing it now ..

**Comment by darkForestCat** [comment]
@cujo30227  let us know please how would go the process.

**Comment by rockylive** [comment]
please update this issue asap you get a reply. Thanks

**Comment by DmytroBrovkin** [comment]
just had a call with apple. Basically, they don’t really care what API you use to playback content from Youtube. They need a  legal document from Google, that would confirm your app can stream their content. This applies to all content providers like Youtube, Soundcloud, Vmeo etc. 
![7AC61A74-C0CD-45FC-A8CE-0F33283AA4F4](https://user-images.githubusercontent.com/11684536/85330967-421bab80-b4a3-11ea-92f3-f29a4ade647c.jpeg)

**Comment by DmytroBrovkin** [comment]
![270C988F-6EFD-41B9-829D-44E53DB19B61](https://user-images.githubusercontent.com/11684536/85331140-945ccc80-b4a3-11ea-9864-3784e3f03d05.jpeg)

**Comment by Frankenxtein** [comment]
> just had a call with apple. Basically, they don’t really care what API you use to playback content from Youtube. They need a legal document from Google, that would confirm your app can stream their content. This applies to all content providers like Youtube, Soundcloud, Vmeo etc.

Where the hell am i going to get that document. A large company like give won't give a damn about some tiny app developer. :)

**Comment by kdk0** [comment]
Uh... Does this mean any app that shows embedded Youtube video now needs to submit some legal document from Youtube?

**Comment by theirfanshah** [comment]
Hello,

I'm also facing same rejection, I replied Apple Review Team in Resolution Center, and got replied today, and yes they are asking for documentary evidence.

Reply from Apple:

`Hello,

Thank you for your response.

During our review we have found that your app provides a curated list of YouTube videos that users can watch and listen to. We understand that the YouTube API is public, however the App Store Review Guidelines state that you need to provide documentation that demonstrates that you have permission to stream the videos.

To resolve this issue, please attach documentary evidence in the App Review Information section in App Store Connect evidencing that you have all necessary rights or permissions to the third-party audio or video streaming, catalogs, and discovery services in your app.

Best regards,

App Store Review`

How can I get document from YouTube, and why they will provide document to individuals ?

**Comment by huynguyencong** [comment]
I have the same problem. Does anyone know how to find the document that Apple require?

**Comment by MhmdSalah** [comment]
Hello again everybody,
I can confirm, removing this lib and submitting got the new version approved, but it took apple one full week of "in review" time to get it approved. If i had to guess, i think they are doing some kind of de compiling to investigate the app, and they make the review process longer to investigate thoroughly.

**Comment by huynguyencong** [comment]
> Hello again everybody,
> I can confirm, removing this lib and submitting got the new version approved, but it took apple one full week of "in review" time to get it approved. If i had to guess, i think they are doing some kind of de compiling to investigate the app, and they make the review process longer to investigate thoroughly.

@MhmdSalah it means you have to remove Youtube feature from your app? If so, it is not a solution for this issue.

**Comment by MhmdSalah** [comment]
> > Hello again everybody,
> > I can confirm, removing this lib and submitting got the new version approved, but it took apple one full week of "in review" time to get it approved. If i had to guess, i think they are doing some kind of de compiling to investigate the app, and they make the review process longer to investigate thoroughly.
> 
> @MhmdSalah it means you have to remove Youtube feature from your app? If so, it is not a solution for this issue.

Nope! i managed to create a solution. As of now, my solution is not as good as having this lib inside the guts of my app, but it is working. It will not be suitable for every app because my app is a special condition. Best of luck to you.

**Comment by chaocharleswang** [comment]
> > > Hello again everybody,
> > > I can confirm, removing this lib and submitting got the new version approved, but it took apple one full week of "in review" time to get it approved. If i had to guess, i think they are doing some kind of de compiling to investigate the app, and they make the review process longer to investigate thoroughly.
> > 
> > 
> > @MhmdSalah it means you have to remove Youtube feature from your app? If so, it is not a solution for this issue.
> 
> Nope! i managed to create a solution. As of now, my solution is not as good as having this lib inside the guts of my app, but it is working. It will not be suitable for every app because my app is a special condition. Best of luck to you.

Were you requested to provide some documents proof? How did you reply? Thx.

**Comment by darkForestCat** [comment]
> > > Hello again everybody,
> > > I can confirm, removing this lib and submitting got the new version approved, but it took apple one full week of "in review" time to get it approved. If i had to guess, i think they are doing some kind of de compiling to investigate the app, and they make the review process longer to investigate thoroughly.
> > 
> > 
> > @MhmdSalah it means you have to remove Youtube feature from your app? If so, it is not a solution for this issue.
> 
> Nope! i managed to create a solution. As of now, my solution is not as good as having this lib inside the guts of my app, but it is working. It will not be suitable for every app because my app is a special condition. Best of luck to you.

So are you using  official YouTube library?And how  did you managed documentation problem?

**Comment by jlott1** [comment]
I have not updated my app since these new changes by Apple but I plan on pushing an update this week.  I may get the same response.  Just FYI,  I did get a similar rejection from Apple before and all I had to do was mention that I was a part of the Google Developer Program for developing for YouTube API and provided my Google Client ID as proof.   That's what worked for me in the past, but I'll let you know what happens after my next update.

**Comment by kdk0** [comment]
I was approved a few days ago with this library included in my app. I think maybe it depends on each reviewer...

**Comment by chaocharleswang** [comment]
Are your app approved for the first submission?
________________________________

**Comment by kdk0** [comment]
Yeah it was first submission.

**Comment by darkForestCat** [comment]
> I was approved a few days ago with this library included in my app. I think maybe it depends on each reviewer...

maybe  it  depends on the type of the  app...

**Comment by oososo** [comment]
> > I was approved a few days ago with this library included in my app. I think maybe it depends on each reviewer...
> 
> maybe it depends on the type of the app...

what 's the type of your app?

**Comment by kdk0** [comment]
Mine is shopping info app - https://apps.apple.com/us/app/pebble-fun-beauty-shopping/id1519076154

**Comment by huynguyencong** [comment]
> Mine is shopping info app - https://apps.apple.com/us/app/pebble-fun-beauty-shopping/id1519076154

Yeah, I think only streaming app is rejected by Apple. Your app is shoping app, although it uses this library, but streaming is not the main function.

**Comment by darkForestCat** [comment]
Is anyone who has passed the review process and has sent the documents to the App Review Team?

**Comment by Frankenxtein** [comment]
> I have not updated my app since these new changes by Apple but I plan on pushing an update this week. I may get the same response. Just FYI, I did get a similar rejection from Apple before and all I had to do was mention that I was a part of the Google Developer Program for developing for YouTube API and provided my Google Client ID as proof. That's what worked for me in the past, but I'll let you know what happens after my next update.

Was your update approved?

**Comment by fightveryexplosion** [comment]
Has anyone been able to get your apps approved since?

I'm going to have to update soon because of the recent YouTube changes, and am not looking forward to facing this rejection...

**Comment by perepechin** [comment]
I don't use this library, but I am also using embedded YouTube videos in my app for about 2-3 months, and my latest app updated was rejected by Apple because of the same reason today - "5. 2.3 Legal: Intellectual Property - Audio/Video Downloading". My app doesn't allow to download videos, but the second part of 5.2.3 also includes "streaming". This is pain.. I will provide an update here if I find a solution.

> 5.2.3 Audio/Video Downloading: Apps should not facilitate illegal file sharing or include the ability to save, convert, or download media from third-party sources (e.g. Apple Music, YouTube, SoundCloud, Vimeo, etc.) without explicit authorization from those sources. **Streaming of audio/video content may also violate Terms of Use, so be sure to check before your app accesses those services.** Documentation must be provided upon request.

**Comment by perepechin** [comment]
I didn't find a solution at this point, and decided to completely remove YouTube features from my iOS app. I don't have any issues with the same app in the Google Play. for example, in my case, the app was rejected even when I removed ability to play YouTube videos via YouTube IFrame API directly inside the app, but I was still displaying the video thumbnails in my app. so now I don't display thumbnails, and I don't allow to play video inside the app via YouTube IFrame API (btw this way we can play only videos for which "Allow Embedding" is set to Yes, and I still don't know how this breaks 5.2.3 section of their guidance), and I only provide a link to YouTube video, because playing videos is not a main thing in my app, so this is not a big issue in my case, but I still cannot agree with these things and I still want to find a nice solution. 

for example, I see that Twitter embeds videos without any issues, and it is unclear why the same things cannot be implemented in other apps.

if "Allow Embedding" is set to Yes for a video - this video can be embedded on the 3rd party sites and apps without any permissions from the author of the user, see "YouTube Video Permission and Rights" section in [Embedded YouTube Videos and Copyright Infringement](https://turbofuture.com/internet/Embed-YouTube-Videos---Copyright-Infringement) article 

if you sell your app and YouTube integration is main selling point - in that case it is very possible that these things are not allowed, but in my case all YouTube features are available even in the free version of the app, and I don't display any ads in my app as well :/

**Comment by perepechin** [comment]
btw I think that this issue can be closed, because it doesn't relate to this XCDYouTubeKit player and even if this player will start using YouTube IFrame API it will not help at all :/

**Comment by perepechin** [comment]
fun tweets for this topic:
https://twitter.com/tN023/status/1291497973394935809?s=20 and https://twitter.com/PhilLB1239/status/1291503688528388098?s=20

**Comment by perepechin** [comment]
I found this article [Complying with YouTube's Developer Policies](https://developers.google.com/youtube/terms/developer-policies-guide) and in this article I found info that it is possible to apply for an [API Compliance Audit](https://support.google.com/youtube/contact/yt_api_form).

I didn't try to apply for an API Compliance Audit, but I am going to do this, and then I will let you know the results.

**Comment by jlott1** [comment]
> Hello,
> 
> I'm also facing same rejection, I replied Apple Review Team in Resolution Center, and got replied today, and yes they are asking for documentary evidence.
> 
> Reply from Apple:
> 
> `Hello,
> 
> Thank you for your response.
> 
> During our review we have found that your app provides a curated list of YouTube videos that users can watch and listen to. We understand that the YouTube API is public, however the App Store Review Guidelines state that you need to provide documentation that demonstrates that you have permission to stream the videos.
> 
> To resolve this issue, please attach documentary evidence in the App Review Information section in App Store Connect evidencing that you have all necessary rights or permissions to the third-party audio or video streaming, catalogs, and discovery services in your app.
> 
> Best regards,
> 
> App Store Review`
> 
> How can I get document from YouTube, and why they will provide document to individuals ?

I would suggest that you that keep disputing their rejection and show them the google developers TOS.  
https://developers.google.com/terms

**Comment by denkeni** [comment]
> I would suggest that you that keep disputing their rejection and show them the google developers TOS.  
> 
> https://developers.google.com/terms

No, it would not work. Even the App Review Board rejected my appeal with Google Developers TOS presented. 

Still in the process of YouTube's API Compliance Audit mentioned above, and it looks promising as the solution.

**Comment by SoneeJohn** [comment]
> btw I think that this issue can be closed, because it doesn't relate to this XCDYouTubeKit player and even if this player will start using YouTube IFrame API it will not help at all :/

I am going to leave this open for the time being because I believe it provides useful information to those who might be use this library in an app they plan to publish on the App Store.

**Comment by endavid** [comment]
I submitted a game and I do not use any streaming services and my app got rejected because of this Guideline 5.2.3 as well. I suspect it's because I have a WebView in the game to look up word definitions (it's a word puzzle game). I've set `NSAllowsArbitraryLoads` to `false`, under `NSAppTransportSecurity` in the `Plist.info` file, and whitelisted the sites that I used for definitions, but I got rejected again. One of the whitelisted sites is [Google Translate](https://translate.google.com/). I suspect it has to do with Google URLs, but I'm trying things blindly unless they aren't more explicit.

I have 3 games using exactly the same sites and they didn't get rejected. I do not stream any audio or video, so this is really frustrating. I left a message to Apple after the last rejection asking if they could explain exactly what's wrong, but who knows when they reply.

**Comment by Frankenxtein** [comment]
> I found this article [Complying with YouTube's Developer Policies](https://developers.google.com/youtube/terms/developer-policies-guide) and in this article I found info that it is possible to apply for an [API Compliance Audit](https://support.google.com/youtube/contact/yt_api_form).
> 
> I didn't try to apply for an API Compliance Audit, but I am going to do this, and then I will let you know the results.

This library clearly violates YouTube TOS as it does not use the official iFrame player as recommended by google, i do not think google will approve the api compliance audit?

**Comment by denkeni** [comment]
> @denkeni How did the YouTube API Compliance Audit approach go? Anything new you might want to share.

Unfortunately, after finishing the process, the YouTube API Compliance Team only suggested going to https://support.google.com. It turned out that process only deals with YouTube API Quota extension.

**This issue exists even if you're using the official YouTube SDK**. And Apple insisted that every third-party service should only be used in your app with explicit legal authorization. 😕

I encourage anyone here to leave a comment on https://github.com/youtube/youtube-ios-player-helper/issues/399, the same issue on the official YouTube SDK. Or anyone who found the way to contact YouTube Legal for such authorization would share their experience.

**Comment by OutRunner** [comment]
I really hope Apple aren't going to prevent the use of this library, I have an Apple TV app that uses it and since Apple TV doesn't have a web browser I can't use the JS library or iframe...

**Comment by fangyuxi** [comment]
I also used this SDK to publish several apps that can play Youtube videos.
If the download feature is not provided, and the video is only played online, although this is not in compliance with the  Youtube Terms, it will be allowed by Apple's review.
You just can't include download feature.

@Frankenxtein @DmytroBrovkin

**Comment by Frankenxtein** [comment]
> I also used this SDK to publish several apps that can play Youtube videos.
> If the download feature is not provided, and the video is only played online in your app, although this is not in compliance with the Youtube Terms, it will be allowed by Apple's review.
> You just can't include download feature.
> 
> @Frankenxtein @DmytroBrovkin

When was the last time you pushed an update using this SDK? AFAIK, this rejection started only 4 or 5 months back only.

My app have don't have any download feature whatsoever. Could it be that the buffering of video is giving the impression of downloading to the reviewer? As, the video is likely to keep up playing, unless the buffer is empty even when WiFi/Cellular data is turned off?

**Comment by fangyuxi** [comment]
@Frankenxtein  Last Month

I have been developing such apps for several years. As long as the download featured is not included, it may always pass Apple's review normally. Has it started to require a contract for online video in the past month?

**Comment by Frankenxtein** [comment]
> @Frankenxtein Last Month
> 
> I have been developing such apps for several years. As long as the download featured is not included, it may always pass Apple's review normally. Has it started to require a contract for online video in the past month?

My update was rejected 3x, with the same reason as mentioned on the beginning of this thread. Like i said, there is no download feature in my app.

**Comment by fangyuxi** [comment]
@Frankenxtein 

I just checked the guide. Apple updated the 5.2.3  and added a new line: playing online videos may also require a contract. This line was not included before.

**Comment by diepox** [comment]
What about this app (SnapTube): 
[https://apps.apple.com/az/app/snaptube-lite/id1516145474
](https://apps.apple.com/az/app/snaptube-lite/id1516145474
)
It has even the video **DOWNLOADING** option, and yeah from **Youtube**!

App Review Team is drunk 🥴

**Comment by fangyuxi** [comment]
@diepox This is incredible, even the screenshot of this app is from Android.

**Comment by jlott1** [comment]
> > I would suggest that you that keep disputing their rejection and show them the google developers TOS.
> 
> No, it would not work. Even the App Review Board rejected my appeal with Google Developers TOS presented.
> 
> Still in the process of YouTube's API Compliance Audit [mentioned above](https://github.com/0xced/XCDYouTubeKit/issues/485#issuecomment-670421824), and it looks promising as the solution.

Try this link then.
 https://developers.google.com/youtube/terms/api-services-terms-of-service

I've been app reviewed many times.  
One rule about using YouTube videos was that I needed to make sure there was a  YouTube link overlaid on the video that points to the original content that can be played in a browser.  You also cannot display ads over YouTube content or make money off of the content itself but can make money from other features that are not tied to the content.  You may have already done this.  But if you have a Google developers ID then you are allowed use of YouTube API services through those terms of service.  YouTube would not give developers access to their video API unless they wanted you to play their videos (go here and search for "embed" https://www.youtube.com/t/terms) .   But the iFrame player is very buggy and hasn't been maintained in years.

I hope this information helps in some way.

**Comment by denkeni** [comment]
> Try this link then.
> https://developers.google.com/youtube/terms/api-services-terms-of-service
> 
> I've been app reviewed many times.

I have tried that link too, and it didn't work. App Review has made it clear that they want legal documentary evidence of authorization.

My app has been on the App Store for over 2 years, with many updates passed. Still get this rejection recently. Another example is [Movist](https://mjtsai.com/blog/2019/05/27/movist-removed-from-the-mac-app-store/).

One of the misery of App Store Review is that, **even if you get passed this time, it doesn't mean you're doing right**. It's just they don't care about it *this time*. App Store Review may just look at your app and reject it in any future updates, for the reason they care.

**Comment by trial** [comment]
I passed the app review.
1.I did not mention capability of youtube play function
2. a lot of apps are submitted for iOS 14 update, so maybe the review is  cursory.

**Comment by tungdangplus** [comment]
> I passed the app review.
> 1.I did not mention capability of youtube play function
> 2. a lot of apps are submitted for iOS 14 update, so maybe the review is cursory.

Can you give the link to your app pls.

**Comment by Brookes1r** [comment]
I got rejected  and passed after I challenged there rejection.

**Comment by darkness51** [comment]
@Brookes1r what did you argument to challenge the rejection?

**Comment by baptisteArno** [comment]
@Brookes1r +1, what was your arguments?

**Comment by alanwjlu** [comment]
@Brookes1r +1 what was your arguments?

**Comment by denkeni** [comment]
I've confirmed that App Store Review has revised their internal policy to approve 3rd party apps for YouTube streaming, just give them [YouTube API Services Terms of Service](https://developers.google.com/youtube/terms/api-services-terms-of-service). More details here: https://github.com/youtube/youtube-ios-player-helper/issues/399#issuecomment-867539604

**Comment by leevinh3291** [comment]
> I've confirmed that App Store Review has revised their internal policy to approve 3rd party apps for YouTube streaming, just give them [YouTube API Services Terms of Service](https://developers.google.com/youtube/terms/api-services-terms-of-service). More details here: [youtube/youtube-ios-player-helper#399 (comment)](https://github.com/youtube/youtube-ios-player-helper/issues/399#issuecomment-867539604)

@denkeni just tried but no luck. Review team still rejects my app even i put Youtube ToS in review note. :(

**Comment by deckameron** [comment]
> > I've confirmed that App Store Review has revised their internal policy to approve 3rd party apps for YouTube streaming, just give them [YouTube API Services Terms of Service](https://developers.google.com/youtube/terms/api-services-terms-of-service). More details here: [youtube/youtube-ios-player-helper#399 (comment)](https://github.com/youtube/youtube-ios-player-helper/issues/399#issuecomment-867539604)
> 
> [@denkeni](https://github.com/denkeni) just tried but no luck. Review team still rejects my app even i put Youtube ToS in review note. :(

The same for me! My app got rejected as well and The [YouTube API Services Terms of Service](https://developers.google.com/youtube/terms/api-services-terms-of-service) are not enough anymore.
