### ISSUE TITLE
Problems loading some YouTube URLs even on newest version

### ISSUE THREAD

**Issue by dragonsofthelostrealm** [0xced/XCDYouTubeKit#489]
This YouTube video for instance even in the example project on the newest CocoaPods version I can't download it there's just no video that plays back or anything 

https://www.youtube.com/watch?v=9bEWhQSyyOQ

Specifically the 720p stream option fails, but 480p etc do work. youtube-dl can get the 720p version fine though

**Comment by manobal** [comment]
I am also seeing the same issue even with the latest update. Here are few example video ids that are not playing for me:

n-0XaOsb1rs
9mxxuKMI3AM
pd32k45H9AM

Thanks,
Manobal

**Comment by kayazhou** [comment]
I have the same issue with the 720p stream.

480p works just fine.

**Comment by tungdangplus** [comment]
All videos, my app just get Livestream or quality 360, never get 720 nor 240. I don't know why.
