### ISSUE TITLE
Sometimes Parse web html error!

### ISSUE THREAD

**Issue by oTranAnhMinh** [0xced/XCDYouTubeKit#491]
Hello,

It's called:

case XCDYouTubeRequestTypeWatchPage:
   [self handleWebPageWithHTMLString:responseString];

Please help to check this error:

*** Assertion failure in -[XCDYouTubeClient getVideoWithIdentifier:cookies:customPatterns:completionHandler:], XCDYouTubeClient.m:69
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Both `video` and `error` can not be nil if the operation was not canceled.'

Thank you,

**Comment by phuocmobytelab** [comment]
anybody can help this issue?

**Comment by euroboy** [comment]
Same crash
