### ISSUE TITLE
Xcode 12 SPM `IPHONEOS_DEPLOYMENT_TARGET` warning

### ISSUE THREAD

**Issue by sereisoglu** [0xced/XCDYouTubeKit#496]
Hello.

I am getting this warning because of ".iOS (.v8)" in Package.swift:
<img width="310" alt="Screen Shot 2020-09-18 at 15 06 38" src="https://user-images.githubusercontent.com/29237103/93595600-b55c8d00-f9c0-11ea-8a18-28115477684e.png">

**Comment by SoneeJohn** [comment]
Thanks for reporting this! I will add a fix soon.
