### ISSUE TITLE
This is an query

### ISSUE THREAD

**Issue by JyotiChaurasia1** [0xced/XCDYouTubeKit#504]
1. If I use this library , Will my app be rejected by Apple as we are using YouTube video in iOS app?? Please help.
2. Some video id like "US8Uu6ZjWzU" are not playing in this library giving error like  "Video unavailable". I checked this video id is playing in browser.

**Comment by JyotiChaurasia1** [comment]
plz someone clarify my doubts..

**Comment by SoneeJohn** [comment]
I made some changes on the develop branch can you download that branch and try the demo app again and send me the logs?

You can download it here: https://codeload.github.com/0xced/XCDYouTubeKit/zip/develop

Thanks!

**Comment by SoneeJohn** [comment]
> 1. If I use this library , Will my app be rejected by Apple as we are using YouTube video in iOS app?? Please help.

1. I am not entirely sure some please have reported their app getting rejected. YMMV

**Comment by SoneeJohn** [comment]
Closed in 2.15.1
