### ISSUE TITLE
Certain videos stopped working

### ISSUE THREAD

**Issue by sherwinzadeh** [0xced/XCDYouTubeKit#508]
Recently the following videos have stopped working:

https://youtu.be/eRr0Fqo1aZU
https://youtu.be/k-aYRib3bHE
https://youtu.be/h7p5e2wyzP0
https://youtu.be/9cdoPD51bng
https://youtu.be/nkbTxAfWvNQ

I tested on iOS using 2.15.1. I am receiving a stream URL but it just spins forever in AVPlayerController in iOS.

**Comment by SoneeJohn** [comment]
@sherwinzadeh Please download this branch and use the macOS demo 

https://codeload.github.com/0xced/XCDYouTubeKit/zip/logs

**Comment by SoneeJohn** [comment]
Please my comment here:https://github.com/0xced/XCDYouTubeKit/issues/507#issuecomment-734324664  to see how the files will look and attach them to your report

**Comment by MhmdSalah** [comment]
I have the same problem. Some videos work, and some don't. The videos linked above all worked, but others did not. 

One example: https://www.youtube.com/watch?v=YQHsXMglC9A

I tried to use the macos demo, it keeps loading for a while but eventually it works, it only fails in the ios app.
When it fails, it does not return an error. Instead, it returns a non working url.

**Comment by SoneeJohn** [comment]
@MhmdSalah Did you get an error? Please include your logs.

**Comment by oTranAnhMinh** [comment]
I have the same problem after pull request. Cannot play the video stream url.

**Comment by SoneeJohn** [comment]
@oTranAnhMinh Did you receive an error?

**Comment by oTranAnhMinh** [comment]
@SoneeJohn I don't get any errors but the stream url can't seem to play.

**Comment by MhmdSalah** [comment]
> @SoneeJohn I want to confirm with you that, I just checked and found that the stream url is working properly again after I restarted my laptop. It's very strange! (release/2.15.1)

Me too.

**Comment by sherwinzadeh** [comment]
> @sherwinzadeh Please download this branch and use the macOS demo
> 
> https://codeload.github.com/0xced/XCDYouTubeKit/zip/logs

@SoneeJohn Apologies for the late reply but I have confirmed that the URLs I posted do work on the Mac Demo but not on the iOS Demo app. Is this a confirmed issue? Let me know if there is anything I can do to help investigate further.

**Comment by sherwinzadeh** [comment]
> Please my comment here:[#507 (comment)](https://github.com/0xced/XCDYouTubeKit/issues/507#issuecomment-734324664) to see how the files will look and attach them to your report

Here are my logs:
[Logs.zip](https://github.com/0xced/XCDYouTubeKit/files/5619481/Logs.zip)

But again it works in the macOS Demo App but fails on iOS

**Comment by Keane81** [comment]
I also encountered with the issue when library returns some url but player do not load it. Example of url is:

https://r2---sn-jvhnu5g-c35k.googlevideo.com/videoplayback?expire=1607046852&ei=ZELJX8CjGYf07ASfpLqYCA&ip=109.252.39.38&id=o-ANvXMxpslwySdFzTA_2dhgrEIH_lil7t6uF3Xu2cvmub&itag=18&source=youtube&requiressl=yes&mh=gz&mm=31%2C29&mn=sn-jvhnu5g-c35k%2Csn-jvhnu5g-n8ve7&ms=au%2Crdu&mv=m&mvi=2&pl=22&gcr=ru&initcwndbps=1460000&vprv=1&mime=video%2Fmp4&ns=RGYIArDn__bEBRukLI3yz_MF&gir=yes&clen=9194218&ratebypass=yes&dur=366.457&lmt=1593253505904753&mt=1607024922&fvip=2&c=MWEB&txp=5531432&n=jBLd5JOytzkF3FODq&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAKapR8PdaoF5rUtgemsSPdHPXtDH7yLVwIfhTrnnBXvOAiAE6glIWBqSPyLeVJnme8AsVAIpsw1rOli9pAVePkVssw%3D%3D&sig=KNQ2Oewqi3d52Y1ifnK69vtZIgqNHVxJ0Wgmg3VasNB6Cqymym1pkQHn0o5IJQlQrs0e2C7Vz_C4yHpZuxdvilvoHFfMbjyoGZul4Rl

**Comment by sherwinzadeh** [comment]
FYI -- If I use Low Resolution option in the demo app, it does work on iOS.

**Comment by Keane81** [comment]
No, I didn't. I've set it to false.

**Comment by Keane81** [comment]
@sherwinzadeh no, it doesn't work for me, sometimes I am getting url which is not loaded even if low resolution has been used.
