### ISSUE TITLE
For some videos returns a non video url

### ISSUE THREAD

**Issue by sukov** [0xced/XCDYouTubeKit#512]
The latest update (2.15.2) has a bug where some videos stream links are pointed to an url which contains `index.m3u8` instead of the video file.

It is always reproducible with certain videos.
Example video that has this behavior: https://www.youtube.com/watch?v=5onuaiFetFg

**Comment by MhmdSalah** [comment]
This is a live stream, correct?

**Comment by sukov** [comment]
Yes it is, my bad. But there is still an issue I think, `XCDYouTubeVideoQualityHTTPLiveStreaming` is not `nil` for non Live videos which got me confused in the first place. Closing this issue.
