### ISSUE TITLE
Question about video returns

### ISSUE THREAD

**Issue by SarahH12099** [0xced/XCDYouTubeKit#516]
NSDictionary *streamURLs = video.streamURLs;
NSURL *streamURL = streamURLs[XCDYouTubeVideoQualityHTTPLiveStreaming] ?: streamURLs[@(XCDYouTubeVideoQualityHD720)] ?: streamURLs[@(XCDYouTubeVideoQualityMedium360)] ?: streamURLs[@(XCDYouTubeVideoQualitySmall240)];
NSLog("URL: %@", streamURL);

Hello, for the streamURL, I was wondering is there a way to make it return always the full video url and not the m3u8 please? I noticed with some videos it will return the full video and some videos will return m3u8. Is it possible to make it where it will only return the full video url please?

**Comment by SarahH12099** [comment]
Never mind, sorry, I'm blind, lol

**Comment by flyling** [comment]
I don't want it returns m3u8. Now many videos it wll return m3u8. Who can help me?
