### ISSUE TITLE
streamURL = nil for "LIVE NOW" videos(youtube).

### ISSUE THREAD

**Issue by devbest555** [0xced/XCDYouTubeKit#538]
Before 4 days, all of the videos are worked(load/play) fine 
for now, common youtube videos work fine but "LIVE NOW" videos don't work anymore.
when I debug the code, streamURL = nil
who can help me? any good news?

This issue had been solved by @karimabees.

**Comment by tkachV** [comment]
Need update lib to new requirement.
<img width="753" alt="Screenshot 2021-06-23 at 13 20 00" src="https://user-images.githubusercontent.com/16904429/123082801-1b7eb080-d428-11eb-8e47-763c6b7c3e76.png">

**Comment by devbest555** [comment]
@tkachV 
Thank you for your information.
what should I change/add/update in the XCDYouTubeVideoKit?

**Comment by tkachV** [comment]
@devbest555 

Maybe it's not your case, but for me worked 
XCDYouTubeVideoOperation.m, line 152 change to:

NSDictionary *query = @{ @"video_id": self.videoIdentifier, @"hl": self.languageIdentifier, @"el": eventLabel, @"ps": @"default", @"html5" : @"1", @"c" : @"TVHTML5", @"cver" : @"6.20180913" };

added: [..., @"c" : @"TVHTML5", @"cver" : @"6.20180913"]

It's not tested for live-video.

**Comment by devbest555** [comment]
@tkachV 
I had added it in line 152 already but live-video doesn't work.
I wish you will test the live-videos(azl07ua79pa,  hartiIFC1s4).
If live-videos works fine, then Perfect and please inform me it

**Comment by FvorY** [comment]
@tkachV Thank you for your information, it works for me

**Comment by devbest555** [comment]
@FvorY 
can you show me your project or code for playing the "LIVE" video(ex : azl07ua79pa, hartiIFC1s4)?
Thank you in advance

**Comment by FvorY** [comment]
@devbest555 it not tested for live-video, my problem is video failed to play.

**Comment by devbest555** [comment]
@FvorY 
I asked it about live-video.
any idea?

**Comment by karimabees** [comment]
@devbest555 

XCDYoutubeVideo.m 
line 33
NSString *manifestURL = streamingData[@"hlsManifestUrl"];

There is no 'hlsManifestUrl' value.
Instead, I checked that there is 'dashManifestUrl' information. 

NSString *manifestURL = streamingData[@"dashManifestUrl"];

But this url seems unreliable. Interpretation is required. 
I can't interpret the value of 'dashManifestUrl'. Someone please if possible.

**Comment by tester89** [comment]
Can anyone fix this for Live video please. Thank you.

**Comment by karimabees** [comment]
@devbest555 @tester89 

I just checked that it works.

XCDYouTubeVideoOperation.m > [startWatchPageRequest] function works fine.
(*Looks better than using [get_video_info].)

* Modify to force [startWatchPageRequest] to be called.

----------
XCDYouTubeVideoOperation.m (line 442)
(Temporarily delete [eventLabels] so that [startWatchPageRequest] is executed)
----------
self.eventLabels = [[NSMutableArray alloc] initWithArray:@[ @"embedded", @"detailpage" ]];
--->> [Edit]
self.eventLabels =[[NSMutableArray alloc] init];

----------
XCDYouTubeVideo.m
----------
NSString *httpLiveStream = info[@"hlsvp"] ?: XCDHTTPLiveStreamingStringWithString(playerResponse);
--->> [Edit]
NSString *httpLiveStream = info[@"hlsvp"] ?: XCDHTTPLiveStreamingStringWithString(playerResponse);
 if(httpLiveStream.length == 0){
         httpLiveStream = info[@"streamingData"][@"hlsManifestUrl"];
}

**Comment by devbest555** [comment]
Great news,
Let me follow you and test the app.
After test,  let me email you instantly.
Thank you in advance

**Comment by devbest555** [comment]
Hi, karimabees
Many thank you.
I tested the app with your code and it does work fine.
Wonderful !!!
Thank you again.

**Comment by Candygoblen123** [comment]
I've set up a fork with the changes, you should be able to use CocoaPods with it like this:
`pod 'XCDYouTubeKit', :git => 'https://github.com/Candygoblen123/XCDYouTubeKit'`

**Comment by devbest555** [comment]
Thank you.
I already fixed the error based on karimabees suggestion.
Thank you again.

**Comment by devbest555** [comment]
For both of Live-video and common-videos : 
1. XCDYouTubeVideoOperation.m
self.eventLabels = [[NSMutableArray alloc] initWithArray:@[ @"embedded", @"detailpage" ]];
--->> [Edit]
self.eventLabels =[[NSMutableArray alloc] init];

2. XCDYouTubeVideo.m
NSString *httpLiveStream = info[@"hlsvp"] ?: XCDHTTPLiveStreamingStringWithString(playerResponse);
--->> [Edit]
NSString *httpLiveStream = info[@"hlsvp"] ?: XCDHTTPLiveStreamingStringWithString(playerResponse);
if(httpLiveStream.length == 0){
httpLiveStream = info[@"streamingData"][@"hlsManifestUrl"];
}

I added above code and then Worked fine.

**Comment by AshokRadadiya** [comment]
> For both of Live-video and common-videos :
> 
> 1. XCDYouTubeVideoOperation.m
>    self.eventLabels = [[NSMutableArray alloc] initWithArray:@[ @"embedded", @"detailpage" ]];
>    --->> [Edit]
>    self.eventLabels =[[NSMutableArray alloc] init];
> 2. XCDYouTubeVideo.m
>    NSString *httpLiveStream = info[@"hlsvp"] ?: XCDHTTPLiveStreamingStringWithString(playerResponse);
>    --->> [Edit]
>    NSString *httpLiveStream = info[@"hlsvp"] ?: XCDHTTPLiveStreamingStringWithString(playerResponse);
>    if(httpLiveStream.length == 0){
>    httpLiveStream = info[@"streamingData"][@"hlsManifestUrl"];
>    }
> 
> I added above code and then Worked fine.

not working for me

**Comment by devbest555** [comment]
Hi,  @AshokRadadiya 
Please find your method and then comment here.

**Comment by AshokRadadiya** [comment]
> Hi, @AshokRadadiya
> Please find your method and then comment here.

working sir, thank you!
