### ISSUE TITLE
Crash on iOS 8

### ISSUE THREAD

**Issue by jacks8x** [0xced/XCDYouTubeKit#70]
It crash on iOS 8. I see it crash when call (id) initWithVideoIdentifier:(NSString *)videoIdentifier method, right after you call self = [super init].

**Comment by 0xced** [comment]
I finally wrote it: https://github.com/0xced/XCDYouTubeKit/blob/develop/CONTRIBUTING.md

**Comment by asapo** [comment]
:smiley: :+1:
