### ISSUE TITLE
Integrating XCDYoutubeKit in XCode 6 to support IOS8

### ISSUE THREAD

**Issue by Priyanka-Razdan** [0xced/XCDYouTubeKit#71]
HI,

I had integrated previous version "XCDYoutubeVideoPlayerViewController " which works fine when after running it on IOS8 it crashes. So want to integrate this latest version for IOS 8 support.
But facing issues. Following are the warning which i get while integrating XCDYoutubeKIt in Xcode6.

ld: warning: directory not found for option '-F/Applications/Xcode 3.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks'
Undefined symbols for architecture i386:
  "_JSContextGetGlobalObject", referenced from:
      -[XCDYouTubePlayerScript initWithString:] in XCDYouTubePlayerScript.o
  "_JSEvaluateScript", referenced from:
      -[XCDYouTubePlayerScript initWithString:] in XCDYouTubePlayerScript.o
  "_JSGlobalContextCreate", referenced from:
      -[XCDYouTubePlayerScript initWithString:] in XCDYouTubePlayerScript.o
  "_JSGlobalContextRelease", referenced from:
      -[XCDYouTubePlayerScript dealloc] in XCDYouTubePlayerScript.o
  "_JSObjectCallAsFunction", referenced from:
      -[XCDYouTubePlayerScript unscrambleSignature:] in XCDYouTubePlayerScript.o
  "_JSObjectIsFunction", referenced from:
      -[XCDYouTubePlayerScript initWithString:] in XCDYouTubePlayerScript.o
  "_JSObjectSetProperty", referenced from:
      -[XCDYouTubePlayerScript initWithString:] in XCDYouTubePlayerScript.o
  "_JSStringCopyCFString", referenced from:
      -[XCDYouTubePlayerScript unscrambleSignature:] in XCDYouTubePlayerScript.o
  "_JSStringCreateWithCFString", referenced from:
      -[XCDYouTubePlayerScript initWithString:] in XCDYouTubePlayerScript.o
      -[XCDYouTubePlayerScript unscrambleSignature:] in XCDYouTubePlayerScript.o
  "_JSStringRelease", referenced from:
      -[XCDYouTubePlayerScript initWithString:] in XCDYouTubePlayerScript.o
      -[XCDYouTubePlayerScript unscrambleSignature:] in XCDYouTubePlayerScript.o
  "_JSValueIsObject", referenced from:
      -[XCDYouTubePlayerScript initWithString:] in XCDYouTubePlayerScript.o
  "_JSValueIsString", referenced from:
      -[XCDYouTubePlayerScript unscrambleSignature:] in XCDYouTubePlayerScript.o
  "_JSValueMakeString", referenced from:
      -[XCDYouTubePlayerScript initWithString:] in XCDYouTubePlayerScript.o
      -[XCDYouTubePlayerScript unscrambleSignature:] in XCDYouTubePlayerScript.o
  "_JSValueToStringCopy", referenced from:
      -[XCDYouTubePlayerScript unscrambleSignature:] in XCDYouTubePlayerScript.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Please advice.
Thanks in advance.

**Comment by ananarola** [comment]
Hi... i am also new to github... Guys can u please share the link for  XCDYouTubeKit 2.0.2.
