### ISSUE TITLE
Issue in iOS 7 

### ISSUE THREAD

**Issue by thibautrey** [0xced/XCDYouTubeKit#8]
I get this issue each time with video on iOS 7 : 
_itemFailedToPlayToEnd: {
    kind = 1;
    new = 2;
    old = 0;
}

Everything was okay before the update. I guess something is wrong with one of the library. 

Do someone has the same problem ?

**Comment by minniTomar** [comment]
I am getting this issue from with video in ios 7

**Comment by 0xced** [comment]
Please follow the discussion in issue #105.
