### ISSUE TITLE
Landscape Mode When Viewing Video?

### ISSUE THREAD

**Issue by bennettl** [0xced/XCDYouTubeKit#82]
I need my app to be by default in portrait mode, but because of this, when the user is watching the youtube video, he can't turn the video to landscape mode? I was wondering how to enable landscape mode for viewing youtube videos but when the user go's back to my app, have it stay in portrait mode? Thanks!

**Comment by devilbags** [comment]
Just observe when the XCDYoutubePlayerViewController will enter or exit fullscreen mode, then set the 'orientation' value of current device to landscape. use 'MPMoviePlayerWillEnterFullscreenNotification' and 'MPMoviePlayerWillExitFullscreenNotification'

**Comment by hoangphan92** [comment]
I found solution in here:  https://gist.github.com/MylesCaley/75a08a3006ad0109271b5fdc5075dfc7
hope it will useful for you !! ^^
