### ISSUE TITLE
How can I catch the events from XCDYouTubeVideoPlayerViewController?

### ISSUE THREAD

**Issue by vietanh85** [0xced/XCDYouTubeKit#90]
Hi, Thank you so much form your great library. 

I just wondering if are there anyway to catch and hook some events from XCDYouTubeVideoPlayerViewController such as:
- load video finshed
- error on loading video
- etc

Thank you so much,
Anh.

**Comment by anansi** [comment]
These notifications arent working in iOS 9. Is this related to the deprecation?

**Comment by 0xced** [comment]
They are working fine for me in the demo app running on iOS 9.2. Have you tried to add a breakpoint to see if the notifications are properly registered and fired?
