### ISSUE TITLE
VEVO/WMG/SME videos blocked?

### ISSUE THREAD

**Issue by nahum365** [0xced/XCDYouTubeKit#94]
I can't get any VEVO/SME videos (or any other official music videos) using XCDYouTubeKit. It just started happening, and my app was just released. Is this a change made by YouTube?

**Comment by airrons** [comment]
does here have any other issus to be resolved ?

**Comment by Fabio8511** [comment]
How can I play WMG video ?

**Comment by frakman1** [comment]
I just got this to fail with a WMG video. I am using version 2.2.0 and am located in the USA. 
Relevant logs:

```
videoId: bvC_0foemLY
url: https://www.youtube.com/watch?v=bvC_0foemLY
 [XCDYouTubeKit] JavaScript exception: TypeError: undefined is not an object (evaluating 'window.location.hash')
 [XCDYouTubeKit] Video operation finished with error: This video contains content from WMG. It is restricted from playback on certain sites. Watch on YouTube
Domain: XCDYouTubeVideoErrorDomain
Code:   150
User Info: {
    NSLocalizedDescription = "This video contains content from WMG. It is restricted from playback on certain sites. Watch on YouTube";
    NSURL = "https://www.youtube.com/get_video_info?el=embedded&hl=en&ps=default&video_id=bvC_0foemLY";
}
```
My code snippet:
```    
    [[XCDYouTubeClient defaultClient] getVideoWithIdentifier:videoId completionHandler:^(XCDYouTubeVideo *video, NSError *error) {
        if (video)
        {
            self.VidPlayer = [[XCDYouTubeVideoPlayerViewController alloc] initWithVideoIdentifier:videoId];
            self.VidPlayer.moviePlayer.backgroundView.backgroundColor = [UIColor colorWithRed:10 green:31 blue:49 alpha:1];
            [self presentMoviePlayerViewControllerAnimated:self.VidPlayer];
        }
        else
        {
            // Handle error
            NSLog(@"***ERROR LOADING VIDEO ***");
        }
    }];
```   
When I tried to play it anyway ie if(1), it would launch the player and immediately exit back to the previous screen.
I hope that gives you everything you need to reproduce it. Let me know if you need anything else. 
(Thank you for writing this excellent library by the way)

**Comment by 0xced** [comment]
@frakman1 This issue have been solved in version 2.3.2 (see #186).

Also, you should not use `XCDYouTubeClient` at all when using `XCDYouTubeVideoPlayerViewController` because you will end up fetching the video information twice. I have updated the README to demonstrate how to [properly handle errors](https://github.com/0xced/XCDYouTubeKit/tree/6e799b7b8028ba0df464d570354efab3ff85fefb#present-the-video-in-full-screen) with `XCDYouTubeVideoPlayerViewController`.

**Comment by frakman1** [comment]
@0xced  Thank you Cedric for:
1- Responding so promptly
2- Informing me of the new version that fixes this. I upgraded and it works now.
3- Pointing out the redundancy in my code. Part of the confusion comes from the Usage section of the README file in the master branch. I think the link you included was for the developer branch. I get it now but it wasn't clear from the original README.

**Comment by 0xced** [comment]
Indeed, I updated the README just after reading your code snippet. The new README will be available on master when I release the next version of XCDYouTubeKit.

**Comment by omose14** [comment]
Hey is there an updated version that fixes the restrictions now?
