### ISSUE TITLE
In fullscreen mode, fast forward and fast rewind buttons are causing unstoppable "loading..."screen.

### ISSUE THREAD

**Issue by serdarsenol** [0xced/XCDYouTubeKit#99]

**Comment by 0xced** [comment]
I was able to reproduce this issue if I tap the back or forward button just when the time scrubber appears in the top bar but before the video actually starts. Unfortunately, this behavior is also occurs on a `MPMoviePlayerViewController`. I was able to reproduce this issue with this simple code:
```objc
NSURL *movieURL = [NSURL URLWithString:@"http://download.blender.org/peach/bigbuckbunny_movies/BigBuckBunny_320x180.mp4"];
MPMoviePlayerViewController *moviePlayerViewController = [[MPMoviePlayerViewController alloc] initWithContentURL:movieURL];
[self presentMoviePlayerViewControllerAnimated:moviePlayerViewController];
```
Unfortunately, it means there’s not much that XCDYouTubeKit can do about it.

If this is an important issue for you, I suggest you to build your own fullscreen video player based on AVFoundation and integrate it with [XCDYouTubeClient](http://cocoadocs.org/docsets/XCDYouTubeKit/2.0.2/Classes/XCDYouTubeClient.html).
